### ISSUE TITLE
TimeAs and LengthAs slow

### ISSUE THREAD

**Issue by f3flight** [melanchall/drywetmidi#10]
@melanchall I decided to open a separate bug for this since it's not really related to https://github.com/melanchall/drywetmidi/issues/8. I noticed that with the same test midi file I provided there it takes ~17 sec on my i7 laptop's core to extract each TimedObject's absolute time:
`MetricTimeSpan t = event.TimeAs<MetricTimeSpan>(tmap)`
and for Notes also:
`MetricTimeSpan l = note.LengthAs<MetricTimeSpan>(tmap)`

So it's rather slow... a few times slower than my older implementation. Maybe some optimization can be done around recurrent TimeAs / LenghAs calls, some unnecessarily repeated operation can be skipped?

test code:
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using Melanchall.DryWetMidi.Smf;
using Melanchall.DryWetMidi.Smf.Interaction;

namespace test
{
    class MainClass
    {
        public static void Main()
        {
            Stream stream = new FileStream("/home/dsutyagin/Downloads/test.mid", FileMode.Open, FileAccess.Read);
            MidiFile midiFile = MidiFile.Read(stream);
            Stopwatch stopwatch = Stopwatch.StartNew();
            IEnumerable<ITimedObject> timedObjectsAndNotes = midiFile.GetTimedEvents().ExtractNotes();
            Console.WriteLine(stopwatch.ElapsedMilliseconds);
            stopwatch.Restart();
            TempoMap tmap = midiFile.GetTempoMap();
            Console.WriteLine(stopwatch.ElapsedMilliseconds);
            stopwatch.Restart();
            int i = 0;
            foreach (ITimedObject x in timedObjectsAndNotes)
            {
                // comment me N1 - saves 6 sec
                MetricTimeSpan t = x.TimeAs<MetricTimeSpan>(tmap);

                i++;
                Note note = x as Note;
                if (note != null)
                {
                    i++;

                    //comment me N2 - saves 10 sec
                    MetricTimeSpan l = note.LengthAs<MetricTimeSpan>(tmap);
                }
            }
            Console.WriteLine(stopwatch.ElapsedMilliseconds);
        }
    }
}
```
sample output:
```
70
146
16918

Press any key to continue...
```

**Comment by f3flight** [comment]
Not anywhere as bad on my desktop Win10 machine though... Just under 5 sec overall
![image](https://user-images.githubusercontent.com/6680260/40208066-a2954e94-59ec-11e8-8f82-48b7264428a8.png).

However if we compare with MidiSharp-based example (with my patch https://github.com/f3flight/MidiSharp/commit/a7614bd402d688ff38ddbf3f2d55c614c742c00b), the results are:
![image](https://user-images.githubusercontent.com/6680260/40208754-1f7bd592-59f0-11e8-9eee-b9cd1616d678.png)
So it's about 200 times faster...

**Comment by f3flight** [comment]
I wonder if we can make DryWetMidi anywhere as fast...

**Comment by f3flight** [comment]
Specifically slow items are these two lines:
![image](https://user-images.githubusercontent.com/6680260/40209589-05444a1a-59f5-11e8-9a7b-38d0abcb713e.png)

- `if (!tempoChanges.Any())`
- `foreach (var tempoChange in tempoChanges.Concat(new[] { new ValueChange<Tempo>(time, tempoLine.AtTime(time)) }))`

**Comment by f3flight** [comment]
I made an improvement, let me make a pull request..

**Comment by f3flight** [comment]
with this change I get down to ~1.8s in Release profiling:
![image](https://user-images.githubusercontent.com/6680260/40213034-3bbe80de-5a08-11e8-9e0a-1b77512acc3f.png)
without it I get around ~2.8s
![image](https://user-images.githubusercontent.com/6680260/40213268-75115c84-5a09-11e8-96f0-5bd38d3c012f.png)

**Comment by f3flight** [comment]
it's interesting that after this patch, allocating doubles is slow... whaat?
![image](https://user-images.githubusercontent.com/6680260/40213369-f6b4651a-5a09-11e8-955f-7f4a5d580341.png)
I'll see if I can improve performance further...

**Comment by f3flight** [comment]
I guess it's just the whole design around IEnumerables which is progressively slower with each added layer of complexity over source data... So getting anywhere near the MidiSharp's result is unlikely without using some sort of cache...

**Comment by melanchall** [comment]
@f3flight Thanks for opening the issue. I am concerned about performance and planning to do some improvements in future releases.

You are right, we need sort of cache to store accumulated microseconds at points of tempo change. I'll think about possible solutions. Maybe I'll introduce something like `ITempoMapCache` with different implementations for each type of time span and also introduce conversion methods that take that cache instead of `TempoMap`.

Thanks for pull request, I'll look into it as soon as possible.

**Comment by melanchall** [comment]
I tested caching and performed benchmarks with this code:

```csharp
foreach (var e in _timedEvents)
{
    var mt = e.TimeAs<MetricTimeSpan>(_tempoMap);
}
```

Results:
**without caching** ~3.970 s
**with caching** ~183.5 ms

So yes, cache gives significant performance boost.

**Comment by f3flight** [comment]
@melanchall sounds great! cant wait to see it implemented, i will then move forward with my project using your lib.

**Comment by mjbath** [comment]
Hi Dmitry,

I’m working on some music theory stuff on top of Max’s library.  What are you working on?

Thanks,
Mark
________________________________

**Comment by f3flight** [comment]
@mjbath https://www.youtube.com/watch?v=tgpBUSRmtwE
Want to embed a midi player with functionality similar to Yousician's practice mode.

**Comment by f3flight** [comment]
@mjbath I'm also very interested in collaboration so if you are interested as well we can join efforts, you can PM me in FB or Telegram as f3flight

**Comment by melanchall** [comment]
@f3flight I've implemented caching for metric time span conversion (I forgot about linking to an issue inside a commit message so the commit is [b008c6c](https://github.com/melanchall/drywetmidi/commit/b008c6c4ef2a0c3b24d6877b26e1d0745116c8ff)). For this task I've created benchmarks that were ran on this environment:

```
BenchmarkDotNet=v0.10.12, OS=Windows 10.0.17134
Intel Core i5-7200U CPU 2.50GHz (Kaby Lake), 1 CPU, 4 logical cores and 2 physical cores
Frequency=2648438 Hz, Resolution=377.5810 ns, Timer=TSC
  [Host] : .NET Framework 4.7 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3101.0
  Clr    : .NET Framework 4.7 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3101.0
```

Results are:

| Conversion | Mean (without cache, ms) | Mean (with cache, ms) |
| ----- | ----------------------------:| -------------------------:|
|     Time from ticks to metric | 1320.3 | 59.12
|   Length from ticks to metric | 2640.3 | 116.50
|   Time from metric to ticks |   528.7 | 58.21
| Length from metric to ticks | 1834.8 | 118.51

There is no any new public API, caching works internally with regular `TempoMap` so you don't need to change anything in your code that uses DryWetMIDI.

As you can see from the commit I've created benchmarks for every time span, but note that at the moment performance is improved only for `MetricTimeSpan` conversion. In fact `BarBeatTimeSpan` conversion is extremely slow on large collections of events or notes too. It will be handled in another commit, so please don't close the issue.

Please take the latest version of the _develop_ branch and verify that metric conversion is faster now. I'm waiting for your results.

**Comment by f3flight** [comment]
@melanchall I confirm significant (~10x) speed up achieved, thank you very much for this improvement.

**Comment by melanchall** [comment]
The main problem was `TempoMap.Tempo.Values` and `TempoMap.TimeSignature.Values` were resorted on every get. So values sorting was performed for each time/length conversion. I eliminated unnecessary sortings and benchmarks results for bar/beat time span conversion are:

| Conversion | Mean (old, ms) | Mean (new, ms) |
| ----- | ----------------------------:| -------------------------:|
|     Time from ticks to bar/beat | 972.5 | 189.7
|   Length from ticks to bar/beat | 1159.1 | 167.3
|   Time from bar/beat to ticks |   1133.9 | 192.3
| Length from bar/beat to ticks | 1610.2 | 228.5

@f3flight Can the issue be closed?

**Comment by f3flight** [comment]
I guess so, thank you!
