### ISSUE TITLE
DryWetMidi Hides Some Members of the Timer Classes 

### ISSUE THREAD

**Issue by TDNCompute** [melanchall/drywetmidi#102]
Some of the critical members of the timer classes are protected and therefore can't be used by an application without subclassing. It would be nice if there was an accurate tempo PPQN clock (96 PPQN minimum) with the necessary functions to implement time-accurate arpeggiators and other real-time MIDI applications.

**Comment by melanchall** [comment]
@TDNCompute Will you provide the info?

**Comment by melanchall** [comment]
For info, you can always use [`MidiClock`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.MidiClock.html) class with any desired tick generator (high precision one used by default).

I'm closing the issue since there is no info about the problem.

**Comment by TDNCompute** [comment]
your previous messages wound up in my spam folder. If you want to give me a
day I can elaborate on the issue for you.

**Comment by melanchall** [comment]
Yes, of course :) Reopening.

**Comment by melanchall** [comment]
So... Any info?

**Comment by TDNCompute** [comment]
I wrote a small program to route midi in to midi out to utilize my new keyboard controller with an old synthesizer module I had. This program proved to be useful, so I added more features to control the synthesizer module such as program/bank selection, sustain pedal, etc.  Now I would like to add an arpeggiator to the program. An arpeggiator is a tool that uses MIDI to cycle through a pre-programmed series of notes. What I would do is play a chord on my keyboard, my program would detect the chord on midi in, and generate and send an arpeggiated pattern of notes based on the chord to midi out. 

You mentioned that I could use the high performance timer, but the sample code you sent me wouldn't compile because the class members you suggested that I use were not public members. 

What I would like is a steady tempo generator with a callback where I could send the midi notes to midi out in the callback.

TempoGen tg = new InternalTempoGen(120);  //120 beats per minute
tg.Callback += MyCallback;
tg.Start();

The tempo generator with these settings would call MyCallback 24 times per beat at 120 beats per minute.   The 24 times per beat is known as pulses per quarter note, and the division allows the arpeggiated sequences to use 8th,16th, triplets, etc.

**Comment by melanchall** [comment]
DryWetMIDI provides [MidiClock](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.MidiClock.html) class which can be used as timer for your program (please read the documentation by provided link). But it accepts interval in terms of milliseconds, so we need a method to convert BPM to milliseconds. So we can use this code:

```csharp
var bpm = 120;

var midiClock = new MidiClock(true, new HighPrecisionTickGenerator(), TimeSpan.FromMilliseconds(60000.0 / bpm));
midiClock.Ticked += OnTicked;
midiClock.Start();

...

private void OnTicked(object sender, EventArgs e)
{
    // do whatever you want
}
```

Please let me know if it works.

**Comment by melanchall** [comment]
@TDNCompute Any news?

**Comment by TDNCompute** [comment]
Yes, this worked enough for my purposes.
