### ISSUE TITLE
Using Midi track to trigger effects at the time of the note

### ISSUE THREAD

**Issue by Echoframe** [melanchall/drywetmidi#104]
Hi, this has probably been asked dozen of times but i just don't understand from reading the existing issues (like#79).
What i would like to do is:

-read the midi file
-have the notes map some sort of "active" or "playing" to a variable or function (if its the note value on a scale from 1 to 88 even better)
-use said variable/function to trigger other stuff (like blendshapes)

If what i described was possible at runtime thats amazing, not necessary though

I hope you have the time to help me!
Thank you

**Comment by melanchall** [comment]
Hi,

Can you please describe the problem in more details? Do you need to start [playback](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html) of a MIDI file and do some things when some notes are started playing?

**Comment by Echoframe** [comment]
Hi, thanks for answering me first of all!

I would like to have a midi file direct the state of a variable or function at runtime, meaning whenever there is a note in the midi file the value changes accordingly.

For a song that has only three notes that are 1 second apart that would be:

Start

variable = [Notenumber] (something like 0 for lowest note possible) **>at time 0 sec<**
variable = [Notenumber] **>at time 1 sec<**
variable = [Notenumber] **>at time 2 sec<**

So yeah, i would like stuff to happen whenever a midi note is played, i don't need the midi to actually play though.

My plan is to have shapekeys triggered by midi notes at their corresponding time, be it from an .anim file that was created from a midi file or at runtime.

**Comment by melanchall** [comment]
You can start playback without output device and attach event handler triggered by notes starts. Small example:

```csharp
private static Playback _playback;

static void Main(string[] args)
{
    var midiFile = MidiFile.Read("My MIDI file.mid");
    _playback = midiFile.GetPlayback();
    _playback.NotesPlaybackStarted += OnNotesPlaybackStarted;

    _playback.Start();

    Console.ReadKey();
}

private static void OnNotesPlaybackStarted(object sender, NotesEventArgs e)
{
    foreach (var note in e.Notes)
    {
        // do whatever you want with note
    }
}
```

Don't forget to call `_playback.Dispose()` when you're done with playback or your program.

Please read these pages to learn moreabout playback API:
* https://melanchall.github.io/drywetmidi/articles/playback/Overview.html
* https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.Playback.html

**Comment by Echoframe** [comment]
Okay, i was trying to have it put out the note.NoteNumber with Debug.Log but it doesn't work. Is there a data type issue here?

```
foreach (var note in e.Notes)
        {
            Debug.Log(note.NoteNumber);
        }
```

**Comment by melanchall** [comment]
Provide the full code of your program please.

**Comment by Echoframe** [comment]
```
using Melanchall.DryWetMidi.Core;
using Melanchall.DryWetMidi.Devices;
using Melanchall.DryWetMidi.Interaction;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditorInternal;
using UnityEngine;

public class gooMidiEvent : MonoBehaviour
{
    private static Playback _playback;

    static void Main(string[] args)
    {
        var midiFile = MidiFile.Read("Assets/test.mid");
        _playback = midiFile.GetPlayback();
        _playback.NotesPlaybackStarted += OnNotesPlaybackStarted;

        _playback.Start();

        Console.ReadKey();
       _playback.Dispose()

    }

    private static void OnNotesPlaybackStarted(object sender, NotesEventArgs e)
    {
        
        foreach (var note in e.Notes)
        {
            //notekey = note.NoteNumber;

            Console.WriteLine(note.NoteNumber);
            // do whatever you want with note
        }
    }
}
```

**Comment by melanchall** [comment]
It seems you just copy/paste my code. I suppose your `Main` method never called, right?

I suppose you use Unity. You should learn how to use it. From what I know, you need use `Start` method which called when you press **Play** button in Unity editor. Please check out this issue (it seems it's similar to yours): [trigger object with a note in Unity](https://github.com/melanchall/drywetmidi/issues/85).

**Comment by melanchall** [comment]
@Echoframe Did you solve the problem?

**Comment by melanchall** [comment]
I'm closing the issue since there are no comments.
