### ISSUE TITLE
Some basic functions. 

### ISSUE THREAD

**Issue by CIRCE-EYES** [melanchall/drywetmidi#105]
![Screenshot](https://user-images.githubusercontent.com/69172266/99461265-c6c70480-2931-11eb-8f16-56cc97e4dfb9.jpg)

[Basic_Functions-From DryWet-Melanchall.zip](https://github.com/melanchall/drywetmidi/files/5556715/Basic_Functions-From.DryWet-Melanchall.zip)

Well, this is a simple application that allows you to see only some functionalities of the wonderful library of the author MELANCHALL - DryWetmidi - (github.com/melanchall/drywetmidi) or (melanchall.github.io/drywetmidi). 
It is made under Visual Studio 2019 VB.net, perhaps with time and if I add more examples, I will pass it to C #. But my basic knowledge is limited to vb.net. 
I must appreciate all the help of the creator of this library in many aspects of the C # syntax to be able to adapt it to this demo and thus see how to transcribe it to vb.net. I have made this demonstration of basic functions for all those people who do not have much knowledge in programming, and there is nothing like a complete example to study it from beginning to end. It consists of several functions: 

1- It is focused on the simultaneous reproduction of midi files in loop mode and sending of midi notes, thus being able while the file is playing, playing the virtual piano (in addition to selecting the channel to your liking), playing chords placed in a listbox, etc. 

2- The valuable Record function allows you to record EVERYTHING, through the InputDevice input, that is, you can connect an external keyboard via USB and not only record the incoming notes, you can also add midis, chords, virtual piano notes, etc. we go all in a midi soup and create a midi file with all those incoming data !!! 

3- It has a listbox with four chords, which belong to a kind of database with 960 chords + Bass note variants, written in the Module1.vb file, I only put 4 but adding a panel with all the items it becomes a whole library of chords. I hope it is useful for you.

 If you can think of more features to add, it would be great to share it with everyone! We would all learn. 

Greetings to the creator ... Melanchall.

**Comment by melanchall** [comment]
@CIRCE-EYES Thanks for the program and for using the library! I hope your app will be helpful for other users of the library.

Max
