### ISSUE TITLE
Channel Sound

### ISSUE THREAD

**Issue by 3yggy** [melanchall/drywetmidi#107]
Do midis store channel sounds/instrument names. How am I meant to realize the sounds other than by using standards like drums on 9, which no one follows?

**Comment by melanchall** [comment]
Hi,

MIDI files can contain [Program Change](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.ProgramChangeEvent.html) and [Instrument Name](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.InstrumentNameEvent.html) events. So you can take such events from a MIDI file and decide what instrument used.

For example:

```csharp
var programChangeEvents = midiFile
    .GetTimedEvents()
    .Where(e => e.Event.EventType == MidiEventType.ProgramChange)
    .ToArray();

var instrumentNameEvents = midiFile
    .GetTimedEvents()
    .Where(e => e.Event.EventType == MidiEventType.InstrumentName)
    .ToArray();
```

**Comment by 3yggy** [comment]
Hello,

Is there no connection to the channel and the InstrumentName event or its inheritance? If I want to find the first instrument played in each channel, do I have to look at the note following the instrument change?

Thank you

**Comment by melanchall** [comment]
MIDI channel is not applicable to meta events. Instrument Name event is a [meta event](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.MetaEvent.html) and thus yes, you need to look at following channel events (like Not On on any other inherited from [ChannelEvent](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.ChannelEvent.html) class) within the same track chunk:

```csharp
foreach (var trackChunk in midiFile.GetTrackChunks())
{
    var midiEvents = trackChunk.Events;

    var instrumentNameEvent = midiEvents.FirstOrDefault(e => e.EventType == MidiEventType.InstrumentName);
    if (instrumentNameEvent == null)
    {
        // there is no Instrument Name event within the track chunk
        continue;
    }

    var channelEvent = midiEvents
        .SkipWhile(e => e != instrumentNameEvent)
        .Skip(1)
        .OfType<ChannelEvent>()
        .FirstOrDefault();

    if (channelEvent == null)
    {
        // there is no channel event after Instrument Name one
        continue;
    }

    var channel = channelEvent.Channel;
}
```

**Comment by 3yggy** [comment]
Thank you very much
