### ISSUE TITLE
Out Of Memory Win 10 on StartEventsListening

### ISSUE THREAD

**Issue by ted-dgk** [melanchall/drywetmidi#109]
I have been working with midiclock and output devices without issue. Much fun - thank you.

Now I am moving to input device (Launchkey 49 MKII) and have an out of memory exception. Here is the code:
```
            inputDevice = InputDevice.GetByName(MIDIIN2_Launchkey_MIDI);
            inputDevice.EventReceived += InputDevice_EventReceived;
            inputDevice.ErrorOccurred += InputDevice_ErrorOccurred;
            inputDevice.StartEventsListening();

```
As soon as I call StartEventsListening I get the exception. I know this isn't much to go on and I don't expect you to tell me what the issue might, but I have no idea of how to debug this. Anything you might be able to suggest? (BTW not using usb-c). I have the latest version. I can read midi events from the Launchkey with javascript.

I'll keep playing with it and let you know if I find anything.

Thanks
Ted

**Comment by melanchall** [comment]
Hi Ted,

Hm, strange. I never heard about such problems from users of the library. The only idea I have is:
1. download sources from **master** branch
2. build the library by yourself in **Debug** mode (you can throw away _Tests_ and _Benchmarks_ projects)
3. reference the DLL you've built instead the one you're referencing currently

Now you can dig into `StartEventsListening` in debug to know what exact instruction causes the exception. Can you please do this?

Max

**Comment by ted-dgk** [comment]
Just started looking at it

A Pinvoke is returning the error. Possible driver issue?? I'll continue to look. Thanks.

`public static extern uint midiInOpen(out IntPtr lphMidiIn, int uDeviceID, MidiWinApi.MidiMessageCallback dwCallback, IntPtr dwInstance, uint dwFlags);
`

**Comment by ted-dgk** [comment]
I rebooted the machine and did not start any programs so nothing should have been accessing the keyboard. I reran and now get past that error but get a new one:

The specified device is already in use.  Wait until it is free, and then try again.

**Comment by ted-dgk** [comment]
Midi on windows seems kind of wonky. Many posts said you did not need a driver if your device was class compliant (and it seemed to work in many situations like js). But the Launchkey website had a specific driver for this device family and I installed it. After a few no-go, things started working.

Hopefully this helps someone else.

Thanks for the help. Great Library.
Ted

**Comment by melanchall** [comment]
Thank you for your investigation on Launchkey driver. Definitely useful information. And thanks for using the library! :)
