### ISSUE TITLE
BeatsPerMinute value error

### ISSUE THREAD

**Issue by RadioDisney** [melanchall/drywetmidi#110]
Melanchall.DryWetMidi.Interaction.Tempo.BeatsPerMinute
When the bpm is 69.999988333335278，this feild return 69

**Comment by melanchall** [comment]
Hi,

Yes, we need to change the type of BeatsPerMinute to `double`. I'll do this and let you know.

Thanks,
Max

**Comment by melanchall** [comment]
I changed the type of the `BeatsPerMinute` property to `double`. Now it's up to you how to round its value.

Changes are in _develop_ branch. You can either build the library from sources or take new DLL from here:
* [.NET Framework version](https://artprodsu6weu.artifacts.visualstudio.com/Ada86e53e-02d0-42a7-ad86-d86986ae81da/d286d31e-d5f6-443f-b126-d81074c91872/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL01lbGFuY2hhbGwvcHJvamVjdElkL2QyODZkMzFlLWQ1ZjYtNDQzZi1iMTI2LWQ4MTA3NGM5MTg3Mi9idWlsZElkLzExNjY2L2FydGlmYWN0TmFtZS9CaW5hcmllcw2/content?format=file&subPath=%2FDryWetMIDI.5.1.3-bin-net45.zip)
* [.NET Standard version](https://artprodsu6weu.artifacts.visualstudio.com/Ada86e53e-02d0-42a7-ad86-d86986ae81da/d286d31e-d5f6-443f-b126-d81074c91872/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL01lbGFuY2hhbGwvcHJvamVjdElkL2QyODZkMzFlLWQ1ZjYtNDQzZi1iMTI2LWQ4MTA3NGM5MTg3Mi9idWlsZElkLzExNjY2L2FydGlmYWN0TmFtZS9CaW5hcmllcw2/content?format=file&subPath=%2FDryWetMIDI.5.1.3-bin-netstandard20.zip)

Thanks for the issue and for using the library.

**Comment by melanchall** [comment]
@RadioDisney Is your problem solved?

**Comment by melanchall** [comment]
Closing due to no response.
