### ISSUE TITLE
Receiving Midi Time Code Events

### ISSUE THREAD

**Issue by seejkee** [melanchall/drywetmidi#115]
Hi,
I'm new to C# and trying to figure out how the Midi Time Code works.
I use `_inputDevice.EventReceived` and `_inputDevice.MidiTimeCodeReceived` EventHandler to receive **Full/Quarter Frame** MTC events.

When I try to use them together, only `_inputDevice.EventReceived` works.
Sorry for the stupid question, but why is `_inputDevice.MidiTimeCodeReceived` not working in this case?
```cs
_inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived; // MTC Quarter Frame Event
_inputDevice.EventReceived += OnEventReceived; // MTC SysEx Full Frame Event
```
> Input device is listening for events. Press any key to exit...
01/03/2021 16:04:12 MTC SysEx Full Frame: [1:53:11:13]
01/03/2021 16:04:12 MTC SysEx Full Frame: [1:2:44:24]

Separately each EventHandler works great
```cs
_inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived; // MTC Quarter Frame Event
//     _inputDevice.EventReceived += OnEventReceived; // MTC SysEx Full Frame Event
```
> Input device is listening for events. Press any key to exit...
01/03/2021 16:11:49 MTC Quarter Frame: [0:29:13:27]
01/03/2021 16:11:49 MTC Quarter Frame: [0:29:13:29]

```cs
//     _inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived; // MTC Quarter Frame Event
_inputDevice.EventReceived += OnEventReceived; // MTC SysEx Full Frame Event
```
> Input device is listening for events. Press any key to exit...
01/03/2021 16:31:14 MTC SysEx Full Frame: [0:17:13:14]
01/03/2021 16:31:14 MTC SysEx Full Frame: [1:18:44:21]

```cs
using System;
using Melanchall.DryWetMidi.Devices;
using Melanchall.DryWetMidi.Core;
namespace TimeCodeGen
{
    class Program
    {
        private static InputDevice _inputDevice;
        static void Main(string[] args)
        {
            _inputDevice = InputDevice.GetByName("testport");
            _inputDevice.RaiseMidiTimeCodeReceived = true;
            _inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived; // MTC Quarter Frame Event
            _inputDevice.EventReceived += OnEventReceived; // MTC SysEx Full Frame Event
            _inputDevice.StartEventsListening();
            Console.WriteLine("Input device is listening for events. Press any key to exit...");
            Console.ReadKey();
            if (_inputDevice != null) { }
            _inputDevice.Dispose();
        }
        // MTC SysEx Full Frame Event
        private static void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
        {
            int ffHours, ffMinutes, ffSeconds, ffFrames;
            var sysEvent = e.Event as NormalSysExEvent;
            byte[] sysData = sysEvent.Data;
            ffHours = sysData[4] - 96;
            ffMinutes = sysData[5];
            ffSeconds = sysData[6];
            ffFrames = sysData[7];
            Console.WriteLine(DateTime.Now + " MTC SysEx Full Frame: [" + ffHours + ":" + ffMinutes + ":" + ffSeconds + ":" + ffFrames + "]");
        }
        // MTC Quarter Frame Event
        private static void OnMidiTimeCodeReceived(object sender, MidiTimeCodeReceivedEventArgs tc)
        {
            Console.WriteLine(DateTime.Now + " MTC Quarter Frame: [" + tc.Hours + ":" + tc.Minutes + ":" + tc.Seconds + ":" + tc.Frames + "]");
        }
    }
}
```

**Comment by melanchall** [comment]
Hi,

Are you sure your device **always** send both MTC and SysEx events? Please show me what events arriving without additional processing (please comment `_inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived;`):

```csharp
private static void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
{
    Console.WriteLine(e.Event);
}
```

Capture as many events as you can to see that both MTC and SysEx (which are events of different types) are sent by the device.

**Comment by seejkee** [comment]
Yes, I generate both events via **Vegas 14 Pro Edit** (full-frame messages called for cursors position changes), **MIDI OX** shows the received both events correctly. 
I uploaded logs to my github:
https://github.com/seejkee/MidiTimeCodeEvents/

_just modified a bit for readability_
`Console.WriteLine(DateTime.Now + " sysex event: " + e.Event);`

**Comment by melanchall** [comment]
Thanks, but we need to capture events again. Please modify your `WriteLine` to this:

```csharp
Console.WriteLine($"[{DateTime.Now}] {e.Event}");
```

Because those events are not sysex ones. Also I see in your log lines like this:

```
01/03/2021 22:53:19 MTC Quarter Frame: [2:31:56:22]
```

So you didn't comment `_inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived;`. Please comment it. We need to see raw MIDI events.

**Comment by seejkee** [comment]
> So you didn't comment `_inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived;`. Please comment it. We need to see raw MIDI events.
I'm sorry that, I fixed it now
https://raw.githubusercontent.com/seejkee/MidiTimeCodeEvents/main/console_Out_events.txt

**Comment by melanchall** [comment]
I'm sure that shown events are not the same as you got when you opened the issue. In your code you have the line:

```csharp
var sysEvent = e.Event as NormalSysExEvent;
```

But in your log there are a lot of events that are not `NormalSysExEvent` so your program will crash on `sysEvent.Data`. Use this code:

```csharp
// MTC SysEx Full Frame Event
private static void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
{
    int ffHours, ffMinutes, ffSeconds, ffFrames;
    var sysEvent = e.Event as NormalSysExEvent;
    if (sysEvent == null)
        return;

    byte[] sysData = sysEvent.Data;
    ffHours = sysData[4] - 96;
    ffMinutes = sysData[5];
    ffSeconds = sysData[6];
    ffFrames = sysData[7];
    Console.WriteLine(DateTime.Now + " MTC SysEx Full Frame: [" + ffHours + ":" + ffMinutes + ":" + ffSeconds + ":" + ffFrames + "]");
}
// MTC Quarter Frame Event
private static void OnMidiTimeCodeReceived(object sender, MidiTimeCodeReceivedEventArgs tc)
{
    Console.WriteLine(DateTime.Now + " MTC Quarter Frame: [" + tc.Hours + ":" + tc.Minutes + ":" + tc.Seconds + ":" + tc.Frames + "]");
}
```

So please uncomment

```csharp
_inputDevice.MidiTimeCodeReceived += OnMidiTimeCodeReceived; // MTC Quarter Frame Event
_inputDevice.EventReceived += OnEventReceived; // MTC SysEx Full Frame Event
```

and check again.

**Comment by seejkee** [comment]
```cs
    if (sysEvent == null)
        return;
```
@melanchall Thank you very much! It's worked :)
