### ISSUE TITLE
Feature Request: Strong Name the assembly

### ISSUE THREAD

**Issue by MoogleTroupe** [melanchall/drywetmidi#118]
Please strong name the nuget package. It is recommended to do so on open source libraries, and to check in the signing key to the git repo. 

https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named

It doesn't affect projects that are not strong named, but projects that are cannot use this library from nuget.

**Comment by melanchall** [comment]
PR merged. Thank you!

**Comment by melanchall** [comment]
:rocket: **5.2.1 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!
