### ISSUE TITLE
Melanchall.DryWetMidi.dll is built in debug mode

### ISSUE THREAD

**Issue by ragrr4** [melanchall/drywetmidi#12]
During the Windows App Certification Kit the test failed in the Debug configuration test section

FAILED
    Debug configuration

    Error Found: The debug configuration test detected the following errors:
        El archivo binario Melanchall.DryWetMidi.dll se crea en modo de depuración.
        which translates...
        The binary file Melanchall.DryWetMidi.dll is built in debug mode
    Impact if not fixed: Microsoft Store doesn’t allow a debug version of an app.
    How to fix: Please make sure the app isn’t linking to any debug versions of a framework and it is built with release configuration with optimization enabled. If this is a managed app please make sure you have installed the correct version of .NET framework. 

Thanks in advance

**Comment by ragrr4** [comment]
Hi,

It's from the NuGet Package on it's latest version

**Comment by melanchall** [comment]
Ohh, sorry for that. I'll replace the package and let you know.

**Comment by melanchall** [comment]
I've replaced the package. Please reinstall the library.
