### ISSUE TITLE
Intermittent "Undefined external error" takes down app when debugging

### ISSUE THREAD

**Issue by jskeet** [melanchall/drywetmidi#121]
I've just started using the library, and love it... but I've got a problem that I don't yet understand.

I've only seen it when using a "Fore" MIDI to USB cable (the actual MIDI device it's talking to doesn't seem to matter) but it seems that if it's going to happen, it happens the first time I try to play a file on any device. If it works once, it keeps working until the process is finished.
When it _does_ fail, which has always been while debugging, so far, it takes down the process.

This is the exception:

```text
Melanchall.DryWetMidi.Devices.MidiDeviceException
  HResult=0x80131500
  Message=Undefined external error.
  Source=Melanchall.DryWetMidi
  StackTrace:
   at Melanchall.DryWetMidi.Devices.MidiDevice.ProcessMmResult(UInt32 mmResult)
   at Melanchall.DryWetMidi.Devices.OutputDevice.SendShortEvent(MidiEvent midiEvent)
   at Melanchall.DryWetMidi.Devices.OutputDevice.SendEvent(MidiEvent midiEvent)
   at Melanchall.DryWetMidi.Devices.Playback.OnClockTicked(Object sender, EventArgs e)
   at Melanchall.DryWetMidi.Devices.MidiClock.OnTicked()
   at Melanchall.DryWetMidi.Devices.MidiClock.Tick()
   at Melanchall.DryWetMidi.Devices.MidiClock.OnTickGenerated(Object sender, EventArgs e)
   at Melanchall.DryWetMidi.Devices.TickGenerator.GenerateTick()
   at Melanchall.DryWetMidi.Devices.HighPrecisionTickGenerator.OnTick(UInt32 uID, UInt32 uMsg, UInt32 dwUser, UInt32 dw1, UInt32 dw2)
```

The code is reasonably simple - it's in a WPF app:

```csharp
var devices = OutputDevice.GetAll().ToList();
var outputDevice = devices.First(d => d.Name == "USB Midi ");
MidiFile file = MidiFile.Read(midiFileName);
var playback = file.GetPlayback(outputDevice);
var duration = playback.GetDuration<MetricTimeSpan>();
playback.InterruptNotesOnStop = true;
playback.Start();
```

The exception looks like it's in a library-specific thread. Any thoughts around how I can diagnose this any further? Should I be looking for updated drivers?

**Comment by jskeet** [comment]
(I'm aware of `OutputDevice.GetByName`, but in the real code I'm also logging all the actual devices, hence this approach. I'd be surprised if that caused an issue.)

**Comment by jskeet** [comment]
Note on frequency of error: yesterday it seemed to be happening about 50% of the time. Today it's more like 10%-20%. It's *possible* that adding `outputDevice.PrepareForEventsSending()` helps, but I don't have enough evidence to say for sure yet.

**Comment by jskeet** [comment]
Ha... and the next time I test it, I see that no, `PrepareForEventsSending` doesn't prevent this. But the exception isn't thrown until I start actually playing back the file.

**Comment by melanchall** [comment]
Hi @jskeet,

Thanks for using the library!

From the call stack you've provided there are two possible places where error occured:

* Windows MIDI driver (or driver of your hardware)
* your MIDI hardware

`SendShortEvent` just calls Windows API method [`midiOutShortMsg`](https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-midioutshortmsg). `ProcessMmResult` method of DWM just handles return value of `midiOutShortMsg` and if it represents error, calls [`midiOutGetErrorText`](https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-midioutgeterrortext) to get text of the error.

So `Undefined external error.` is an error from `midiOutShortMsg`.

Looking on the web I see many threads around this problem. Some examples:

* https://www.elektronauts.com/t/windows-midi-bug-undefined-external-error-renamed-and-solved/44181
* https://answers.microsoft.com/en-us/windows/forum/windows_7-hardware/unidentified-external-error-when-opening-any-usb/38022945-fab6-469e-82d8-6c5bf1372105
* https://windowsforum.com/threads/midi-controller-undefined-external-error.49537/

So the problem is not related with DWM. Can you please look in debug, what kind of MIDI event leads to the exception? Or the type of an event doesn't matter? Can you open any DAW (Cubase, Studio One, Reason and so on), create MIDI track and play it via your device? Will the exception occur?

**Comment by jskeet** [comment]
Can you please look in debug, what kind of MIDI event leads to the exception?

It's a program change event on channel 11, changing to program number 9. This is the first event sent to the device. (The first several events in the file are all program change for channel 11. I suspect this may have a specific meaning for the intended device.) Interestingly, I've managed to reproduce it - just once - with the cable not actually plugged into a "real" device. Unfortunately the device that has been able to reproduce it most often is a church electronic pipe organ, which obviously isn't in my normal development environment...

> So the problem is not related with DWM.

I'm sure it's not *caused* by DWM, but I'd argue that the high precision tick generator should probably be more robust against such exceptions. It looks like OnTick is executed as a callback from `MidiTimerWinApi.timeSetEvent`, which I *suspect* means it'll kill the multimedia timer thread... it would really be nice if that didn't happen :)

> Can you open any DAW (Cubase, Studio One, Reason and so on), create MIDI track and play it via your device? 

I don't have a DAW installed at the moment, but will give it a go when I have time. If I could reproduce this issue more reliably, that would definitely help. I'm going to try to reproduce it in a minimal example - I'll see if a console app works. I also have another USB to MIDI cable on its way... it's entirely possible that that will use the same chipset and driver, but we'll see.

**Comment by jskeet** [comment]
Okay, I've now managed to reproduce it *reasonably* reliably (see below), and with very brief code:

```csharp
using Melanchall.DryWetMidi.Common;
using Melanchall.DryWetMidi.Core;
using Melanchall.DryWetMidi.Devices;

class Program
{
    static void Main()
    {
        string name = "USB Midi ";
        using (var device = OutputDevice.GetByName(name))
        {
            device.PrepareForEventsSending();
            var evt = new ProgramChangeEvent(new SevenBitNumber(9)) { Channel = new FourBitNumber(11) };
            device.SendEvent(evt);
        }
    }
}
```

The key to making this fail is to wait a while between runs. Basically, you can run the code above and it's fine... wait a minute, run it again, and it fails. Run it immediately afterwards, and it's fine. It *feels* like the driver effectively "goes to sleep" and fails the first event sent after that. 

Putting the code in a loop with sleeps in (but sending bursts of 5 events), it looks like this "idle timeout" is inconsistent. I've seen it fail after sleeping for as little as 34 seconds, and succeed after sleeping for as long as 54 seconds. Sleeping for longer seems to *always* reproduce the issue.

Do you have any suggestions as to a "no-op" MIDI event I could send before trying to actually play a file? That would at least work around the issue - although I'm really hoping that I can find a USB MIDI device that doesn't have this problem.

I suspect most of this information isn't relevant to DWM specifically, but may help others with the same cable/driver. However, I do still think it would be a good idea to avoid taking down the multimedia event thread on failure.

**Comment by melanchall** [comment]
Thanks for such extensive investigation!

> It's a program change event on channel 11, changing to program number 9.

What if you use another MIDI events? For example, what if you send bunch of `NoteOffEvent` instances?

> However, I do still think it would be a good idea to avoid taking down the multimedia event thread on failure.

In fact, multimedia thread will not fail, it's a system thread persisted in Windows. But a program thread will fail and yes, it's not OK. It can be easily fixed from my side by handling an error: swallow it and raise an event like `OutputDeviceErrorOccurred`. Maybe it should be configurable by providing property like `FailOnOutputDeviceError` within `Playback` class which will be set to `false` by default. What do you think about this feature?

> Do you have any suggestions as to a "no-op" MIDI event I could send before trying to actually play a file?

Unfortunately no :(

**Comment by jskeet** [comment]
> What if you use another MIDI events? For example, what if you send bunch of NoteOffEvent instances?

- NoteOffEvent: fails
- NoteOnEvent: fails
- ChannelAftertouchEvent: fails
- PitchBendEvent: fails
- NormalSysExEvent: doesn't fail, but doesn't stop other events failing afterwards (doesn't "wake up" whatever has gone to sleep)

Given that I need to wait a minute between each test, I don't think it's worth testing that further ;)

>  It can be easily fixed from my side by handling an error: swallow it and raise an event like OutputDeviceErrorOccurred. Maybe it should be configurable by providing property like FailOnOutputDeviceError within Playback class which will be set to false by default. What do you think about this feature?

Yes, that sounds great to me. Thanks!

> > Do you have any suggestions as to a "no-op" MIDI event I could send before trying to actually play a file?

> Unfortunately no :(

Not to worry. In my specific use case I think a NoteOff event would be absolutely fine: I'm just playing MIDI files, so if there *are* any notes on beforehand, I'd want them to stop anyway :)

**Comment by melanchall** [comment]
Well, I'll add discussed API, build prerelease package and let you know.

Thanks for the issue!

**Comment by jskeet** [comment]
Thanks! And please don't feel any urgency on my part. I know it's a slightly odd situation that's caused by a dodgy driver :)

**Comment by melanchall** [comment]
Hi @jskeet,

I've added `DeviceErrorOccurred` event to the `Playback` class. I decided not to add property-switcher of the behavior, so exceptions in `IOutputDevice.SendEvent` will always be swallowed and will cause the new event fired.

You can install [5.2.1-prerelease6](https://www.nuget.org/packages/Melanchall.DryWetMidi/5.2.1-prerelease6) package from NuGet to try new API.

**Comment by jskeet** [comment]
Great - thanks so much. I'll try it over the weekend!

**Comment by jskeet** [comment]
FYI: I've just received my new USB MIDI cable (different manufacturer), and that appears to have the same problem. Interesting.

**Comment by melanchall** [comment]
I've tested the library on USB-MIDI adapter some time ago and all was working fine.

Looks like Windows MIDI driver problem...

**Comment by jskeet** [comment]
Hmm. I wouldn't be surprised if different cables used different adapters.

I'm currently struggling with my workaround - the "send one event, and that wakes it up" doesn't seem to be working in my WPF app... so even with the prerelease6 package, we don't get an exception (and the event is fired) but it doesn't go from "broken" to "working" either. Will investigate more over the weekend.

**Comment by jskeet** [comment]
This doesn't affect the library, but is for the sake of anyone coming to this issue later on...

> I'm currently struggling with my workaround - the "send one event, and that wakes it up" doesn't seem to be working in my WPF app

I worked out what I was doing differently: sending the failed event doesn't fix *that* `OutputDevice` instance; it wakes up the driver so that the *next* `OutputDevice` you create for that device will work. It *looks* like the device then continues to work even after a long delay, so this is basically a one-off retry each time you try to create an output device.

**Comment by melanchall** [comment]
So your workaround is something like that:

```csharp
var outputDevice = OutputDevice.GetByName("Device");

try
{
    outputDevice.SendEvent(new NoteOffEvent());
}
catch {}
finally
{
    outputDevice.Dispose();
}

outputDevice = OutputDevice.GetByName("Device");
```

?

**Comment by jskeet** [comment]
Pretty much, yes :)

**Comment by melanchall** [comment]
Interesting :-) Thank you for providing a workaround for the problem!

Whar about the issue? Can it be closed or you plan to continue investigation?

**Comment by jskeet** [comment]
Happy to close it - thanks for all your work :)

**Comment by melanchall** [comment]
:rocket: **5.2.1 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!

**Comment by jskeet** [comment]
Excellent, will do - thanks again!
