### ISSUE TITLE
How do I identify which track a MidiEvent belongs to when a Playback is in progress?

### ISSUE THREAD

**Issue by akira0245** [melanchall/drywetmidi#122]
Hi, I'm using a custom IOutputDevice to play a PlayBack, I want this device process NoteEvent differently between different Tracks. but a NoteEvent doesn't have a track property. How should I solve this?
Thank you.

**Comment by melanchall** [comment]
Hi,

Hmm, it's not possible right now. I'll think how to provide such info during playback and come back to you.

Thanks!

**Comment by melanchall** [comment]
@akira0245 Can you please say what kind of logic do you want to implement? Something like "if the number of track chunk is N, skip an event"?

**Comment by akira0245** [comment]
> @akira0245 Can you please say what kind of logic do you want to implement? Something like "if the number of track chunk is N, skip an event"?

If a NoteEvent has a Track property, my Device should look like this. This Device is very basic and now only handles NoteOn and NoteOff. I just need to do an action before the NoteOn of a different Track is played. Thank you!
```
class BardPlayDevice : IOutputDevice
	{
		public void PrepareForEventsSending()
		{

		}

		public void SendEvent(MidiEvent midiEvent)
		{
			var keyboard = Plugin.pluginInterface.Framework.Gui.GetAddonByName("PerformanceModeWide", 1);
			if (keyboard == null) return;

			if (midiEvent is NoteOnEvent noteOnEvent)
			{
				if (Plugin.PlayingGuitar && Plugin.config.OverrideGuitarTones)
				{
					var tone = Plugin.config.TracksTone[midiEvent.Track];
					playlib.GuitarSwitchTone(PerformanceToneChange.Address, tone);

				}

				var noteNum = noteOnEvent.NoteNumber - 48 + Plugin.config.NoteNumberOffset;
				if (noteNum < 0 || noteNum > 36) return;
				playlib.PressKey(keyboard.Address, noteNum);
			}
			else if (midiEvent is NoteOffEvent noteOffEvent)
			{
				var noteNum = noteOffEvent.NoteNumber - 48 + Plugin.config.NoteNumberOffset;

				if (noteNum < 0 || noteNum > 36) return;
				playlib.ReleaseKey(keyboard.Address, noteNum);
			}
		}

		public event EventHandler<MidiEventSentEventArgs> EventSent;
	}
```

**Comment by akira0245** [comment]
> @akira0245 Can you please say what kind of logic do you want to implement? Something like "if the number of track chunk is N, skip an event"?

Yes, it would also be handy to be able to skip events so that I don't have to regenerate a PlayBack when I enable or disable a track.

**Comment by melanchall** [comment]
Thanks for clarification. I'll think about how to design the new API. I suppose signature of the `SendEvent` will be changed to provide an event metadata.

**Comment by melanchall** [comment]
It seems it's quite complicated. There is a big pitfall with assigning track chunk number to event sent to a device by playback. Some events can be not presented in any track chunk and can be generated by playback on the fly. Cases where this occurs:

1. You set new time (with `MoveToTime` method, for example) and new time falls in middle of some note. If `TrackNotes` property set to `true`, new `NoteOnEvent` will be generated, but it doesn't actually exist in a track chunk.
2. The same problem with `TrackProgram`, `TrackPitchValue` and `TrackControlValue` properties.

We also can't add property like `TrackChunkIndex` to `MidiEvent` because there are a lot of situations where this property is not relevant.

I have one idea, need to check it. But anyway your task will require some additional code from you, since we can't support track chunk index in MIDI events directly due to reasons mentioned above.

**Comment by akira0245** [comment]
Thanks for your work! For my purposes, any extra code is fine as long as there is a way to get enough midievent metadata. I approve it's a good idea to pass these information through the SendEvent signature.

**Comment by melanchall** [comment]
@akira0245 solution is ready, I'll provide it tomorrow.

**Comment by melanchall** [comment]
Well, the changes I've made:

* removed `sealed` modifier from `TimedEvent`, `Note` and `Chord` so you can subclass from them;
* removed `sealed` modifier from `Playback` and added `TryPlayEvent` virtual method to the class which by default sends event to a device;
* added `IMetadata` interface which is respected by `Playback` if implemented by input timed objects.

For your task you need:

1. create your own implementation of `TimedEvent` implementing `IMetadata`:

    ```csharp
    private sealed class TimedEventWithTrackChunkIndex : TimedEvent, IMetadata
    {
        public TimedEventWithTrackChunkIndex(MidiEvent midiEvent, long time, int trackChunkIndex)
            : base(midiEvent, time)
        {
            Metadata = trackChunkIndex;
        }

        public object Metadata { get; set; }
    }
    ```

    so `Metadata` property will hold the index of a track chunk.

2. create your own implementation of `Playback`:

    ```csharp
    private sealed class MyPlayback : Playback
    {
        public MyPlayback(IEnumerable<ITimedObject> timedObjects, TempoMap tempoMap)
            : base(timedObjects, tempoMap)
        {
        }

        protected override bool TryPlayEvent(MidiEvent midiEvent, object metadata)
        {
            // Place your logic here
            // Return true if event played (sent to plug-in); false otherwise
        }
    }
    ```

    so in fact you even don't need a custom output device. But if you want, you can do something like that:

    ```csharp
    private sealed class MyOutputDevice : IOutputDevice
    {
        public event EventHandler<MidiEventSentEventArgs> EventSent;

        public void PrepareForEventsSending()
        {
        }

        public void SendEvent(MidiEvent midiEvent)
        {
        }

        public bool SendEventWithMetadata(MidiEvent midiEvent, object metadata)
        {
            // Place your logic here
            // Return true if event sent to plug-in; false otherwise
        }
    }
    ```

    and in `TryPlayEvent` of `Playback`:

    ```csharp
    protected override bool TryPlayEvent(MidiEvent midiEvent, object metadata)
    {
        return ((MyOutputDevice)OutputDevice).SendEventWithMetadata(midiEvent, metadata);
    }
    ```

3. create playback from instances of `TimedEventWithTrackChunkIndex`:

    ```csharp
    var timedEvents = midiFile
        .GetTrackChunks()
        .SelectMany((c, i) => c.GetTimedEvents().Select(e => new TimedEventWithTrackChunkIndex(e.Event, e.Time, i)))
        .OrderBy(e => e.Time);

    var tempoMap = midiFile.GetTempoMap();

    var playback = new MyPlayback(timedEvents, tempoMap);
    ```

Modify constructor of `MyPlayback` if you want to pass output device. But as I said before, it seems you don't need custom output device.

And... that's all. No breaking changes in API and your task solved :)

**Comment by akira0245** [comment]
@melanchall Thank you for the quick update and also for writing such detailed instructions, it solved my problem perfectly. I really appreciate dryWetMidi and your work, thank you again!

**Comment by melanchall** [comment]
:rocket: **5.2.1 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!
