### ISSUE TITLE
midiFile.GetPlayback

### ISSUE THREAD

**Issue by wolfy01** [melanchall/drywetmidi#129]
When loading in huge midi's, it works. But when you call `midiFile.GetPlayback(outputDevice);` everything freezes for awhile, sometimes this can be a _long_ time

**Comment by melanchall** [comment]
`Playback` creation requires pretty much work to provide all the features like using event/note callback, data tracking, metadata routing and so on. I have an idea to provide options to turn off some features on playback instantiating if user don't need them. But that's just an idea right now.

Can you please give me a MIDI file you have troubles with? So I'll analyze what's going on and give you more detailed feedback.

**Comment by wolfy01** [comment]
> `Playback` creation requires pretty much work to provide all the features like using event/note callback, data tracking, metadata routing and so on. I have an idea to provide options to turn off some features on playback instantiating if user don't need them. But that's just an idea right now.
> 
> Can you please give me a MIDI file you have troubles with? So I'll analyze what's going on and give you more detailed feedback.

The files that cause it to freeze for a bit are called "Black Midi's". Most are usually a few MB in size and those it doesn't have much problems with, but as soon as you get into the 100MB range or above, it's way more noticeable. Black Midi's have anywhere from 1k, 100k, to 1m+ notes. So I'm assuming that the reason its freezing is because there is so many events it has to handle. I can still provide a MIDI if you'd like

**Comment by melanchall** [comment]
> So I'm assuming that the reason its freezing is because there is so many events it has to handle

Yes, of course.

>  I can still provide a MIDI if you'd like

Yes, please. Maybe I can do creation of `Playback` a bit faster.

**Comment by wolfy01** [comment]
Here's the midi: 

[The Black Bomb U12.zip](https://github.com/melanchall/drywetmidi/files/6664640/The.Black.Bomb.U12.zip)

129 MB When extracted.

**Comment by melanchall** [comment]
Thanks!

I'll profile playback creation and let you know what I've found.

**Comment by wolfy01** [comment]
> Thanks!
> 
> I'll profile playback creation and let you know what I've found.

Okay, thanks!

**Comment by melanchall** [comment]
@wolfy01 Can you please give a smaller file, maybe 10MB or something like that? It seems it's too long to create playback from the provided file on my system :(

**Comment by wolfy01** [comment]
Sure! Here's the same MIDI, but with a lot less notes and a smaller file size.

[The Black Bomb U12 [A little Deblacked].zip](https://github.com/melanchall/drywetmidi/files/6665630/The.Black.Bomb.U12.A.little.Deblacked.zip)
8.14 MB

**Comment by melanchall** [comment]
Thanks for the file!

Problem was with a lot of tempo changes within the file. So conversion of events times to microseconds was really long. I've made some changes and now that conversion is much faster. And thus playback creation much much faster too.

I've published [5.2.1-prerelease9](https://www.nuget.org/packages/Melanchall.DryWetMidi/5.2.1-prerelease9) version of the library, please install it via NuGet and let me know if the problem solved or not.

**Comment by wolfy01** [comment]
> Thanks for the file!
> 
> Problem was with a lot of tempo changes within the file. So conversion of events times to microseconds was really long. I've made some changes and now that conversion is much faster. And thus playback creation much much faster too.
> 
> I've published [5.2.1-prerelease9](https://www.nuget.org/packages/Melanchall.DryWetMidi/5.2.1-prerelease9) version of the library, please install it via NuGet and let me know if the problem solved or not.

Major improvement. Nice!

**Comment by melanchall** [comment]
Thankyou for the issue! Can it be closed?

**Comment by wolfy01** [comment]
> Thank you for the issue! Can it be closed?

It still takes awhile from more testing, but it is faster. 

> I have an idea to provide options to turn off some features on playback instantiating if user don't need them.

Are you planning on doing that somewhere in the future? It would probably help a lot with this too.

**Comment by melanchall** [comment]
> Are you planning on doing that somewhere in the future? It would probably help a lot with this too.

Yes, I'll come back to the subject in the future, but right now I see that playback creation is many times faster than before you opened this issue :)

> Edit: Also the main issue for me now is mostly just loading the file 🤣

If you about `MidiFile.Read`, then I think I can't do better right now because reading a MIDI file is already optimized in many ways. But even your 129 MB file takes just several seconds to parse it into `MidiFile` on my machine, so I think it's very good for such a big file.

**Comment by wolfy01** [comment]
> > Are you planning on doing that somewhere in the future? It would probably help a lot with this too.
> 
> Yes, I'll come back to the subject in the future, but right now I see that playback creation is many times faster than before you opened this issue :)
> 
> > Edit: Also the main issue for me now is mostly just loading the file 🤣
> 
> If you about `MidiFile.Read`, then I think I can't do better right now because reading a MIDI file is already optimized in many ways. But even your 129 MB file takes just several seconds to parse it into `MidiFile` on my machine, so I think it's very good for such a big file.

Yeah, also I ended up using a `Thread` to do it, which did actually make it a bit faster. Also, thank you for this amazing project 👍

**Comment by melanchall** [comment]
:rocket: **5.2.1 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!
