### ISSUE TITLE
suggestion: ProgramChange event in PatternBuilder

### ISSUE THREAD

**Issue by tamitam** [melanchall/drywetmidi#13]
I use dryWetMidi to develope a site for building playbacks.
I need every track to be in different instrument, and I build the tracks using PatternBuilder.
If it is possible to add a ProgramChange function to PatternBuilder - I think it will be usefull not just for me...

**Comment by melanchall** [comment]
Hi,

`PatternBuilder` has `SetProgram` method which I suppose is what you need. Please update the library (latest version is **3.0.0**).

**Comment by melanchall** [comment]
@tamitam Is your provlem solved?

**Comment by tamitam** [comment]
Yes!!!!!!!!!! Thank you!
