### ISSUE TITLE
Play the notes in a 3D keyboard

### ISSUE THREAD

**Issue by Maddy1107** [melanchall/drywetmidi#133]
Hello,

I am working on a project where I have a 3D keyboard in Unity.

I have extracted the notes, octaves and time. Now I want to play that notes on the keyboard automatically.

Any Idea how to do the with the perfect timing that is extracted?

This might be a silly question to ask but I have no idea how to do it.

I can use the notes to play on the keyboard but how to use the time.

Thank you.

**Comment by melanchall** [comment]
Hi,

Can you please provide more details about what you want to do? Right now it's not clear. Do you want to start playback of collection of notes?

**Comment by melanchall** [comment]
I'm going to close the issue if no details will be provided.

**Comment by melanchall** [comment]
I'm closing the issue. Please reopen it if you have info I've asked for.
