### ISSUE TITLE
Update wiki to verison 3.0.0

### ISSUE THREAD

**Issue by tamitam** [melanchall/drywetmidi#14]
I see that in verison 3.0.0 there's a lot of changes.
Are you going to update Wiki or should I try learn it by myself?

**Comment by melanchall** [comment]
Yes, I'm going to do that :) Some changes in 3.0.0 already described in Wiki, but some not. Thanks for pointing out.

**Comment by tamitam** [comment]
Thank you,
When will it be done?

**Comment by melanchall** [comment]
I'm planning to release new version at mid of July, so I'll update Wiki by this time. At now you can take a look at [release notes](https://github.com/melanchall/drywetmidi/releases/tag/v3.0.0) for 3.0.0 to see what was changed.

Full changelog available on [Releases](https://github.com/melanchall/drywetmidi/releases) page.

**Comment by melanchall** [comment]
The library updated to [3.1.0](https://github.com/melanchall/drywetmidi/releases/tag/v3.1.0) along with Wiki.
