### ISSUE TITLE
Note.Time property returns tick instead of time

### ISSUE THREAD

**Issue by X1nto** [melanchall/drywetmidi#143]
```cs
var midiFile = MidiFile.Read("Raw/MIDI/music.mid");
var tempoMap = midiFile.GetTempoMap();
var notes = midiFile.GetNotes();
    
_detector = new Detector(notes
    .Select(note => new Beat
    {
        Millis = note.Time,
    })
);
```
Beat.cs: 
```cs
public struct Beat
{
    public long Millis;

    public override string ToString()
    {
        return $"Millis: {Millis}";
    }
}
```
`Millis = note.Time` is set to the tick of note, instead of the millisecond, it plays on.
I also tried with `Millis = note.TimeAs<MetricTimeSpan>(tempoMap).Milliseconds` but still no luck there.

Library version: 6.0.1, installed with NuGet, net framework 4.7.2

**Comment by melanchall** [comment]
First of all, it's absolutely correct that `Note.Time` returns ticks. [Documentation](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Interaction.Note.html#Melanchall_DryWetMidi_Interaction_Note_Time) says about t:

> Gets or sets absolute time of the note in **units defined by the time division of a MIDI file**.

_units defined by the time division of a MIDI file_ = _ticks_

So yes, you need to use [`MetricTimeSpan`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Interaction.MetricTimeSpan.html). But you use wrong property. `Milliseconds` property, according to [documentation](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Interaction.MetricTimeSpan.html#Melanchall_DryWetMidi_Interaction_MetricTimeSpan_Milliseconds):

> Gets the **milliseconds component** of the time represented by the current MetricTimeSpan.

So `Milliseconds` just returns milliseconds part of a time. For example, for `00:01:02.345` the property will return `345`. But you need to get **entire time** as milliseconds number. You can do it like this:

```csharp
Millis = note.TimeAs<MetricTimeSpan>(tempoMap).TotalMicroseconds / 1000
```

**Comment by X1nto** [comment]
I see, my bad. Thanks for responding!

Tested your solution, works fine, but I think it would be great to add a property called TotalMilliseconds which essentially returns the same. I'll try and PR the feature.
