### ISSUE TITLE
Hide unmanaged dlls

### ISSUE THREAD

**Issue by josago97** [melanchall/drywetmidi#158]
Hello, 

I would like to know if there is any way to hide the dlls of the library so that they do not appear in the root folder of the project in the  solution explorer.

Thanks.

![image](https://user-images.githubusercontent.com/26380095/150623583-65b28c2a-76de-4799-b6d0-143f87779566.png)

**Comment by melanchall** [comment]
Hello,

Are these files are present in your project's folder physically? Or they just appeared in VS Solution Explorer and makes noise there?

These files shouldn't be a part of a project. They are only for copying into the project's bin folder. I suppose that is how VS works and nothing we can do with it. But you can search information on the web on the issue.

**Comment by josago97** [comment]
The files are not physically present in the project, they simply appear in the solution explorer. Also, they are not even present in the project file.

![image](https://user-images.githubusercontent.com/26380095/150651666-d7f20d51-33c2-4c99-a081-91a3667bbd1e.png)

**Comment by melanchall** [comment]
Well, in this case I think it's how VS works. I'm not sure I can do something from my side. I'll look closely on the issue tomorrow.

**Comment by josago97** [comment]
Well thank you very much. In case it's any help, the dlls appear when I build the project. I use Visual Studio Community 2022 17.0.5.

**Comment by melanchall** [comment]
Finally I've found it's my fault. I've fixed the issue. Fix will be availabale in the next release of the library. But you can install [6.1.0-prerelease2](https://www.nuget.org/packages/Melanchall.DryWetMidi/6.1.0-prerelease2) version of the library via NuGet right now to get rid of the files.

Thank you for the issue! I've learned something new :) Please let me know if the problem gone or not.

**Comment by josago97** [comment]
The dlls are no longer visible and everything works, thank you very much.

**Comment by melanchall** [comment]
:rocket: **6.1.0 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!
