### ISSUE TITLE
Bars and Beats gone or renamed?

### ISSUE THREAD

**Issue by manchuwook** [melanchall/drywetmidi#16]
Originally I was using this code
```
((NotesCollection)noteMan.Notes).ToList()
   .GroupBy(gb => new {
    Bar = gb.TimeAs<MusicalTimeSpan>(tempoMap).Bars,
    Beat = gb.TimeAs<MusicalTimeSpan>(tempoMap).Beats + 1
})
```
But now it seems they are red after the update.  Is there a way I can get those back?

**Comment by manchuwook** [comment]
Scratch that, it got moved - apologies from me.

**Comment by melanchall** [comment]
Hi!

Sorry for delay. Glad to know you've solved your problem. But I'd like to notice that `MusicalTimeSpan` doesn't have `Bar` and `Beat` properties. I suppose you are talking about `BarBeatTimeSpan` and `Bars` and `Beats` properties.

Also be aware of calling `TimeAs` multiple times on the same instance of `ITimedObject`. Each calling will perform some calculations and thus performance can degenerate. Call `TimeAs` one time and then use properties of returned object.

Thank you for using DryWetMIDI.
