### ISSUE TITLE
Is it Possible to Have Different Instruments Playing Simultaneously?

### ISSUE THREAD

**Issue by wbaldoumas** [melanchall/drywetmidi#163]
I'm using `PatternBuilder` and I'd like to be able to have different instruments playing simultaneously. I've tried something like the following, but only the last instrument set by the `ProgramChange` is what ends up being used for both sets of notes. What would be the correct way of having these flute and guitar lines played simultaneously?

```cs
var patternBuilder = new PatternBuilder();

patternBuilder.Anchor();
patternBuilder.ProgramChange(GeneralMidiProgram.Flute);
patternBuilder.SetNoteLength(MusicalTimeSpan.Eighth.Triplet());
patternBuilder.Note(Note.Get(NoteName.C, Octave.Middle.Number));
patternBuilder.Note(Note.Get(NoteName.C, Octave.Middle.Number + 1));
patternBuilder.Note(Note.Get(NoteName.C, Octave.Middle.Number));

patternBuilder.MoveToFirstAnchor();
patternBuilder.ProgramChange(GeneralMidiProgram.Harpsichord);
patternBuilder.SetNoteLength(MusicalTimeSpan.Sixteenth);
patternBuilder.Note(Note.Get(NoteName.E, Octave.Middle.Number));
patternBuilder.Note(Note.Get(NoteName.G, Octave.Middle.Number));
patternBuilder.Note(Note.Get(NoteName.F, Octave.Middle.Number));
patternBuilder.Note(Note.Get(NoteName.G, Octave.Middle.Number));

var pattern = patternBuilder.Build();
```

**Comment by melanchall** [comment]
Hi,

You may think about single pattern as about single track chunk. Pattern is a sequential set of actions. So if some point of pattern you set new program, this program will be applied to all following actions. You move to start of the pattern and set new program thus overriding previous one.

You can create two patterns, convert them to track chunks using different channels and then combine them to a MIDI file:

```csharp
var tempoMap = TempoMap.Default;

var flutePattern = new PatternBuilder()
    .ProgramChange(GeneralMidiProgram.Flute)
    .SetNoteLength(MusicalTimeSpan.Eighth.Triplet())
    .Note(Note.Get(NoteName.C, Octave.Middle.Number))
    .Note(Note.Get(NoteName.C, Octave.Middle.Number + 1))
    .Note(Note.Get(NoteName.C, Octave.Middle.Number))
    .Build();
var fluteTrackChunk = flutePattern.ToTrackChunk(tempoMap, (FourBitNumber)0);

var harpsichordPattern = new PatternBuilder()
    .ProgramChange(GeneralMidiProgram.Harpsichord)
    .SetNoteLength(MusicalTimeSpan.Sixteenth)
    .Note(Note.Get(NoteName.E, Octave.Middle.Number))
    .Note(Note.Get(NoteName.G, Octave.Middle.Number))
    .Note(Note.Get(NoteName.F, Octave.Middle.Number))
    .Note(Note.Get(NoteName.G, Octave.Middle.Number))
    .Build();
var harpsichordTrackChunk = harpsichordPattern.ToTrackChunk(tempoMap, (FourBitNumber)1);

var midiFile = new MidiFile(
    fluteTrackChunk,
    harpsichordTrackChunk);
```

Also as you can see you don't need to prepend each instruction with `patternBuilder`. All `PatternBuilder`s methods returns the `PatternBuilder` so you can chain your actions.

Is the solution above good fot you? If not, please describe you scenario in more detail.

**Comment by melanchall** [comment]
I've also added layers support to my backlog. But I can't say when the feature will be implemented.

**Comment by wbaldoumas** [comment]
Hey, I gave that a try and it worked great. I knew it was probably something so simple. Thank you for the in-depth response with examples! 😄
