### ISSUE TITLE
Total length of MIDI file

### ISSUE THREAD

**Issue by fwestberg** [melanchall/drywetmidi#17]
Hey @melanchall,

Thanks for providing this library!

How would you go about getting the total length of a MIDI file?
I've looked at the example you've provided in the README, but this gives you the timing of the last note-off event:

`TempoMap tempoMap = midiFile.GetTempoMap();`

`TimeSpan midiFileDuration = midiFile.GetTimedEvents().LastOrDefault(e => e.Event is NoteOffEvent)?.TimeAs<MetricTimeSpan>(tempoMap) ?? new MetricTimeSpan();`

I need the length of the file including any "unused space". 

<img width="946" alt="2bars" src="https://user-images.githubusercontent.com/13394935/49334193-f313da00-f5cf-11e8-8d20-60e418490dab.png">

In the scenario above, what I'm looking for is the value 768 ticks (96 ticks * 8 beats), but if I use the provided code, I get 696 (96 ticks * 7,25 beats (the position of the cursor)).

I've tried to look through the wiki, but I can't seem to figure it out.

**Comment by melanchall** [comment]
Hi @fwestberg,

Thank you for using the library. Can you provide me a file you want to get total length for?

**Comment by fwestberg** [comment]
Of course – here is the file I used in the example above: https://we.tl/t-uNy1UvoSTa

**Comment by melanchall** [comment]
I've examined your file. There are no events in it after time of 696 ticks, so the library gives you the correct result. I thunk the reason you see empty space at the end of file is MIDI editor you use. It expands visual representation of MIDI file to the end of last bar.

So your real task is get the length of a file in terms of bars occupied by MIDI data. You can do it with this code:

```csharp
var tempoMap = midiFile.GetTempoMap();
var barBeatTimeOfLastEvent = midiFile.GetTimedEvents().Last().TimeAs<BarBeatTimeSpan>(tempoMap);

var totalBars = barBeatTimeOfLastEvent.Bars;

// If a bar is partially occupied, we need add it to the total count of bars
if (barBeatTimeOfLastEvent.Beats > 0 || barBeatTimeOfLastEvent.Ticks > 0)
    totalBars = barBeatTimeOfLastEvent.Bars + 1;

// Convert time span corresponding to total count of bars to ticks
var totalBarsInTicks = TimeConverter.ConvertTo<MidiTimeSpan>(new BarBeatTimeSpan(totalBars, 0), tempoMap);
```

With this code you'll get expected 768. Please let me know if your problem solved.

**Comment by fwestberg** [comment]
That makes sense – and the code is exactly what I need. Thank you!

**Comment by melanchall** [comment]
Good news :) Let me know if you have any other questions about the library.

**Comment by rn1d** [comment]
@melanchall, thank you for sharing your library and answering questions.

I'm faced with a similar problem, but I think the solution you propose is not always correct. The basic idea, if I understand correctly, is to look at the last event and assume the next bar is the end. That assumption fails if there is more than one bar of silence after the last event. It makes a difference if you want to loop the original MIDI file.

There is a special event to signal the end of a track - `EndOfTrackEvent`. 

Unfortunately, DryWetMidi doesn't make it available in the parsed `MidiFile` object. It is discarded when parsing MIDI data. https://github.com/melanchall/drywetmidi/blob/develop/DryWetMidi/Core/Chunks/TrackChunk.cs#L134

Ideally, this should be exposed somehow - at least the event should be included in the parsed track Event collection.

**Comment by melanchall** [comment]
@rn1d Thanks for pointing out the problem!

Hmm, I'll think how to handle the situation you've mentioned. I'm on vacation right now. I'll come back to the issue a couple of days later.

**Comment by rn1d** [comment]
This is a corner case, to be sure, and I am not expecting anything, I just wanted to chime in. 
Enjoy your vacation! 🌴

**Comment by melanchall** [comment]
@rn1d I think now that this was a wrong decision to hide EOT event. This violates the principle of the library according to which it should be possible to get raw MIDI data as it present in a file without any transformations.

I suppose I'll expose the event. Thanks for your comment!

**Comment by melanchall** [comment]
I've added `EndOfTrackStoringPolicy` property to the `ReadingSettings` class. So I've decided to leave default behavior as is, **BUT** give ability to change it:

```csharp
var midiFile = MidiFile.Read("file.mid", new ReadingSettings
{
    EndOfTrackStoringPolicy = EndOfTrackStoringPolicy.Store
});
```

With this code `EndOfTrackEvent` will be present in track chunks of the `midiFile` (if the event is present in an input file of course).

Changes are in _develop_ branch. @rn1d I can build prerelease NuGet package, if you need it.

**Comment by rn1d** [comment]
Fantastic, thank you! If it's not too much trouble to build that pre release package, I would use it. If it's too much hassle - no worries, I'll wait for the next release.

**Comment by melanchall** [comment]
@rn1d Version [5.2.1-prerelease8](https://www.nuget.org/packages/Melanchall.DryWetMidi/5.2.1-prerelease8) is published, you can install it via NuGet. Thank you!

**Comment by melanchall** [comment]
:rocket: **5.2.1 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!
