### ISSUE TITLE
NormalSysEx is not sent.

### ISSUE THREAD

**Issue by valimaties** [melanchall/drywetmidi#172]
Hi.
I tried to send some of the SysEx I read from my keyboard back to keyboard, but nothing happens.
I used MidiView to see what is going on and no message is send to my keyboard from PC.
That is strange because the event is raised (OnEventSent), because the Debug.WriteLine() is telling me that the event was sent. 
But nothing happens! What should I do to check?!

**Comment by melanchall** [comment]
Hi,

1. What operating system are you on (Win/Mac)?
2. What the data of a problem sys ex event? Please provide bytes of the event as a text (not as an image).

**Comment by valimaties** [comment]
The OS is Windows 11, and the SysEx I send to my keyboard is an Yamaha SysEx, which have to change the Registration Memory number in the selected registration bank.
The SysEx is 43-73-01-52-25-11-00-02-**00**-00-F7 .
This one stands for the first registration memory in a registration bank.
For the other 9, the bolded byte will change to 01, 02, 03, ...
I send these SysEx-es by converting the string to byte[] using the below function and send it to OutputDevice as
```cs
new NormalSysExEvent(String_To_Bytes2(mySysExString.Replace("-","")))
```
Conversion from string to byte[] function
```cs
private byte[] String_To_Bytes2(string strInput)
{
    int numBytes = (strInput.Length) / 2;
    byte[] bytes = new byte[numBytes];

    for (int x = 0; x < numBytes; ++x)
    {
        bytes[x] = Convert.ToByte(strInput.Substring(x * 2, 2), 16);
    }
    return bytes;
}
```

**Comment by melanchall** [comment]
Well, I've created a simple test program:

```csharp
using Melanchall.DryWetMidi.Core;
using Melanchall.DryWetMidi.Multimedia;

var inputDevice = InputDevice.GetByName("MIDI A");
inputDevice.EventReceived += OnEventReceived;
inputDevice.StartEventsListening();

var outputDevice = OutputDevice.GetByName("MIDI A");
var mySysExString = "43-73-01-52-25-11-00-02-00-00-F7";

Console.WriteLine($"Sending:  {mySysExString}");
outputDevice.SendEvent(new NormalSysExEvent(String_To_Bytes2(mySysExString.Replace("-", ""))));

void OnEventReceived(object? sender, MidiEventReceivedEventArgs e)
{
    var sysExEvent = (NormalSysExEvent)e.Event;
    Console.WriteLine($"Received: {string.Join("-", sysExEvent.Data.Select(b => Convert.ToString(b, 16).PadLeft(2, '0')))}");
}

byte[] String_To_Bytes2(string strInput)
{
    int numBytes = (strInput.Length) / 2;
    byte[] bytes = new byte[numBytes];

    for (int x = 0; x < numBytes; ++x)
    {
        bytes[x] = Convert.ToByte(strInput.Substring(x * 2, 2), 16);
    }
    return bytes;
}

Console.ReadKey();

inputDevice.Dispose();
outputDevice.Dispose();
```

`"MIDI A"` is a virtual loopback device so if we send an event to it, we immediately receive it from the device. If we run the program, we'll see following output:

```
Sending:  43-73-01-52-25-11-00-02-00-00-F7
Received: 43-73-01-52-25-11-00-02-00-00-f7
```

So as you can see there is nothing wrong with how DryWetMIDI sends and receives a sys ex event. We got exactly the same event as we sent. More than that, you wrote:

> event is raised (OnEventSent)

For Windows `EventSent` will be fired for sys ex **only** if it was successfully processed by Windows MIDI system.

So the first thing we can do in your case is to send the same event via another software. There are programs that allows sending sys ex messages, so please try them and let me know about results.

**Comment by valimaties** [comment]
Ok, thanks for your reply, I will try to test it with other software/hardware and I'll come back with results.

**Comment by valimaties** [comment]
I came back after tests.
Yes, of course, this library works as expected!
The problem is that the keyboard responds with a SysEx different than the one you must send to activate that function in the keyboard, which is strange, but this is how the things work. 

So, I will close this issue, as long as it is nothing more than an undocumented SysEx issue of keyboard's manufacturer!
