### ISSUE TITLE
Getting NoteOn time and Length in seconds

### ISSUE THREAD

**Issue by turboman1** [melanchall/drywetmidi#18]
Hello,
This is not an issue (sorry), but I am wondering how I can access all NoteOn events, and these attributes:

     Note-on time (seconds),  
     Length of note (seconds),  
 
  
I tried the code below, but it's giving incorrect values.

```cs 
                IEnumerable<Melanchall.DryWetMidi.Smf.Interaction.Note> notes = midi.GetNotes();
                
                var tempoMap = midi.GetTempoMap();
                foreach (var note in notes)
                { 
                    // note's duration (seconds)
                    note.LengthAs<MetricTimeSpan>(tempoMap).TotalMicroseconds / 1000000f

                    // note's start time (seconds)
                    note.TimeAs<MetricTimeSpan>(tempoMap).TotalMicroseconds / 1000000f
                 }
```

Thanks!

**Comment by melanchall** [comment]
@turboman1 Will you provide details on issue? :)

**Comment by melanchall** [comment]
I'm going to close the issue since no information provided. Unit tests for the library show that time and length calculations are correct so I don't see any bugs with it.

@turboman1 Please reopen the issue if you have info.
