### ISSUE TITLE
NotEnoughBytesException

### ISSUE THREAD

**Issue by ktp73** [melanchall/drywetmidi#180]
I'm getting the error Melanchall.DryWetMidi.Core.NotEnoughBytesException: 'MIDI file cannot be read since the reader's underlying stream doesn't have enough bytes.' when trying to load a file from disk (please see attached zipped file - [rowan tree live midi sample.zip](https://github.com/melanchall/drywetmidi/files/8693944/rowan.tree.live.midi.sample.zip).

In there something about this file that's an issue - I can open it in other midi tools without issue.

**Comment by melanchall** [comment]
Hi,

Well, that's what we see:

![image](https://user-images.githubusercontent.com/26361185/168458098-5b557c27-528d-4d74-a6c6-3630ba02ae9c.png)

So your file contains unknown chunk and it declares its size bigger than count of remaining bytes in the file. In fact, it's corruption of MIDI spec. And DryWetMIDI **by default** highlights this corruption. But it's a kind of "soft corruption" that can be handled in many cases including yours:

```csharp
var midiFile = MidiFile.Read(
    @"E:\Downloads\rowan.tree.live.midi.sample\rowan tree live midi sample.mid",
    new ReadingSettings
    {
        NotEnoughBytesPolicy = NotEnoughBytesPolicy.Ignore,
        InvalidChunkSizePolicy = InvalidChunkSizePolicy.Ignore
    });
```

Now the file will be read without problems and you'll see an unknown chunk there:

![image](https://user-images.githubusercontent.com/26361185/168458162-786fc8e3-e13a-4d7b-9170-1cf559a8334e.png)

You can get rid of unknown chunk at all on reading a file:

```csharp
var midiFile = MidiFile.Read(
    @"E:\Downloads\rowan.tree.live.midi.sample\rowan tree live midi sample.mid",
    new ReadingSettings
    {
        UnknownChunkIdPolicy = UnknownChunkIdPolicy.Skip
    });
```

And now we won't see the chunk in the `midiFile`:

![image](https://user-images.githubusercontent.com/26361185/168458208-7f8fe21e-827d-4563-86a7-d8863b866c16.png)

So as you can see DryWetMIDI provides you a rich set of settings to control reading process and read a MIDI file exactly as you want. I suppose the tools you've tested the file on just ignore unknown chunk.

**Comment by ktp73** [comment]
Great - thanks for the detailed explanation (I believe the file was created by Ableton - interesting if they are generating corrupted files).
