### ISSUE TITLE
Is it possible to play half mark from midi file ? 

### ISSUE THREAD

**Issue by CIRCE-EYES** [melanchall/drywetmidi#188]
In this tiny example attached it plays a mark called "Csus", and it plays in loop mode perfect. 

But I need to know how to play just the half of the mark, I mean, if the mark plays 8 beats, Id like to play just the first 4 beats only, In loop mode too !! 

Thanks a lot !!!! 
![Play_Half_Mark](https://user-images.githubusercontent.com/69172266/170658917-658b7301-dc84-4ac5-9ad0-dffa42937917.png)

**Comment by CIRCE-EYES** [comment]
> In this tiny example attached it plays a mark called "Csus", and it plays in loop mode perfect.
> 
> But I need to know how to play just the half of the mark, I mean, if the mark plays 8 beats, Id like to play just the first 4 beats only, In loop mode too !!
> 
> Thanks a lot !!!! ![Play_Half_Mark](https://user-images.githubusercontent.com/69172266/170658917-658b7301-dc84-4ac5-9ad0-dffa42937917.png)

**Comment by melanchall** [comment]
Hmm, but I've replied you by email. Here the quote from my letter to you:

> As for your task. If mark's duration is stored in a variable `markDuration` of `ITimeSpan` type, then after jumping to the mark write following code:
> 
> ```csharp
> var currentTime = _playback.GetCurrentTime<MetricTimeSpan>();
> _playback.PlaybackStart = currentTime;
> _playback.PlaybackEnd = currentTime.Add(markDuration.Divide(2), TimeSpanMode.TimeLength);
> _playback.Loop = true;
> ```

**Comment by CIRCE-EYES** [comment]
[How_play_half_Mark.zip](https://github.com/melanchall/drywetmidi/files/8785067/How_play_half_Mark.zip)
[Form1.txt](https://github.com/melanchall/drywetmidi/files/8785068/Form1.txt)

**Comment by CIRCE-EYES** [comment]
Sorry, email empty !!!

**Comment by melanchall** [comment]
@CIRCE-EYES I recommend you to check spam folder or something like that. Because Gmail successfully sent message to you so you should receive it.

**Comment by CIRCE-EYES** [comment]
I will check mail again, anyway here is a tiny example who wants to see how find a mark and play it. 

Thanks and Thanks again !!!!!
