### ISSUE TITLE
Error in Test project after last update

### ISSUE THREAD

**Issue by valimaties** [melanchall/drywetmidi#189]
Hi. I'm getting two errors from `InputDevice` and `OutputDevice` in Test project after I fetched my forked DryWetMidi, about `TestCheckpoints`. Here's a screenshot:

![DryWetMidiTestProjectError](https://user-images.githubusercontent.com/49796453/170684172-fa88c5ad-100d-49c1-9207-67fdf2e16d70.png)

**Comment by melanchall** [comment]
Hi,

`TestCheckpoints` will work only in two build configurations: **DebugTest** and **ReleaseTest**. You can see this in code here: https://github.com/melanchall/drywetmidi/blob/ab918caeb7cb5cf3090f9a164f950d4f25511a7e/DryWetMidi/Multimedia/MidiDevice.cs#L89

So just use one of the build configurations I've shown above.

**Comment by valimaties** [comment]
As long as I use the main project, it's ok. You know better what to do! 🙌
