### ISSUE TITLE
Read custom chunks from a midi file, when chunk header contains no size information

### ISSUE THREAD

**Issue by valimaties** [melanchall/drywetmidi#197]
Hi.
I have a midi file which contains one track with some nested chunks. One of the complex chunks (these ones contains multiple simple chunks or complex chunks, in a nested structure) contains information about waveform data, and the waveform data itself. Yes, wave data in midi file structure. 
The structure is like this:
```
AWav- ComplexChunk
    |- WAVE (no chunk size, only these 4 bytes, as a marker)
    |- Afmt SimpleChunk contains chunk size information
    |- Sfmt SimpleChunk contains chunk size information
etc...
```

using this code
```cs
public sealed class AWavChunk : ComplexChunk
    {
        public const string Id = "AWav";

        public AWavChunk() :
            base(Id, new ChunkTypesCollection
            {
                { typeof(WAVEChunk), WAVEChunk.Id },
                //{ typeof(AfmtChunk), AfmtChunk.Id },
                //{ typeof(SfmtChunk), SfmtChunk.Id },
                //{ typeof(SdecChunk), SdecChunk.Id },
                //{ typeof(AdatChunk), AdatChunk.Id },
                //{ typeof(AInfChunk), AInfChunk.Id }
            })
        {
        }

        public override MidiChunk Clone()
        {
            return new AWavChunk
            {
                Chunks = Chunks.Select(c => c.Clone()).ToList()
            };
        }
    }
```
I'm getting an `InvalidChunkSizeException` for WAVE chunk. (Actual size (1366657) of a WAVE chunk differs from the one declared in the chunk's header (1097231732)). But, as I said, WAVE chunks does not have any size, they are only like markers in this midi file structure. 
If I comment `{ typeof(WAVEChunk), WAVEChunk.Id },` in the code above, and uncomment the others I get `NotEnoughBytesException`

the structure of SimpleChunk and ComplexChunk are the same from #100

**Comment by melanchall** [comment]
Hi,

It looks like you want to read WAVE file. Why do you think it's somehow related to MIDI?

**Comment by melanchall** [comment]
I think you need to combine multiple libraries to read your file. You can read entire structure with DryWetMIDI, but for reading the complex chunk (which includes WAVE marker) you can use dedicated library for audio, for example, NAudio.

**Comment by valimaties** [comment]
> Hi,
> 
> It looks like you want to read WAVE file. Why do you think it's somehow related to MIDI?

Because:
1. The file header is MThd.
2. Second chunk is MTrk.
3. Next chunks are some nested chunks, one of them we spoke already in the past, OTSc and CASM.

The file is an Audio Style format from Yamaha. The style engine from the keyboard read those wave files and play them in loop.
I don't want to play the audio chunks, I only want to read the file and to see where the problems are, because the files from keyboard are ok, but the custom Audio Styles made in their soft have some problems. I want to check, and if I can, to repair the problems.

**Comment by melanchall** [comment]
Oh, really complex structure :) Well, maybe we can adjust reading of `AWav` chunk moving reader's position by 4 bytes on the start? If you show me your class for `AWav` chunk, I'll try to show what I mean.

It's impossible for MIDI chunkto omit its length. WAVE in fact is not a chunk, it's indeed sort of marker as it is in WAV files.

> You say that `AFil` chunk I must read it with NAudio?

No, now I see that actually there is no valid WAV file inside, it's a mix of MIDI and WAV.

**Comment by valimaties** [comment]
`AWav` class is in the first post, already. You want me to show those simple classes too? for `WAVEChunk`, `AfmtChunk` and so on?
Those are `SimpleChunk` classes and `AInf` is a ComplexChunk, like `AWav`.

**Comment by melanchall** [comment]
Well, something like this:

```csharp
public sealed class AWavChunk : ComplexChunk
{
    public const string Id = "AWav";

    public AWavChunk() :
        base(Id, new ChunkTypesCollection
        {
            //{ typeof(AfmtChunk), AfmtChunk.Id },
            //{ typeof(SfmtChunk), SfmtChunk.Id },
            //{ typeof(SdecChunk), SdecChunk.Id },
            //{ typeof(AdatChunk), AdatChunk.Id },
            //{ typeof(AInfChunk), AInfChunk.Id }
        })
    {
    }

    protected override void ReadContent(MidiReader reader, ReadingSettings settings, uint size)
    {
        reader.Position += 4; // skip WAVE marker
        
        base.ReadContent(reader, settings, size);
    }

    public override MidiChunk Clone()
    {
        return new AWavChunk
        {
            Chunks = Chunks.Select(c => c.Clone()).ToList()
        };
    }
}
```

**Comment by valimaties** [comment]
This is ok in reading process. But I think it will blowup the structure when I write back the file, doesn't it?

**Comment by melanchall** [comment]
```csharp
protected override void ReadContent(MidiReader reader, ReadingSettings settings, uint size)
{
    reader.Position += 4; // skip WAVE marker
    base.ReadContent(reader, settings, size - 4);
}

protected override void WriteContent(MidiWriter writer, WritingSettings settings)
{
    writer.WriteString("WAVE");
    base.WriteContent(writer, settings);
}

protected override uint GetContentSize(WritingSettings settings)
{
    return base.GetContentSize(settings) + 4;
}
```

**Comment by valimaties** [comment]
Thank you Maxim. Till I will make all classes which modifies my file to be able to save it, I will close this issue. In theory, it must work!
