### ISSUE TITLE
PatternBuilder SetProgram method not working with ToTrackChunk method

### ISSUE THREAD

**Issue by meckzqz** [melanchall/drywetmidi#20]
Code to reproduce:

```
PatternBuilder patternBuilder = new PatternBuilder();
patternBuilder.SetProgram(GeneralMidiProgram.Accordion);
patternBuilder.Note(NoteName.C);
MidiFile midiFile = new MidiFile(new[]
{
    patternBuilder.Build().ToTrackChunk(TempoMap.Default, (FourBitNumber)1)
});
```

Expected Result: Program index will be changed on channel 1 and note will play on channel 1.
Result: Program index has been changed on channel 0 and note plays on channel 1.

Thank you for any attention brought to this issue. My apologies if this is the result of a misunderstanding of DryWetMIDI on my part.

**Comment by melanchall** [comment]
Hi,

I confirm the issue. I've fixed it in _develop_ branch and the fix will be available in next release of the library. At now you have several options to work around the issue:

* Build the library from sources of the _develop_ branch
* Wait for the next release
* Insert `ProgramChangeEvent` at start of track chunk after `ToTrackChunk` call:

    ```csharp
    var trackChunk = patternBuilder.Build().ToTrackChunk(TempoMap.Default, (FourBitNumber)1);
    trackChunk.Events.Insert(0, GeneralMidiProgram.Accordion.GetProgramEvent());
    ```

**Comment by meckzqz** [comment]
Hello,

The quick turnaround time on this is much appreciated. I have tried using the solution you've proposed, and the results are unchanged from my previous report.

The code in question:

```csharp
var trackChunk = patternBuilder.Build().ToTrackChunk(TempoMap.Default, (FourBitNumber)0);
trackChunk.Events.Insert(0, GeneralMidiProgram.Accordion.GetProgramEvent());
var chordTrackChunk = chordPatternBuilder.Build().ToTrackChunk(TempoMap.Default, (FourBitNumber)1);
chordTrackChunk.Events.Insert(0, GeneralMidiProgram.Pad8.GetProgramEvent());
MidiFile midiFile = new MidiFile(new[]
{
    trackChunk,
    chordTrackChunk
});
```

I'm prepared to switch to the develop branch for now, but I'm confused as to why this code isn't functioning as expected.

**Comment by melanchall** [comment]
Oh sorry, I forgot to set `Channel` property on event returned by `GetProgramEvent`:

```csharp
var programChangeEvent = (ProgramChangeEvent)GeneralMidiProgram.Pad8.GetProgramEvent();
programChangeEvent.Channel = (FourBitNumber)1;
chordTrackChunk.Events.Insert(0, programChangeEvent);
```

@meckzqz, can the issue be closed?
