### ISSUE TITLE
Consider seperating timing logic into new project

### ISSUE THREAD

**Issue by jhimes144** [melanchall/drywetmidi#203]
The high resolution timing logic contained in this library is a hidden gem. Would anyone consider separating it out into a new open source project?

**Comment by melanchall** [comment]
I should notice that:

1. right now this logic implemented for Windows and macOS only;
2. implementation for Windows can be more accurate via usage of undocumented WinAPI functions `NtQueryTimerResolution`, `NtSetTimerResolution` and `NtDelayExecution`.

Can you please say why you're so excited by timing logic with DryWetMIDI? :)

**Comment by jhimes144** [comment]
@melanchall 

I'm sorry for replying so late.

I am using the timing logic for a .net application to control entertainment lighting fixtures with the DMX protocol and other ip based protocols. These IP protocols (ArtNet) require that I send packets at 45fps intervals, I wish to maintain a main "loop" in my application that is locked to 45fps. I currently use my own fork of just your multimedia code to accomplish this with precision. The alternative is busy waiting an entire processor core the entire time the app is open. I also use this entire project for other midi-related things in the same app.

I'm now looking at making my own solution for Linux, using hrtimers. As an aside, can I ask why you chose to forego implementing Linux in this project?
