### ISSUE TITLE
Device is already in use (IN_OPENRESULT_ALLOCATED)

### ISSUE THREAD

**Issue by thebitbrine** [melanchall/drywetmidi#205]
I opened the MIDI device using the following code:

```CSharp
IInputDevice _inputDevice = InputDevice.GetByName(deviceName);
_inputDevice.EventReceived += OnEventReceived;
_inputDevice.StartEventsListening();
```

Since there's no way to disconnect the device, I tried the following:
```CSharp
_inputDevice.StopEventsListening();
_inputDevice = null;
```

After switching to another MIDI input, now I want to connect to the first one but this is what I get:
`Device is already in use (IN_OPENRESULT_ALLOCATED)`

How can I Dispose/Disconnect the first device so I can connect to it later?

**Comment by thebitbrine** [comment]
I was using `IInputDevice` instead of `InputDevice`, consuming the class directly exposes `.Dispose()` which solves the problem.

Final code:
```CSharp
//Init
IInputDevice _inputDevice = InputDevice.GetByName(deviceName);
_inputDevice.EventReceived += OnEventReceived;
_inputDevice.StartEventsListening();

//Dispose
_inputDevice.StopEventsListening();
_inputDevice.Dispose();
```

**Comment by melanchall** [comment]
@thebitbrine Hmm, maybe it's a good idea to derive `IInputDevice` from `IDisposable`. I'll think about it.

**Comment by melanchall** [comment]
Well, now `IInputDevice` and `IOutputDevice` are derived from `IDisposable`. Changes are available in a prerelease version of the DryWetMIDI on NuGet – [6.1.2-prerelease3](https://www.nuget.org/packages/Melanchall.DryWetMidi/6.1.2-prerelease3).

**Comment by melanchall** [comment]
:rocket: **6.1.2 version is released now!**

Prerelease NuGet packages will be unlisted soon, so please update the package references to the new version.

Thanks for using the library!
