### ISSUE TITLE
BUG: inputDevice StartEventListening

### ISSUE THREAD

**Issue by Ploogle** [melanchall/drywetmidi#206]
The following code snippet:

```
 private InputDevice _inputDevice;

    void Start()
    {
        foreach (InputDevice device in InputDevice.GetAll())
        {
            _inputDevice = device;
            break;
        }

        _inputDevice.EventReceived += OnEventReceived;
        _inputDevice.StartEventsListening();  
     }
```

Produces the following error:
```
MidiDeviceException: Internal error (IN_OPENRESULT_PREPAREBUFFER_INVALIDHANDLE).
Melanchall.DryWetMidi.Multimedia.NativeApi.HandleResult[TResult,TException] (TResult result, System.Func`3[T1,T2,TResult] createException) (at <ab947fe0485d4bc880e852225aad217d>:0)
Melanchall.DryWetMidi.Multimedia.NativeApiUtilities.HandleDevicesNativeApiResult[TResult] (TResult result) (at <ab947fe0485d4bc880e852225aad217d>:0)
Melanchall.DryWetMidi.Multimedia.InputDevice.EnsureHandleIsCreated () (at <ab947fe0485d4bc880e852225aad217d>:0)
Melanchall.DryWetMidi.Multimedia.InputDevice.StartEventsListening () (at <ab947fe0485d4bc880e852225aad217d>:0)
MIDIController.Start () (at Assets/MIDIController.cs:35)
```

100% of the time. I was originally attempting to GetName() but switched to the foreach device for debugging to ensure that it was getting a valid device from the list. Outputting the device in question shows that it is the correct one I'm trying to connect to.

This is in Unity3D v2020.3.28f1, running on Windows 11 64-bit.

**Comment by melanchall** [comment]
1. What's the kind of a device? Is it really input one like MIDI keyboard or so?
2. What's the name of a problem device?
3. Does the error reproduced for this device only or for all devices?
4. How DryWetMIDI installed? Via Asset Store or via placing DLLs near Unity project manually?

**Comment by Ploogle** [comment]
1/2. SpringBeats Virtual MIDI https://springbeats.com/sbvmidi/

3. I dug up a MIDI hardware device and it looks like it works perfectly for the MPKMini2.
4. Installed DryWetMIDI via the Asset Store / package manager.

**Comment by melanchall** [comment]
I've installed this software on my Win 10 and all works fine:

```csharp
var id = InputDevice.GetByName("Springbeats vMIDI1");
id.EventReceived += Id_EventReceived;
id.StartEventsListening();
```

So please say the name of your device (`_inputDevice.Name`). Also try to use this device in some 3d party software (for example assign it as an input device for a software synth).

**Comment by Ploogle** [comment]
I attempted another virtual MIDI cable and it looks like LoopMIDI works perfectly with DryWetMIDI. My guess is it's a bug with the SpringBeats Virtual MIDI driver in Windows 11.

Thank you for your very quick responses! I'm super happy with DryWetMIDI.
