### ISSUE TITLE
sysEx Message data

### ISSUE THREAD

**Issue by amritgenius** [melanchall/drywetmidi#208]
Sorry to bother you. this library is great but i need something to read the sysex messages sent over midi. im getting the event but can't able to read the raw message.

**Comment by melanchall** [comment]
Can you please describe your problem in more detail? Do you receive MIDI events via `InputDevice`? What do you mean "raw data"? Do you need to get bytes from sys ex event?

**Comment by amritgenius** [comment]
Hello Sir,
           let me explain a bit, there is a software called hauptwerk, that
software send the data over midi like 39 byte of data or 39 bit, sorry i'm
not data structure person hahah, im write a software in c# in which i want
to capture the data ( as from input device ) but i need the bytes or raw
message to deal with.

Thankyou.
Singh

**Comment by melanchall** [comment]
Hi Singh,

Try this code:

```csharp
var converter = new MidiEventToBytesConverter();
var bytes = converter.Convert(midiEvent);
```

**Comment by amritgenius** [comment]
private void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
        {
            var converter = new MidiEventToBytesConverter();
            var bytes =  = converter.Convert(e);
            string result = Encoding.UTF8.GetString(bytes);
            Console.WriteLine(result);
        }


NO, MidiEvent and MidiEventReceivedEventArgs are two different things. Error says its not possible to convert one from the other.

**Comment by amritgenius** [comment]
Ok,  
var bytes = converter.Convert(e.Event);  
 solved the problem. 
Thankyou So much for the support.
Love From Italy.
