### ISSUE TITLE
Question about BytesToMidiEventConverter

### ISSUE THREAD

**Issue by valimaties** [melanchall/drywetmidi#209]
Hi.
I have an Yamaha sequencer specific SysEx, which contains a path to a file and the next bytes I supose there are some other midi events, like Control Change or some other controls, I don't know... 
Example of SysEx:
```
43-73-0C-01-45-3A-2F-4D-79-20-53-74-79-6C-65-73-2F-56-61-6C-69-2F-4A-75-6D-61-74-61-74-65-20-74-75-2E-53-39-31-30-2E-50-41-44-00-4E-56-00-00-09-8F-0C-59-9C-8C-E1-02-A4-8C-79-5D-8A-8F-0C-59-9C-8C-64-18-A8-8F-2F-12-60-00-00-00-00-8F-96-7C-58-8F-96-7C-80-03-00-1A-54-8F-97-1E-50-8F-96-7C-58-8F-96-7C-58-8F-96-7C-80-8F-96-7C-58-8F-96-7C-80-8F-96-7C-58-8F-96-7C-80-03-8A-E8-48-8F-97-1E-50-8F-97-29-B4-8F-96-7C-58-30-00-00-38-FF-00-00-00-07-2C-69-6C-00-00-00-6F-00-00-00-01-8F-0E-F7-54-8C-C1-9D-AC-8F-0E-E9-C0-8C-2D-1E-BA-00-00-00-34-8C-DA-0E-27-8C-2C-65-72-00-00-00-80-00-00-00-01-00-00-00-00-8F-5E-70-B4-8F-04-90-68-00-00-00-70-62-30-00-03-8C-2C-76-1A-70-30-00-03-8C-2C-6D-22-8F-0C-5A-3E-8C-C1-31-6C-8C-2A-AE-46-00-00-00-15-00-00-00-01-00-00-00-00-8C-C1-31-6C-8C-70-CA-E0-00-00-00-00
```
The first four bytes tells me that it is an SysEx for changing **MultiPads**. After those 4 bytes I have a sequence of bytes that translate to a path of a "pad" file in keyboard, for example:
```
45-3A-2F-4D-79-20-53-74-79-6C-65-73-2F-56-61-6C-69-2F-4A-75-6D-61-74-61-74-65-20-74-75-2E-53-39-31-30-2E-50-41-44
=
E:/My Styles/Vali/Jumatate tu.S910.PAD
```

But the next bytes I suppose there are some MidiEvents regarding this PAD file. Beeing an undocumented SysEx I don't know what contains the sequence of bytes.
I tried to convert the rest of the byte sequence to MidiEvents, but I get `UnexpectedRunningStatusException` exception:
```cs
var mel = (new BytesToMidiEventConverter()).ConvertMultiple(data);
``` 
Could you help me with my issue?! 
Thanks!

**Comment by melanchall** [comment]
Hi,

First of all, parsing of sys ex data is up to you. Since you don't know format of the message, the only thing I can do for you is to ask a couple of questions:

1. I see you pass `data` variable in last code snippet. Does this array contains only bytes after file path?
2. Did you try to set `ReadDeltaTimes` property to `true` on converter?

**Comment by valimaties** [comment]
> Hi,
> 
> First of all, parsing of sys ex data is up to you. Since you don't know format of the message, the only thing I can do for you is to ask a couple of questions:
> 
> 1. I see you pass `data` variable in last code snippet. Does this array contains only bytes after file path?
> 2. Did you try to set `ReadDeltaTimes` property to `true` on converter?

Hi @melanchall 
1. Yes, data variable contains only byte[] without path of pad file.
2. I didn't set that property. I will try again with this property set to true and came back after that!

**Comment by valimaties** [comment]
I've set the property to true, but I've encountered the same error ... Seems I have to dig more on this byte array... :(
Thanks
