### ISSUE TITLE
Can't install NuGet package through PowerShell

### ISSUE THREAD

**Issue by xhevahir** [melanchall/drywetmidi#21]
Hi,
I'm trying to install using the NuGet instructions, and Powershell gives this error:
Install-Package : A parameter cannot be found that matches parameter name 'Version'.
At line:1 char:44
+ Try {Install-Package Melanchall.DryWetMidi -Version 4.0.0}Catch {$_ | ...
+                                            ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

I'm new to .NET, so maybe I'm missing something obvious.

**Comment by melanchall** [comment]
Hi,

Please try to run the following command in PowerShell:

```
Install-Package Melanchall.DryWetMidi -Verbose
```

and show me the output of it.

**Comment by melanchall** [comment]
Hi,

Please note that `Install-Package` with `-Version` parameter is a command for [NuGet Package Manager Console](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-install-package) inside Visual Studio. It's not a command for PowerShell.

PowerShell's `Install-Package` has not `-Version` parameter.

Is it an option to install package for your project with Visual Studio? Or you must do it via PowerShell only?

**Comment by xhevahir** [comment]
That worked! Thanks a lot for helping a newbie.

**Comment by ajnair100** [comment]
am still facing the issue am unable to install SMO 14 for sql 2017 for me to run my Avamar backup which needs these Smo14 

how can I do this ? any idea is it powershell script or Nuget or what  should be done to get these SMo14 for sql 2017??

the above command PS fails ..
