### ISSUE TITLE
Read a midi file in a web browser ?

### ISSUE THREAD

**Issue by Ghostmoonk** [melanchall/drywetmidi#211]
Hello,

My issue is that I'd like to **read a midi file in a WebGL build** but it seems impossible for the MidiFile.Read function to find the correct path.
It's also tooltiped for the path parameter that it "Reads a midi file by its full path" which also seems wrong. In the editor, the path starts at project root, and in WebGL build, with "/".

I suspect that slash caracter effectively ruining the path to locate the file.
My midi file is located in the **StreamingAssets** folder in a path like _https://127.0.0.1:7777/StreamingAssets/MIDI/file.midi_.

Here is my base code even if it may not be necessary to share :
```
[System.Serializable]
public class MidiField
{
    public string midiFileName;
    public MidiFile MidiFile
    {
        get
        {
            string root = FileManagement.FileManager.GetStreamingAssetFolder();
#if UNITY_WEBGL && !UNITY_EDITOR
            return midiFileName.Length > 0 ? 
            MidiFile.Read(midiFileName) : MidiFile.Read(root + "/MIDI/default.mid");
#else
            return midiFileName.Length > 0 ? 
            MidiFile.Read(root + "/MIDI/" + midiFileName) : MidiFile.Read(root + "/MIDI/default.mid");

#endif 
        }
    }
}
```

Thank you for your help

**Comment by melanchall** [comment]
Hello,

DryWetMIDI provides `Read` method overload which takes stream to read file from. Maybe WebGL has an API to get file as stream? You can then pass that stream to `MidiFile.Read`.

**Comment by Ghostmoonk** [comment]
Thanks for your answer.
That's effectively what I did in the end, I created a stream from an `UnityWebRequest` and passed it instead of a string.

**Comment by melanchall** [comment]
@Ghostmoonk So the problem is solved and the issue can be closed?
