### ISSUE TITLE
NoteOn event fired even if I release the Note

### ISSUE THREAD

**Issue by arjOman** [melanchall/drywetmidi#218]
I have a Yamaha PSR-E473, connected through USB3. I was trying to listen to the NoteOff event, but it was never fired, even after releasing the key.

**Comment by melanchall** [comment]
I suppose you use `InputDevice`. The class has [`SilentNoteOnPolicy`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Multimedia.InputDevice.html#Melanchall_DryWetMidi_Multimedia_InputDevice_SilentNoteOnPolicy) property which declares how _Note On_ event with zero velocity is handled. By default such events are treated as _Note On_ ones, i.e. as is.

My assumption your device sends _Note Off_ events as _Note On_ ones with zero velocity. Just set `SilentNoteOnPolicy` to `SilentNoteOnPolicy.NoteOff` value:

```csharp
inputDevice.SilentNoteOnPolicy = SilentNoteOnPolicy.NoteOff;
...
inputDevice.StartEventsListening();
```

**Comment by arjOman** [comment]
Hi, changing the property did help. Thank you!
