### ISSUE TITLE
how to split midi files into windows of x bars

### ISSUE THREAD

**Issue by cristianmtr** [melanchall/drywetmidi#22]
Hey

I am looking through the documentation but I can't seem to find what I need

I want to split a midi file into windows of 8 bars, with a step size of 1 bar

Any suggestions?

Cheers

**Comment by melanchall** [comment]
Hi,

> I want to split a midi file into windows of 8 bars, with a step size of 1 bar

So what the length of each new MIDI file? 1 bar or 8 bars?

**Comment by cristianmtr** [comment]
8 bars. Then move 1 bar forward in time, and generate the next 8 bars from the file. And so on, until I reach the end of the file (the last 8 bar sequence)

Does that make sense?

**Comment by melanchall** [comment]
Thanks for clarification. Please try this code:

```csharp
using Melanchall.DryWetMidi.Smf;
using Melanchall.DryWetMidi.Smf.Interaction;
using Melanchall.DryWetMidi.Tools;

// ...

var newFiles = midiFile.SplitByGrid(
    new SteppedGrid(new BarBeatTimeSpan(8, 0), new BarBeatTimeSpan(1, 0)));
```

This code splits `midiFile` into new files with length of 8 bars and 1 bar:

```
|--------|-|--------|-|--------|-|--------|-|--------|
```

Just remove files with length of 1 bar (every second) and you'll get desired result. If it's supposed that 1-bar files will be empty you can try to set `RemoveEmptyFiles` to `true` on `SplittingMidiFileByGridSettings` passed to `SplitByGrid`:

```csharp
var newFiles = midiFile.SplitByGrid(
    new SteppedGrid(new BarBeatTimeSpan(8, 0), new BarBeatTimeSpan(1, 0)),
    new SplittingMidiFileByGridSettings
    {
        RemoveEmptyFiles = true
    });
```

You can find more information about MIDI file splitting on the library Wiki: [MIDI file splitter](https://github.com/melanchall/drywetmidi/wiki/MIDI-file-splitter). Please note that `SplittingMidiFileByGridSettings` has some useful properties that can help you to get desired result.

Thanks for your case. It seems it will be useful to add kind of `Margin` property to implementations of `IGrid` to support scenarios like yours.

**Comment by cristianmtr** [comment]
Wow, thanks so much for this!

But actually, it's not what I meant:

Let's take this line as being a musical piece, each `-` being a bar.

```
|--------|----------...
```

In the above I have extracted an 8-bar segment.

I then want to extract the next 8-bar segment, but with a step size of 1

```
-|--------|---------...
```

Does that make sense?

The code you provided extracts an 8-bar segments, then moves **9** bars as a step, and then extracts the next 8bar segment

**Comment by melanchall** [comment]
No, it extracts 8-bar file, then extracts 1-bar file, then extracts 8-bar file and so on :) You just need to ignore those files with length of 1 bar.

**Comment by cristianmtr** [comment]
Yes, I understand that. But that's now what I want.

Given a piece like this and an initial 8 bar segment.

```
|--------|----------...
```

I don't want to move 1 bar starting after the segment, but from the beginning

```
-|--------|---------...
```

As compared with what you are doing, where the next segment would be this:

```
---------|--------|-...
```

It's a sliding window.

**Comment by melanchall** [comment]
Oh, sorry, finally got it :) I'll try to provide you a solution a bit later.

**Comment by cristianmtr** [comment]
Thanks a lot ! 

I am trying myself to figure it out, but my C# skills aren't as sharp as they used to be...

**Comment by melanchall** [comment]
Please try this code:

```csharp
var result = new List<MidiFile>();
var windowSize = 8;

for (var i = 0; ; i++)
{
    var startTime = new BarBeatTimeSpan(i, 0);
    var endTime = new BarBeatTimeSpan(i + windowSize, 0);

    var grid = new ArbitraryGrid(new[] { startTime, endTime });
    var newFiles = midiFile.SplitByGrid(grid).ToList();

    var lengths = new List<ITimeSpan>();
    foreach (var f in newFiles)
    {
        lengths.Add(f.GetTimedEvents().Last().TimeAs<BarBeatTimeSpan>(TempoMap.Default));
    }

    if (!newFiles.Any())
        break;
    else if (newFiles.Count == 1)
        result.Add(newFiles[0]);
    else
    {
        var secondNewFile = newFiles[1];
        var tempoMap = secondNewFile.GetTempoMap();
        var length = secondNewFile.GetTimedEvents().LastOrDefault()?.TimeAs<BarBeatTimeSpan>(tempoMap);

        if (length.Bars == windowSize || (length.Bars == windowSize - 1 && length.Beats > 0 && length.Ticks > 0))
            result.Add(secondNewFile);
        else
            break;
    }
}
```

`length.Bars == windowSize || (length.Bars == windowSize - 1 && length.Beats > 0 && length.Ticks > 0)` means
* length of new file is exactly of window size; or
* length of new file is `windowSize - 1` but it close to window size, so `7.3.99` will be considered as `8` bars; this condition is placed for cases of rounding errors during time/length conversions.

**Comment by cristianmtr** [comment]
Thanks a lot, that worked!
