### ISSUE TITLE
how to change instruments 

### ISSUE THREAD

**Issue by tramper2** [melanchall/drywetmidi#224]
Hi!
now i'm using master-keyboard for midi input device.
and i want to change instrument when i want.
it is ok in NAudio as belows
but i don't know how can i change it in DryWetMidi
===== in NAudio ====

 string OutputDeviceName = "Microsoft GS Wavetable Synth";
 string inputDeviceName = "MPK mini 3";
.....
//change instruments
 public void ChangeChanelNumber(int ch)
    {
        switch (ch)
        {
            case 1:
                _outputdevice.Send(new PatchChangeEvent(0, 1, 0).GetAsShortMessage());
                break;
            case 2:
                _outputdevice.Send(new PatchChangeEvent(0, 1, 78).GetAsShortMessage()); 
                break;
.....

//input callback - send to  output device
private void _inputdevice_MessageReceived(object sender, MidiInMessageEventArgs e)
{
 	 _outputdevice.Send(e.MidiEvent.GetAsShortMessage());
}

but i don't know in DryWetMidi
=====in DryWetMidi =====

//Change Instruments
 public void ChangeChanelNumber(int ch)//, int inst)
    {
        chanelNumber = ch;
        switch (ch)
        {
            case 1:
                _outputDevice.SendEvent(new ProgramChangeEvent((SevenBitNumber)0) { Channel = (FourBitNumber)ch, DeltaTime = 0 });
                break;
            case 2:
                _outputDevice.SendEvent(new ProgramChangeEvent((SevenBitNumber)40) { Channel = (FourBitNumber)ch, DeltaTime = 0 });
                break;

.....

//call back
private void OnEventReceived (object sender, MidiEventReceivedEventArgs e)
{
	 _outputDevice.SendEvent(e.Event); //??????? 
}

==================
Thanks
Danny

**Comment by melanchall** [comment]
Hi,

Honestly I don't understand what's wrong with your code. Can you please explain where an error occurred on incorrect behavior or smth else?

If you about this line

```csharp
_outputDevice.SendEvent(e.Event); //???????
```

you do here exactly the same actions as in NAudio code. So what's going wrong?

Also there is no need to set `DeltaTime` on event sending, it's ignored since an event will be sent immediately as you call `SendEvent`.

**Comment by tramper2** [comment]
Thanks for your reply

it is working in this way 
i can hear changed instrument audio
============================
 if (Input.GetKeyDown(KeyCode.A))
        {
            _outputDevice.SendEvent(new NoteOnEvent((SevenBitNumber)60, (SevenBitNumber)120) { Channel = (FourBitNumber)chanelNumber});
            piano. Text = "A";
        }

==============================

_outputDevice.SendEvent(e.Event); //I can't hear changed instruments, it's play only piano always

**Comment by melanchall** [comment]
Well, just change the method to this:

```csharp
public void ChangeChanelNumber(int ch)
{
    switch (ch)
    {
        case 1:
            _outputDevice.SendEvent(new ProgramChangeEvent((SevenBitNumber)0) { Channel = (FourBitNumber)0 });
            break;
        case 2:
            _outputDevice.SendEvent(new ProgramChangeEvent((SevenBitNumber)78) { Channel = (FourBitNumber)0 });
            break;
```

This is equivalent of NAudio code you've provided me in your first message. In NAudio channel is a number from `1` to `16` and you always set it to `1`. But in DryWetMIDI channel is a number from `0` to `15`, so `1` in NAudio becomes `0` in DWM.

**Comment by tramper2** [comment]
Thanks

I've solved with this code

 var notevent = e.Event as NoteOnEvent;
        _outputDevice.SendEvent(new NoteOnEvent(notevent.NoteNumber, notevent.Velocity) { Channel = (FourBitNumber)chanelNumber });

but there are others problem again. such a violin, sounds keep going... i think there is some problem with velocity

**Comment by tramper2** [comment]
Thanks

I've solved with this code

 var noteOnevent = e.Event as NoteOnEvent;
        _outputDevice.SendEvent(new NoteOnEvent(noteOnevent.NoteNumber, noteOnevent.Velocity) { Channel = (FourBitNumber)chanelNumber });

but there are others problem again. such a violin, sounds keep going... i think there is some problem with velocity
