### ISSUE TITLE
How to combin 2 midifile?

### ISSUE THREAD

**Issue by tramper2** [melanchall/drywetmidi#228]
Hello~

i have a piano midi file and a drum midi file.

i want to combin two midi file into one midi file.

what is the best way?

Thanks Danny

**Comment by tramper2** [comment]
[Drum_pt4_4_hi-hats.zip](https://github.com/melanchall/drywetmidi/files/9909689/Drum_pt4_4_hi-hats.zip)
Hi
it is zip file and two midi file length is different.
Thanks

**Comment by melanchall** [comment]
Unfortunately your files have different tempo maps (different time divisions, different tempo) so there is no way to merge files easily. Merging is possible but it's pretty complex algorithm to preserve both tempos and I have no time right now to implement it. I have such plans but for future releases.

In general you need to reduce both time divisions to least common multiple and handle all tempo and time signature changes (depending on what time type you need to preserve – seconds, bars/beats or smth else).

**Comment by tramper2** [comment]
> Unfortunately your files have different tempo maps (different time divisions, different tempo) so there is no way to merge files easily. Merging is possible but it's pretty complex algorithm to preserve both tempos and I have no time right now to implement it. I have such plans but for future releases.
> 
> In general you need to reduce both time divisions to least common multiple and handle all tempo and time signature changes (depending on what time type you need to preserve – seconds, bars/beats or smth else).

oh i understand~
thanks!
