### ISSUE TITLE
Can I use DWM lib in a Windows Form Application?

### ISSUE THREAD

**Issue by dza6549** [melanchall/drywetmidi#23]
Sorry to be such a total ignorant time-wasting newbie but how would I use the DryWetMidi package in a Windows Form Application?

I've downloaded the NuGet package and I can see the reference, have added the using Melanchall.DryWetMidi; statements and have added the BuildMoonlightSonata.cs from CodeProject and drywetmidi-examples-createfile.cs from git to my solution but I can't seem to access the methods.

The master build doesn't seem to have any forms (shock! horror!) and I'm all lost without my forms.

Ultimately I'd like to use the MIDI file split functions on a bunch of midi files. So maybe I need to learn WPF?

My apologies for asking such a dumb question.

Thanks

**Comment by melanchall** [comment]
Hi,

Thank you for using the library.

DryWetMIDI is just a .NET library, it's not about UI. It provides features to work with MIDI files and devices. You can use it in any .NET Framework application: console or GUI, WinForms or WPF.

Please tell me, what's the problem you've encountered?

If you want to use MIDI file splitting features, please read the article in the library Wiki: [MIDI file splitter](https://github.com/melanchall/drywetmidi/wiki/MIDI-file-splitter). You need add `using Melanchall.DryWetMidi.Tools` to access [tools](https://github.com/melanchall/drywetmidi/wiki/Tools).

If you want to draw content of a MIDI file, it's up to you. DryWetMIDI is not about visual representation of MIDI entities.

**Comment by dza6549** [comment]
Thanks for your very quick reply @melanchall 

I have read the article MIDI file splitter but do not understand how to implement in WinForms.

Problem: I cannot see DryWetMIDI methods in Intellisense with a basic WinForms app. I have downloaded the Nuget package but I have obviously misunderstood something.

```
`using Melanchall.DryWetMidi;
using Melanchall.DryWetMidi.MusicTheory;
using Melanchall.DryWetMidi.Tools;

namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        private void button1_Click(object sender, EventArgs e)
        {
            string midiPath = @"myMidiFile.mid";

            // Failed to see lib
            //Melanchall.DryWetMidi.Common.Read(string filePath, ReadingSettings settings = null)
            //BuildMoonlightSonata();
            //dry-wet
        }
    }
}`
```

**Comment by melanchall** [comment]
> Melanchall.DryWetMidi.Common.Read

Where did you see that? :) Please take a look at the library README:

> To read a MIDI file you have to use `Read` static method of the `MidiFile`:
> `var midiFile = MidiFile.Read("Some Great Song.mid");`

Also please tell me what does it mean?

> I have downloaded the Nuget package

You need to install package via NuGet Package Manager inside Visual Studio.

**Comment by dza6549** [comment]
@melanchall

Sorry man for my ignorance, I am obviously very stupid basic and do not understand classes.  I tried random things from here https://github.com/melanchall/drywetmidi/wiki/Reading-a-MIDI-file

You can see I here have errors
![pack3](https://user-images.githubusercontent.com/27390320/56034217-17e04100-5d6a-11e9-9804-78be9d43b755.png)

NuGet package is installed
![pack2](https://user-images.githubusercontent.com/27390320/56034276-39d9c380-5d6a-11e9-89a0-ba9ad0bb27ef.png)
![pack1](https://user-images.githubusercontent.com/27390320/56034288-465e1c00-5d6a-11e9-9b42-8e2f34465118.png)

**Comment by melanchall** [comment]
You need add

```csharp
using Melanchall.DryWetMidi.Smf;
```

Please take a look at this symbol in Visual Studio from your screenshot:

![image](https://user-images.githubusercontent.com/26361185/56035565-3aa33300-5d33-11e9-9e12-9e4d01d85a84.png)

If you click this dropdown, VS will suggest you to add missed using automatically.

**Comment by dza6549** [comment]
Thanks @melanchall 

I can read/write the midi file now. I was very stupid and did not read carefully enough.

Can I ask some more questions please?

1: CsvConvertor - I have using Tools but I get an error message
![CsvConvertor](https://user-images.githubusercontent.com/27390320/56073720-ed36cc80-5deb-11e9-939a-17437d157f8f.png)

2: Can I split a midi file into channels and save separate midi files? I have tried many methods (please see my ignorant code below) and I can't find a way to get even basic event information. What I want to do is split a midi file into tracks and then split the tracks into bars or using a grid. I would greatly appreciate if you could suggest to me how I might do this.

Thanks for your time. 

Horrible code failures:
```
`
            foreach (var trackChunk in midiFile.GetTrackChunks())
            {
                Console.WriteLine("Track Chunk ID: " + trackChunk.ChunkId.ToString());

                using (var manager = new TimedEventsManager(trackChunk.Events))
                {
                    TimedEventsCollection timedEvents = manager.Events;
                    TimedEvent firstEvent = timedEvents.First();
                    Console.WriteLine("First Event Delta Time: " + firstEvent.Event.DeltaTime.ToString());
                    //firstEvent.Time = 123;
                    //timedEvents.Add(new TimedEvent(new InstrumentNameEvent("Guitar"), 456));
                }

                //using (var notesManager = trackChunk.ManageNotes())
                //{
                //    //notesManager.Notes.RemoveAll(n => n.NoteName == NoteName.CSharp);
                //    //Console.WriteLine("Notes: " + notesManager.Notes.);
                //}
            }

            //foreach (var midiEvent in midiFile.GetTrackChunks().Select(c => c.Events))
            //{
            //    Console.WriteLine("Event: " + midiEvent.ToString());
            //}

            //var trackChunks = midiFile.GetTrackChunks();
            //using (var notesManager = new NotesManager(trackChunk.Events))
            //{
            //    NotesCollection notes = notesManager.Notes;
            //}

            //using (var chordsManager = new ChordsManager(trackChunk.Events))
            //{
            //    ChordsCollection chords = chordsManager.Chords;
            //}

            using (var notesManager = midiFile.GetTrackChunks().First().ManageNotes())
            {
                NotesCollection notes = notesManager.Notes;

                // Get all C# notes
                //IEnumerable<Note> cSharpNotes = notes.Where(n => n.NoteName == NoteName.CSharp);

                // Reduce length of all C# notes by 100
                foreach (var note in notes)
                {
                    Console.WriteLine("Note length: " + note.Length);
                }

                //var notesEndedAt20Seconds = notesManager.Notes.EndAtTime(new MetricTimeSpan(0, 0, 20), tempoMap);
                //var firstNoteLength = notesEndedAt20Seconds.First().LengthAs<MetricTimeSpan>(tempoMap);
            }`
```

**Comment by melanchall** [comment]
### 1

```csharp
var csvConverter = new CsvConverter();
csvConverter.ConvertMidiFileToCsv(midiFile, "D:\taiko.csv", true, null);
```

### 2

```csharp
// Split by channel

var midiFilesByChannels = midiFile.SplitByChannel();

// Split each new file by grid with step of 1 bar and save each 1-bar file

var grid = new SteppedGrid(new BarBeatTimeSpan(1, 0));

foreach (var midiFileByChannel in midiFilesByChannels)
{
    var channel = midiFileByChannel.GetTimedEvents().Select(e => e.Event).OfType<ChannelEvent>().First().Channel;
    var oneBarFiles = midiFileByChannel.SplitByGrid(grid);

    var i = 0;
    foreach (var oneBarFile in oneBarFiles)
    {
        oneBarFile.Write($"File_{channel}_{i++}.mid");
    }
}
```

**Comment by dza6549** [comment]
@melanchall 

This is incredible! Thank you so much :)

Cheers
