### ISSUE TITLE
About multi-platform support in unity

### ISSUE THREAD

**Issue by Personuo** [melanchall/drywetmidi#236]
Hi, is it possible to provide a table that tells us the current version
what features drywetmidi can support in each of the different platforms?

I currently only need to read midi files and visualize the music on android, ios, win, osx and will not use any midi device input and output. Will there be any problems?

**Comment by melanchall** [comment]
Hi,

Great idea! I'll definitely provide such a table in couple of days.

As for reading a MIDI file, it should work on all platforms .NET supports. So if we're talking about .NET 6+, then yes, you can read a file on all platforms you've specified.

Thanks,
Max

**Comment by Personuo** [comment]
Oh, thank you!

**Comment by melanchall** [comment]
I've added [Supported OS](https://melanchall.github.io/drywetmidi/articles/dev/Supported-OS.html) article to the library docs.
