### ISSUE TITLE
Native64 dll not found on UWP

### ISSUE THREAD

**Issue by mpelika** [melanchall/drywetmidi#238]
On the Inspector on the Native64.dll i have selected Platform Settings ->
 SDK = UWP ,
 CPU = ARM64 (i'm using hololens2 ), 
scripting backend = any scripting backend.

 On DryWetMidi.dll i selected SDK = UWP without excluding any platforms. Even though , i dont face any issues building my app, once i load it on hololens i get a message that the native64.dll cannot be found. I can't solve the issue.

(Win32): Loaded 'U:\USERS\DefaultAccount\AppData\Local\DevelopmentFiles\mlearnVS.Release_ARM64.Mary_pel\Melanchall_DryWetMidi_Native64.dll'. 
(Win32): Unloaded 'U:\USERS\DefaultAccount\AppData\Local\DevelopmentFiles\mlearnVS.Release_ARM64.Mary_pel\Melanchall_DryWetMidi_Native64.dll'

**Comment by melanchall** [comment]
Hi,

First of all, some points:

1. Work of the package is not guaranteed on UWP. There was the issue about some problems, but I've decided to stop working on UWP support.
2. I didn't build native dlls for arm64.
3. Even if arm64 version will be available, are you sure required system Windows libraries are present on Hololens? We need winmm.dll there.

Also you haven't provide the code where you got an exception. Please show the code and stacktrace of the exception.

Max

**Comment by melanchall** [comment]
I'm closing the issue since no info provided.
