### ISSUE TITLE
How do I know when i have added sufficient notes for a bar using the Pattern Builder Class

### ISSUE THREAD

**Issue by seunyboyxu** [melanchall/drywetmidi#239]

**Comment by melanchall** [comment]
Hi,

Please read this first – https://melanchall.github.io/drywetmidi/articles/dev/Support.html – and correct the issue. Make short title and provide as many details as possible in the issue description.

Thanks,
Max

**Comment by seunyboyxu** [comment]
hi max, it is more of a question than an issue, I just wasn't really sure how to ask

**Comment by melanchall** [comment]
You didn't provide any details. Show some code and what do you want somewhere in that code.

**Comment by seunyboyxu** [comment]
So i have this class called FinalNote, 
![image](https://user-images.githubusercontent.com/78118301/218318640-0d4eabf2-ca0f-4a38-9c6b-9f452967baa4.png)
NoteName ranges from "A" to "G" including sharps
NoteDuration is in a double where for example 0.25 would represent a quarter note (1/4), like this dictionary i made

![image](https://user-images.githubusercontent.com/78118301/218318784-195d5130-f887-4a33-9d3f-635d2c8a5266.png)


It is in a 2d List where each list represents a bar. And each bar has a list of FinalNote objects.
Here is a test example of what this 2d List will look like with a time signature as 4/4
![image](https://user-images.githubusercontent.com/78118301/218319240-6d58264d-991b-4ff0-b8a0-06201b3ee0e9.png)
where you should see the Final Note objects generated

I want to put my note data into a midi file bar by bar, but I am unsure how to do that since I can't find many guides about how PatternBuilder works. 

I currently have this, ignore the ChordSequence parameter, since i want to do the exact same thing with chords but i want to deal with the notes first

![image](https://user-images.githubusercontent.com/78118301/218319378-d37c6a5d-d846-4eb7-bb1b-b6adbb30f50f.png)

Thank you, let me know if you need any more information

**Comment by melanchall** [comment]
Thank you very much for explanation, that's what I wanted :) Please answer following questions:

1. You have collection (bars) where each item is a collection of notes, right?
2. Each bar is complete, right? Or is it possible that, for example, bar with signature of 4/4 will have 3 quarter notes?
3. Each note has length as a fraction of the whole note, right?
4. Notes should be written in a file without gaps between them, right?

**Comment by seunyboyxu** [comment]
1. Yes,
2. Each bar is complete
3. yes
4. yes

**Comment by melanchall** [comment]
Well, in this case your task is supereasy, we even don't need to know where bars borders are. I'll provide you a solution a bit later. Right now I have one more question: what is the octave of notes? Every note in MIDI is a number which represents letter+octave. We can't write just note's name in a MIDI file.

**Comment by seunyboyxu** [comment]
**I want it to default to octave number 4.** 
I am looking into making my program intelligently switch between octaves.

**Comment by seunyboyxu** [comment]
do you need to see any other parts of the program to help you?

**Comment by melanchall** [comment]
No, I have all required info now, thanks.

**Comment by melanchall** [comment]
I suppose something like that should work:

```csharp
public MidiFile MidiMaker100(
    List<List<FinalNote>> notesByBars,
    int octave,
    int bpm,
    string timeSignatureString)
{
    var patternBuilder = new PatternBuilder();

    foreach (var barNotes in notesByBars)
    {
        foreach (var note in barNotes)
        {
            patternBuilder.Note(
                Melanchall.DryWetMidi.MusicTheory.Note.Parse($"{note.GetNoteName()}{octave}"),
                NoteDurationConversion[note.GetNoteDuration()]);
        }
    }

    var tempo = Tempo.FromBeatsPerMinute(bpm);

    var numer = ...
    var denom = ...
    var timeSignature = new TimeSignature(numer, denom);

    var tempoMap = TempoMap.Create(tempo, timeSignature);

    return patternBuilder.Build().ToFile(tempoMap);
}
```

Calculate `numer` and `denom` by yourself please. But your way is obviously wrong. Please read official documentation how `Substring` with single argument works.

I've also added `octave` parameter so just pass what you want there.

**Comment by seunyboyxu** [comment]
Hi, sorry I will learn this. 
This all works but how do I add the pattern to a new MidiFile object as a track chunk because I also want to add chords to the same MidiFile object?

**Comment by melanchall** [comment]
DryWetMIDI has complete documentation, use it please – https://melanchall.github.io/drywetmidi.

So, if you start from [`PatternBuilder`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Composing.PatternBuilder.html), you'll find its [`Build`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Composing.PatternBuilder.html#Melanchall_DryWetMidi_Composing_PatternBuilder_Build) method, which returns [`Pattern`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Composing.Pattern.html) object which has [`ToTrackChunk`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Composing.Pattern.html#Melanchall_DryWetMidi_Composing_Pattern_ToTrackChunk_Melanchall_DryWetMidi_Interaction_TempoMap_) method. And thus you need to use following code:

```csharp
var notesTrackChunk = notesPatternBuilder.Build().ToTrackChunk(tempoMap);
var chordsTrackChunk = chordsPatternBuilder.Build().ToTrackChunk(tempoMap);

var midiFile = new MidiFile(notesTrackChunk, chordsTrackChunk);
midiFile.ReplaceTempoMap(tempoMap);

return midiFile;
```

**Comment by seunyboyxu** [comment]
Thank you, I think this has solved my problem. 
I may need help for something else soon, if I end up struggling with it. 
Hopefully by then I'll be able to ask questions properly on github
