### ISSUE TITLE
Is there simple way to detect the Midievent subclass when receiving incoming events?

### ISSUE THREAD

**Issue by eriveraa** [melanchall/drywetmidi#24]
Hi, i have an inputDevice that are receiving incomind midi messages. However in the event i just have the MidiEventReceivedEventArgs object with the Event property, so how can i detect if that was a NoteEvent or ControlChange Event, or Program Change Event?

Thanks!!
BTW: Nice library!!

**Comment by melanchall** [comment]
Hi,

You just need to use `is` operator of C# :)

```csharp
if (args.Event is ControlChangeEvent)
{
    // ... do something ...
}
```

You can find the list of all event classes in the library Wiki in [Events](https://github.com/melanchall/drywetmidi/wiki/Events) article.

**Comment by melanchall** [comment]
@eriveraa Is your problem solved?

**Comment by eriveraa** [comment]
Hi Melanchall, in fact it works but i was expecting something like a simple property to check (if args.Event.TypeOfMidiEvent == "NoteEvent").
Making a type comparison or type check is time-expensive.

**Comment by extdevx** [comment]
Hi,

Got it. Well I think I'll add such property in the next release. Thanks for your feature request.

**Comment by eriveraa** [comment]
Nice to know!!!, any possible estimated date?

**Comment by melanchall** [comment]
Hi,

Got it. Well, I think I'll add such property in the next release of the library. Thanks for your feature request.

**Comment by melanchall** [comment]
I don't plan to make release for now. But I'll add the property on this or next week. So you can just download sources and build the new version for you.

**Comment by eriveraa** [comment]
Ok, thanks. Please let me know, so i can download the update.

**Comment by melanchall** [comment]
Hi @eriveraa,

I've added `EventType` property to `MidiEvent` which returns `MidiEventType` enum value. Please take latest sources and build the library for your project. I'll write ti this issue when new version of the library will be released so you can install it via NuGet.

Please let me know if you problem solved or not with this update.

**Comment by eriveraa** [comment]
I will try it, thanks!

**Comment by melanchall** [comment]
@eriveraa, can this issue be closed?

**Comment by melanchall** [comment]
@eriveraa I'm closing the issue. If you have new questions regarding this issue, reopen it.
