### ISSUE TITLE
Getting instrument by channel

### ISSUE THREAD

**Issue by Achacu** [melanchall/drywetmidi#241]
Hi,

I'd like to know if it's possible to find the instrument index from each channel in a MIDI file (for instance, if channel 1 is played by a violin):

```
var file = MidiFile.Read(midiPath+".mid");
var filesByChannel = file.SplitByChannel();

foreach (var singleChannelFile in filesByChannel)
{
    //if(instrumentIndexFromFile == violinIndex)
        ProcessFile(singleChannelFile);
}
```
The only related thing I could find in the API is [InstrumentNameEvent](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.InstrumentNameEvent.html), but it is only for creating the meta event that holds that information.

Thank you for your time!

**Comment by melanchall** [comment]
Hi,

Please clarify what is "instrument index"? There is no such concept in MIDI. Do you mean program number? If yes, try this:

```csharp
var programsByChannels = midiFile
    .GetTrackChunks()
    .SelectMany(c => c.Events)
    .OfType<ProgramChangeEvent>()
    .ToDictionary(e => e.Channel, e => e.ProgramNumber);
```

You'll get a dictionary where key is a channel and value is a program's number.

Thanks,
Max

**Comment by Achacu** [comment]
Yes, that's what I meant. I tried your solution and it works.

Thank you for the quick response :D
