### ISSUE TITLE
Add time offset for each notes during playback?

### ISSUE THREAD

**Issue by akira0245** [melanchall/drywetmidi#242]
Hello Melanchall,

Thank you for creating this wonderful MIDI library! I have a question about using the playback function. Is it possible to adjust the timing of note events while a playback is in progress? Specifically, if I have already created a playback and I want all notes with the metadata "track index 1" delay 50ms when playing, how should I achieve this?

**Comment by akira0245** [comment]
Just found out that I could use a MidiClock in my output device and queue midi events for later playing them in the Tick event. Only works for delaying but seems good enough as a workaround!

**Comment by melanchall** [comment]
Hi,

I suppose your workaround is good, because unfortunately there is no a way to change timing of objects within `Playback`. Interesting question, thanks!

**Comment by NomarCub** [comment]
Hi!
Could either of you please provide some code showing how this MidiClock workaround would work?

**Comment by melanchall** [comment]
Hi @NomarCub,

@akira0245 Can you please share your solution?

**Comment by melanchall** [comment]
:rocket: **8.0.0 version is released now!**

This version introduces the API to change playback on the fly. More info in the [Dynamic changes](https://melanchall.github.io/drywetmidi/articles/playback/Dynamic-changes.html) article. With this functionality you can do whatever you want with objects.
