### ISSUE TITLE
Generate drumming patterns

### ISSUE THREAD

**Issue by dan-vasilov** [melanchall/drywetmidi#243]
Is it possible to generate drumming patterns using this library? If so, could you suggest a starting point?

**Comment by dan-vasilov** [comment]
That's exactly what I needed, thank you! Could you give me a hint why does the code need to use channel 9 (I assume that's what the FourBitNumber is for)?

**Comment by melanchall** [comment]
As far as I know the channel `10` (`9` in terms of DryWetMIDI since channels are numbered from `0` in my library) is the percussion channel. So it'spossible that if you use another channel, you'll hear the piano, for example :) So it's recommended to use dedicated percussion channel.

**Comment by dan-vasilov** [comment]
That makes sense now - I was expecting the channel 10, as the documentation says. Thank you, that's all I needed to know.

**Comment by melanchall** [comment]
@dan-vasilov Can the issue be closed then?

**Comment by dan-vasilov** [comment]
I may have additional questions, would it be all right to close this one and open other issues to handle such questions? If so, let's close this issue.

**Comment by melanchall** [comment]
Well, let's continue within this one.

**Comment by dan-vasilov** [comment]
Is it possible to repeat a pattern? 
2. How do I combine multiple instruments in the same MIDI file?

**Comment by melanchall** [comment]
We can create a new pattern to repeat the previous short one:

```csharp
var longPattern = new PatternBuilder()
    .SetNoteLength(MusicalTimeSpan.Sixteenth)
    .Pattern(pattern)
    .Repeat(10)
    .Build();
```

But we need to change previous code a bit:

```csharp
var pattern = new PatternBuilder()
    .SetNoteLength(MusicalTimeSpan.Sixteenth)
    .Anchor("Start")

    .Anchor()
    .Note(bassDrum)
    .MoveToLastAnchor()
    .StepForward(MusicalTimeSpan.Half)
    .Repeat(4, 1)

    .MoveToLastAnchor("Start")
    .StepForward(MusicalTimeSpan.Quarter)

    .Anchor()
    .Note(snareDrum)
    .MoveToLastAnchor()
    .StepForward(MusicalTimeSpan.Half)
    .Repeat(4, 1)

    .MoveToLastAnchor("Start")

    .Note(hiHatDrum)
    .StepForward(MusicalTimeSpan.Sixteenth)
    .Repeat(2, 7)

    .Build();
```

We can't use `MoveToStart` because in `longPattern` this will cause jump to the start of the whole pattern and thus overriding all notes.

---

You can output a pattern to a track chunk and then combine them into a MIDI file:

```csharp
var pattern1 = new PatternBuilder()
    .ProgramChange(GeneralMidiProgram.BrightAcousticPiano)
    // ...
    .Build();

var pattern2 = new PatternBuilder()
    .ProgramChange(GeneralMidiProgram.Marimba)
    // ...
    .Build();

var tempoMap = TempoMap.Default;
var file = new MidiFile(
    pattern1.ToTrackChunk(tempoMap /* , channel */),
    pattern2.ToTrackChunk(tempoMap /* , channel  */),
    // ...);
```

**Comment by dan-vasilov** [comment]
That should be enough to get me started.
Thank you, again!
Let's close this issue.

**Comment by melanchall** [comment]
Just want to note that starting from **7.2.0** version you can use [piano roll](https://melanchall.github.io/drywetmidi/articles/composing/Pattern.html#piano-roll) feature which can help generate drum patterns faster.

**Comment by dan-vasilov** [comment]
Thank you, it's much appreciated!
