### ISSUE TITLE
Anytime I retrieve a device from InputDevice.GetByIndex() it returns a new instance of that device.

### ISSUE THREAD

**Issue by nickhudson4** [melanchall/drywetmidi#249]
```
IInputDevice device = InputDevice.GetByIndex(0);
IInputDevice device2 = InputDevice.GetByIndex(0);
bool equal = device == device2; // This is false
```

The main issue is now that device2 is basically useless as I cannot catch events from device2.EventReceived;

```
device.StartEventsListening();
device.EventReceived += OnMIDIEventReceived;
device2.EventReceived += OnMIDIEventReceived2;
```
The OnMIDIEventReceived2 handler will never catch the event. Only OnMIDIEventReceived will.

Note: I know this is a weird example, I am just trying to get a better understanding of what is going on.

**Comment by nickhudson4** [comment]
Is there a reason why it doesn't handle events properly for the second instance?

Our app allows the user to create "nodes" that act as MIDI senders/receivers. So the user has the full capability of creating multiple nodes referencing the same MIDI device. I guess I can add a wrapper around your InputDevice class to guarantee the same instance is always grabbed. Was just hoping there was a way around it.

**Comment by melanchall** [comment]
> Is there a reason why it doesn't handle events properly for the second instance?

Yes, there is a reason. Windows MIDI API :) You can work with MIDI devices exclusively only there. So you can't work with the same device in another code or program.

> I guess I can add a wrapper around your InputDevice class to guarantee the same instance is always grabbed

Yes, unfortunately you need to implement a way to cache devices by yourself.

**Comment by nickhudson4** [comment]
Okay. Thanks for the help!
