### ISSUE TITLE
How to send MMC Start event to DAW?

### ISSUE THREAD

**Issue by eriveraa** [melanchall/drywetmidi#25]
Hi Melanchall, 
Is there a way to send an MMC Start event to a DAW?. I want to send the Start (Play) to Cakewalk and Studio One. What event class should i use to do that?
Thanks in advance.

**Comment by melanchall** [comment]
Hi,

You should use `StartEvent` class. Please let me know if it works.

**Comment by eriveraa** [comment]
Hi, I have created and outputDevice bind to a virtual port. 
Cakework uses that virtual port as inputDevice.
I send StartEvent using outputDevice but nothing happens on Cakewalk. 
I do receive the Event Sent from outputDevice event handler.

**Comment by melanchall** [comment]
Oh, I didn't notice that you talk about MMC. MMC messages are just system exclusive ones. The library doesn't contain dedicated classes for MMC messages at now (but I already have it in my backlog), so you should use `NormalSysExEvent`. According to this article – [MIDI Machine Control](https://en.wikipedia.org/wiki/MIDI_Machine_Control) – Play message is:

```csharp
new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x06, 0x02, 0xF7 })
```

Please try to send this event and let me know if it works.

**Comment by eriveraa** [comment]
Just a quick question: On the internet i found that Start MMC is F0 7F 7F 06 06 F7.  Why don't you use F0?

**Comment by melanchall** [comment]
`F0` will be written automatically by `NormalSysExEvent`. In the Wikipedia article I don't see _Start_ message. `06` means _Record Strobe (AKA [[Punch in/out|Punch In]])_.

**Comment by melanchall** [comment]
@eriveraa Any news?

**Comment by melanchall** [comment]
@eriveraa I'm closing the issue. If you have new questions regarding this issue, reopen it.
