### ISSUE TITLE
Midi routing to multiple devices

### ISSUE THREAD

**Issue by eriveraa** [melanchall/drywetmidi#26]
Hi Melanchall: is it possible to send received midi events to multiple outputDevices? (Midi Routing) If so, could you provide an example or reference please?.
Thanks.

**Comment by melanchall** [comment]
Hi,

You can just open several output devices and call `SendEvent` method:

```csharp
var outputDevices = new[]
{
    OutputDevice.GetByName("Output Device 1"),
    OutputDevice.GetByName("Output Device 2"),
    OutputDevice.GetByName("Output Device 3")
};

//

var inputDevice = InputDevice.GetByName("Input Device");
inputDevice.StartEventsListening();
inputDevice.EventReceived += (sender, args) =>
{
    foreach (var outputDevice in outputDevices)
    {
        outputDevice.SendEvent(args.Event);
    }
};

//

inputDevice.Dispose();

foreach (var outputDevice in outputDevices)
{
    outputDevice.Dispose();
}
```

Also there is the `DeviceConnector` class which you can use to automatically redirect incoming events to another device. But I didn't test it with multiple devices.

```csharp
foreach (var outputDevice in outputDevices)
{
    var deviceConnector = inputDevice.Connect(outputDevice);
}
```

**Comment by eriveraa** [comment]
Hi, i will try the first aproach.
However, the second aproach (using DeviceConnector) does not working even with one to one. I created an input device and connected to a virtual port, and no luck. The automatic redirect is not working.
I am monitoring the virtual port, and no data was received. (the input device is working fine receiving events), but it looks like the DeviceConnector is not passing the events automatically.
Any ideas?

**Comment by melanchall** [comment]
I've created simple test which works on virtual MIDI ports:

```csharp
var inputDevice = InputDevice.GetByName("MIDI A");
var inputDeviceOutput = OutputDevice.GetByName("MIDI A");

var outputDevice = OutputDevice.GetByName("MIDI B");
var outputDeviceInput = InputDevice.GetByName("MIDI B");

var devicesConnector = inputDevice.Connect(outputDevice);

inputDevice.StartEventsListening();

outputDeviceInput.StartEventsListening();
outputDeviceInput.EventReceived += (sender, args) =>
{
    // Program falls into this place with Note On event
};

inputDeviceOutput.SendEvent(new NoteOnEvent());
```

**Comment by eriveraa** [comment]
Hi, i am trying to understand your code, but i dont get it how to adapt this code to this scenario:
- I have a external midi controller that would be an inputDevice. (This controller has only midi output port connected to computer, so it becomes inputDevice in your library - and does not apear as a output device).
- How do i connect this midi controller to 2 or more output virtual ports (so i can use the with other programs / daws).

**Comment by melanchall** [comment]
Hi,

Please try this code:

```csharp
var inputDevice = InputDevice.GetByName("MIDI Controller Name");

var outputDevice1 = OutputDevice.GetByName("MIDI Out 1");
var outputDevice2 = OutputDevice.GetByName("MIDI Out 2");

var devicesConnector1 = inputDevice.Connect(outputDevice1);
var devicesConnector2 = inputDevice.Connect(outputDevice2);

inputDevice.StartEventsListening();
```

But I think the second `Connect` will fail since an input device will be locked for use (`DevicesConnector` uses WinAPI `Connect` function and from my experience any such function locks device until it is released). But please try it. Also try connection with one output device. If it won't work, please use approach with manual events redirection since it definitely will work.

**Comment by eriveraa** [comment]
I have tried your code, unfortunately it doesn´t work even with just one output device. I think there is something wrong in the DeviceConnector.
I verified that i receive input events on inputDevice, however the deviceConnector is not handling the messages to the ouputDevice1.
How is the deviceConnector supposed to work?.
Waiting your response. Thanks!

**Comment by melanchall** [comment]
`DevicesConnector` is supposed to redirect events from input device to output one. At now it uses WinAPI [midiConnect](https://docs.microsoft.com/en-us/previous-versions//dd798446(v=vs.85)) function.

It seems it's difficult to make it work as expected in real scenarios. I'll try to get rid of `midiConnect` and do manual redirection since it's much more stable and also allows transfer incoming events to multiple output devices. Also it will give more flexibility in adjusting devices connections.

Thanks for reporting your use case and new ideas!

**Comment by eriveraa** [comment]
Ok melanchall.
So, should i wait for your fix? or is there any workaround to this scenario?

**Comment by melanchall** [comment]
Workaround is the approach I've suggested in my [first comment](https://github.com/melanchall/drywetmidi/issues/26#issuecomment-495925091).

**Comment by melanchall** [comment]
I've refactored `DevicesConnector` so it now doesn't use `midiConnect` function. Changes are in _develop_ branch.

**Comment by eriveraa** [comment]
Hi Melanchall, what does that mean exactly? The functionality is different now? What should I expect now?

**Comment by melanchall** [comment]
It's just refactoring. Purpose of the `DevicesConnector` and API are still unchanged.

**Comment by extdevx** [comment]
With last change you can write:

```csharp
var inputDevice = InputDevice.GetByName("MIDI In");

var outputDevice1 = OutputDevice.GetByName("MIDI Out 1");
var outputDevice2 = OutputDevice.GetByName("MIDI Out 2");

var devicesConnector = inputDevice.Connect(outputDevice1, outputDevice2);
inputDevice.StartEventsListening();
```

**Comment by melanchall** [comment]
With last change you can write:

```csharp
var inputDevice = InputDevice.GetByName("MIDI In");

var outputDevice1 = OutputDevice.GetByName("MIDI Out 1");
var outputDevice2 = OutputDevice.GetByName("MIDI Out 2");

var devicesConnector = inputDevice.Connect(outputDevice1, outputDevice2);

inputDevice.StartEventsListening();
```

After that all events from `inputDevice` will be redirected to `outputDevice1` and `outputDevice2`.

**Comment by melanchall** [comment]
@eriveraa I'm closing the issue. If you have new questions regarding this issue, reopen it.
