### ISSUE TITLE
Crash when running in Unity on M2 MacBook

### ISSUE THREAD

**Issue by akshayabd** [melanchall/drywetmidi#267]
Hi,

I'm using DryWetMIDI to process inputs from MIDI devices like an electric keyboard in a Unity project. I'm using the [Unity asset available](https://assetstore.unity.com/packages/tools/audio/drywetmidi-nativeless-228998) to do this.

Things work on a Windows machine, however when I try running on a MacBook it crashes fairly quickly with the following stacktrace:

```
NullReferenceException: Object reference not set to an instance of an object
Melanchall.DryWetMidi.Multimedia.InputDevice.OnMessage_Mac (System.IntPtr pktlist, System.IntPtr readProcRefCon, System.IntPtr srcConnRefCon) (at <aa425ed4de0e44068f897ec3718f60da>:0)
(wrapper native-to-managed) Melanchall.DryWetMidi.Multimedia.InputDevice.OnMessage_Mac(intptr,intptr,intptr)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnhandledExceptionHandler.bindings.cs:46)
```

I was wondering if you have encountered this before and if there is a solution for this?

I'm getting the connected device using the following code:

```cs
List<InputDevice> inputDevices = InputDevice.GetAll().ToList();
if (inputDevices.Count > 0)
{
      InputDevice _inputDevice = inputDevices.First();
      _inputDevice.EventReceived += OnEventReceived;
      _inputDevice.StartEventsListening();
}
```

Then I'm handling the events in a method with the signature:

```cs
private void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
{
}
```

If you need more information please let me know, I can perhaps create a minimal project and share it on GitHub.

**Comment by melanchall** [comment]
Hi,

Unfortunately I have no Apple devices, so I won't be able to do tests on my side. So I really need your help with the issue.

Well, first of all, download please the **ReceiveMidiData** utility for macOS from [here](https://artprodsu6weu.artifacts.visualstudio.com/Ada86e53e-02d0-42a7-ad86-d86986ae81da/d286d31e-d5f6-443f-b126-d81074c91872/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL01lbGFuY2hhbGwvcHJvamVjdElkL2QyODZkMzFlLWQ1ZjYtNDQzZi1iMTI2LWQ4MTA3NGM5MTg3Mi9idWlsZElkLzI3MjI4L2FydGlmYWN0TmFtZS9VdGlsaXR5LW9zeC14NjQ1/content?format=zip). Run it (in Terminal for example), select the same device and tell me please if the same error occurs.

Also what if you try to receive data from another MIDI device? Do you see the same error?

Thanks,
Max

**Comment by melanchall** [comment]
Oh wait, I've just noticed a problem in your code:

```csharp
if (inputDevices.Count > 0)
{
      InputDevice _inputDevice = inputDevices.First();
```

You create **local** variable here which will be collected by GC when the method exits. So in `OnEventReceived` the `_inputDevice` is probably deleted. You need to declare `_inputDevice` as a class field, not as a local variable. And I suppose the problem will gone. See an example here: https://melanchall.github.io/drywetmidi/articles/devices/Input-device.html.

**Comment by akshayabd** [comment]
Ah such a silly mistake - thanks for pointing that out!

Confirmed when I use a class field the issue doesn't occur. Odd it worked on Windows, maybe the GC behavior is different there.
