### ISSUE TITLE
Unity cannot exit after use

### ISSUE THREAD

**Issue by ZengRunMing** [melanchall/drywetmidi#276]
Hello, I am playing Midi files on Unity using DryWetMidi version 7.0.1.

A problem occurred. When calling Application. Quit() or closing the Unity editor after playing the Midi file, the program cannot exit. The specific situation is that the task manager displays no response, and the program can be closed only after the task manager ends the task.

**Comment by melanchall** [comment]
Hi,

Please read this first – https://melanchall.github.io/drywetmidi/articles/dev/Support.html. At least, provide your code. How you setup a file's playback, how you dispose devices and playback and so on.

**Comment by ZengRunMing** [comment]
The core code is as follows (Github does not allow files with the suffix cs)
[MidiControl.txt](https://github.com/melanchall/drywetmidi/files/12840770/MidiControl.txt)

**Comment by melanchall** [comment]
1. Are you sure you properly dispose all the DryWetMIDI API when exiting Unity? Can you show where you call disposing methods?
2. What if you comment input device creation? Is Unity still hang on exit?
3. What if you comment playback creation? Is Unity still hang on exit?

**Comment by ZengRunMing** [comment]
The processing code is as follows
MCL is MidiControl
PB is Playback
MDO is OutputDevice

private void OnApplicationQuit()
{
	if (MCL != null && MCL[0] != null)
	{
		MCL[0].DisposeMidiOutDevice(PB, MDO);
		MCL[0].DisposeMidiInDevice(MDI);
	}
	MDO.Dispose();
	PB.Dispose();
}

**Comment by melanchall** [comment]
* You've answered only one question from three.
* Looks like you haven't read the article I've mentioned above – https://melanchall.github.io/drywetmidi/articles/dev/Support.html. Here you can see **point 7**. It's pretty hard to read code without proper formatting.

In addition to two question you didn't provide answers on (I **still** need answers), I have a couple of new ones.

> MCL is MidiControl
> MCL[0]

How you can use `[0]` on the `MidiControl` class? There is no indexers within the class or you didn't show it. I see in your previously sent file and can't understand how you can use the `[0]` syntax on `MidiControl`. Maybe `MCL` is a **collection** of `MidiControl` instances? If yes, why `MCL[0]`? There is **always** only one item in the `MCL`? Where you dispose `MCL[1]`, `MCL[2]` and so on?

Can you set breakpoint on `OnApplicationQuit` and confirm it's called before Unity hangs?

**Comment by ZengRunMing** [comment]
I can exit the program when I only use Input or Output, but as long as PlayBack is used, I cannot exit the program.

MCL is a collection of MidiControl arrays, currently only the first one is valid, and none of the others are instantiated.
I confirm that the program was called before exiting.

**Comment by ZengRunMing** [comment]
When I only use 'input and output', I can exit the program, but as long as I use 'playback', I cannot exit the program.
MCL is a collection of MidiControl arrays, currently only MCL [0] is valid, and other array objects are not instantiated.
I confirm that all object handling codes in the above code have been called before the program exits.

**Comment by melanchall** [comment]
Hmm, well, what if you change this code:

```csharp
Playback playback = MF.GetPlayback();
```

to this one:

```csharp
Playback playback = MF.GetPlayback(new PlaybackSettings
{
    ClockSettings = new MidiClockSettings
    {
        CreateTickGeneratorCallback = () => new RegularPrecisionTickGenerator()
    }
});
```

Does the Unity exit correctly now?

Also please say what version of Unity do you use?

**Comment by ZengRunMing** [comment]
Problem solved, Unity can exit now

The version used is 2023.3.171f1c1

**Comment by melanchall** [comment]
@ZengRunMing  Can you please say, what helped? `RegularPrecisionTickGenerator`?

**Comment by ZengRunMing** [comment]
Modified to the following code, Unity can now exit
```C#
Playback playback = MF.GetPlayback(new PlaybackSettings
{
    ClockSettings = new MidiClockSettings
    {
        CreateTickGeneratorCallback = () => new RegularPrecisionTickGenerator()
    }
});
```

**Comment by ZengRunMing** [comment]
According to the code you provided, MidiControl has been modified and Unity can now exit normally
···C#
Playback playback = MF.GetPlayback(new PlaybackSettings
{
    ClockSettings = new MidiClockSettings
    {
        CreateTickGeneratorCallback = () => new RegularPrecisionTickGenerator()
    }
});
```

**Comment by ZengRunMing** [comment]
According to the code you provided, MidiControl has been modified and Unity can now exit normally
```C#
Playback playback = MF.GetPlayback(new PlaybackSettings
{
ClockSettings = new MidiClockSettings
{
CreateTickGeneratorCallback = () => new RegularPrecisionTickGenerator()
}
});
```
