### ISSUE TITLE
MidiClock sync problem

### ISSUE THREAD

**Issue by noonesimg** [melanchall/drywetmidi#277]
Hey, I've been trying out different midi libraries, so far this one seems to have the best API design.

The only problem I had so far is syncing my c# application with a DAW (Ableton)

I'm trying to utilize the `MidiClock` class
Here's a snippet:
```c#
var device = OutputDevice.GetByName(deviceName);

var bpm = 120.0;
var pulsesPerSecond = bpm * 24.0 / 60.0;
var tickIntervalMs = 1000.0 / pulsesPerSecond;
var clock = new MidiClock(
    true,
    new HighPrecisionTickGenerator(), 
    TimeSpan.FromMilliseconds(tickIntervalMs)
);

clock.Ticked += (s, e) =>
{
    device.SendEvent(new TimingClockEvent());
};

clock.Start();
device.SendEvent(new StartEvent());

Task.Delay(60000).Wait();

device.SendEvent(new StopEvent());
```

The actual bpm I get as reported by the DAW is 125.
I can't figure out where the problem is:
Am I using the MidiClock in a wrong way?
Is there a problem with how I am calculating the tickInterval?

**Comment by noonesimg** [comment]
After tinkering with it for some time, It seems like the minimum `tickIntervalMs` difference to have an effect on the clock is 1ms.

**Comment by noonesimg** [comment]
I ended up hacking together a simple example
using `MicroStopwatch` class from [this code project](https://www.codeproject.com/Articles/98346/Microsecond-and-Millisecond-NET-Timer) for convenience

```c#
public class MicroStopwatch : System.Diagnostics.Stopwatch
{
    readonly double _microSecPerTick =
        1000000D / System.Diagnostics.Stopwatch.Frequency;

    public MicroStopwatch()
    {
        if (!System.Diagnostics.Stopwatch.IsHighResolution)
        {
            throw new Exception("On this system the high-resolution " +
                                "performance counter is not available");
        }
    }

    public long ElapsedMicroseconds
    {
        get
        {
            return (long)(ElapsedTicks * _microSecPerTick);
        }
    }
}
```


here's the time keeping part:

```c#
MicroStopwatch stopwatch = new MicroStopwatch();
stopwatch.Start();

long elapsedMicroseconds = 0;
long nextNotification = 0;

var bpm = 120;
var interval = Tempo.FromBeatsPerMinute(bpm).MicrosecondsPerQuarterNote / 24;
bool running = true;

Task.Run(() =>
{
    while (running)
    {
        nextNotification += interval;
        while ((elapsedMicroseconds = stopwatch.ElapsedMicroseconds) < nextNotification)
            Task.Delay(TimeSpan.FromMilliseconds(1)).Wait();

        device.SendEvent(new TimingClockEvent());
    }
});
```

This works better than I've expected. Allowing me to precisely dial in the bpm.
I'm not quite sure what's the problem with `MidiClock`, hope this might help to investigate.

**Comment by melanchall** [comment]
Hi,

First of all, `MidiClock` in conjunction with `HighPrecisionTickGenerator` will tick exactly with the specified intervals. Drift is possible, since neither Windows nor macOS are real-time systems, but that drift is not critical. Unfortunately I don't know why `MidiClock` doesn't work :-(

Your solution is a possible one and something like that is present as an example of custom tick generator in the library docs: https://melanchall.github.io/drywetmidi/articles/playback/Tick-generator.html#custom-tick-generator. But be aware that this code:

```csharp
Task.Delay(TimeSpan.FromMilliseconds(1)).Wait();
```

won't give you `1` ms delay since the minimum possible delay in Windows is `15.6` ms.

**Comment by noonesimg** [comment]
Sure, like I've said, my problem was resolution rather than drift (as it's expected on a non real-time OS).
It seems as if `MidiClock` doesn't differentiate between

```c#
var clock = new MidiClock(
    true,
    new HighPrecisionTickGenerator(), 
    TimeSpan.FromMilliseconds(20)
);
```

and 

```c#
var clock = new MidiClock(
    true,
    new HighPrecisionTickGenerator(), 
    TimeSpan.FromMilliseconds(20.8)
);
```

the actual ticks will occur with the same interval for me in both cases, 
(I've tested this on two windows PCs)

**Comment by noonesimg** [comment]
Going over the source code brought a bit more clarity, given the implementation of the `HighPrecisionTickGenerator` it really doesn't care about fractions of milliseconds. Thanks for the link, I somehow missed that in the Docs, I think I'm just going to implement a custom tick generator for my specific purpose. 
I guess I've expected that to work out of the box coming more from a live midi sequencing perspective rather than processing midi files.

P.S. Thanks for this library!
Keep up the good work

**Comment by melanchall** [comment]
@noonesimg Oh, got it now! Thanks for the clarification.
