### ISSUE TITLE
MIDI File returns error: InvalidMetaEventParameterValueException

### ISSUE THREAD

**Issue by pabloleban** [melanchall/drywetmidi#285]
When trying to load this midi file I get: 
`InvalidMetaEventParameterValueException: 255 is invalid value for the Scale property of a meta event of KeySignature type.`

[El_rey_leon_The_circle_of_life.zip](https://github.com/melanchall/drywetmidi/files/13969786/El_rey_leon_The_circle_of_life.zip)

However if I load the midi file on FL Studio, it works fine.

**Comment by melanchall** [comment]
Hi,

The file is pretty strange. It has four track chunks at the end with just a single event - _Key Signature_ one. This event violates MIDI file spec. `255` is invalid value for the scale byte which can be either `0` or `1`. So DryWetMIDI throws the error by default informing you that the file is invalid at some part.

But DryWetMIDI has a reach set of reading options. Just use this code:

```csharp
var midiFile = MidiFile.Read(
    "El_rey_leon_The_circle_of_life.mid",
    new ReadingSettings
    {
        InvalidMetaEventParameterValuePolicy = InvalidMetaEventParameterValuePolicy.SnapToLimits
    });
```

and the file will be read successfully. I suppose FL just ignores the error.

Thanks,
Max
