### ISSUE TITLE
Skipping notes

### ISSUE THREAD

**Issue by AldeRoberge** [melanchall/drywetmidi#297]
Very basic notes :

![image](https://github.com/melanchall/drywetmidi/assets/4276275/60cfd603-d361-4b0b-89cb-3c5d7aecb909)

Exported :

![image](https://github.com/melanchall/drywetmidi/assets/4276275/0686f71d-c5ed-48b3-9a91-e32983c30ca3)

Read : 

```csharp

using Melanchall.DryWetMidi.Core;
using Melanchall.DryWetMidi.Multimedia;
using Melanchall.DryWetMidi.MusicTheory;

namespace SongActor.Runtime;

public class SongActor
{
    public void PlaySong(string midiFilePath)
    {
                var midiFile = MidiFile.Read(path);

                using var outputDevice = new OutputDevice(track);
                using var playback = midiFile.GetPlayback(outputDevice);
                
                playback.Play();
        }
    }

    private class OutputDevice(Track track) : IOutputDevice
    {
        public event EventHandler<MidiEventSentEventArgs>? EventSent;

        private readonly Track _track = track;

        public void Dispose()
        {
        }

        public void PrepareForEventsSending()
        {
        }

        public void SendEvent(MidiEvent midiEvent)
        {
            // Send the MIDI event to the output device
            Console.WriteLine($"Sending MIDI event: {midiEvent} for track '{_track.Name}'.");
        }
    }
}
```

But for some reason, the first key I receive is F5 :

![image](https://github.com/melanchall/drywetmidi/assets/4276275/74607f04-e7b8-4e70-88ae-790d9cd65c21)

And then it keeps skipping more notes.

![image](https://github.com/melanchall/drywetmidi/assets/4276275/bee27e77-3e21-4adb-bacd-a282331d76d1)

Notice there are no F5 notes in my midi file. For some reason, Ableton is 1 octave lower than what drywetmidi says it is.

At this point, I do not care much for an octave discrepancy, I just want to see all notes print in the console.
[Dialogue.mid.txt](https://github.com/user-attachments/files/15529947/Dialogue.mid.txt)

Here is the .mid file attached, remove the .txt extension

I'm starting to think Ableton might be the culprit, its MIDI support is subpar, and I'm not happy with its limitation to only be able to export single tracks midi files ('version 0'). I will test tomorrow and try with a fresh confirmed working .mid file, and see if it has the same problem.

**Comment by melanchall** [comment]
Hello,

> But for some reason, the first key I receive is F5

What is _"key"_? I don't see instructions in your code that print lines like _"Key: N"_.

> For some reason, Ableton is 1 octave lower than what drywetmidi says it is.

DWM uses the convention: **note number 60 = C4**. Other software may use another convention. That's OK, because MIDI specification doesn't specify a strict rule for that.

I sure DWM reads the file (and plays it) as is, without any corruptions. So yes, I think the problem is with Ableton.

**Comment by melanchall** [comment]
@AldeRoberge Any news?

**Comment by AldeRoberge** [comment]
Hey, I'll get back to you asap. Sorry for the delay, I have to get this fixed pretty soon.

**Comment by melanchall** [comment]
@AldeRoberge Can the issue be closed?

**Comment by AldeRoberge** [comment]
Hello, yes let's mark it as closed and I'll update with further information. I acquired FL Studio to attempt a fix for the error, which DWM is probably not the cause!

Thanks for your time and great product.
