### ISSUE TITLE
How to use on Unity 2017?

### ISSUE THREAD

**Issue by FabioZumbi12** [melanchall/drywetmidi#3]
Hi,
Sorry but this is not an issue, but i want to use this library on a Unity project but i dont know how. Do you know if is possible, and how to use?

I found other midi readers but what i want its only a midi file reader, i dont want to play.

Thanks!

**Comment by melanchall** [comment]
Hi,

You can try to download the project sources, copy them to your Unity solution and build it. There is the one file in the library code that, I think, will not be compiled – [DryWetMidi/Smf/Utilities/IOUtilities.cs](https://github.com/melanchall/drywetmidi/blob/develop/DryWetMidi/Smf/Utilities/IOUtilities.cs) – since it uses WinAPI functions. To compile this file you need to eliminate WinAPI calls. Or I can prepare "good" file for you.

Let me know how integration the library into your project is going.

Max

**Comment by FabioZumbi12** [comment]
Great, thanks to fast response!!

I have downloaded the source and imported the folder into my project. With this i can use some classes like MidiFile, but what i want its only get all notes on/off and the timesample of each note to i iterate bteween notes. You know a good way to this?
And seems some options from your examples is not available for. Its because i using C#?

Something like this: 
```
midiFile.GetTempoMap();
midiFile.GetTimedEvents();
```


(i still lookin into your wiki)

**Comment by melanchall** [comment]
Please clarify what do you need. You want to print track names and events?

There is no such thing like _name of track_ in a MIDI file. But track chunk can contain _Sequence/Track Name_ event. To get it you can use this code:

```csharp
var trackName = trackChunk.Events
                          .OfType<SequenceTrackNameEvent>()
                          .FirstOrDefault()
                          ?.Text;
```

All events override `ToString` so output should be nice.

You said that you want to get notes with timestamps. You can use this code:

```csharp
IEnumerable<Note> notes = midiFile.GetNotes();
```

`Note` class has `Time` property which is what you need.

**Comment by FabioZumbi12** [comment]
Ohh man, it worked!

I needed to import classes "System.Linq" and "Melanchall.DryWetMidi.Smf.Interaction" to allow me to use `GetNotes()` and `OfType`.

 Thaaank you for help for now.

**Comment by melanchall** [comment]
You are welcome :)

Feel free to open new issues if you have any questions about the library.

**Comment by FabioZumbi12** [comment]
Hi,
Me again.
Just a little question. I did not found the note time equivalent to PCM timesamples to sync with Unity AudioSources. I can use seconds, but is not precise and Unity source only give me pcm samples and seconds.
Can you give me a tip about this?

**Comment by melanchall** [comment]
Hi,

You can try to operate by seconds. To get note's time in this format use this code:

```csharp
var tempoMap = midiFile.GetTempoMap();
var metricTime = note.TimeAs<MetricTimeSpan>(tempoMap);
```

Now you have note's time as an instance of the `MetricTimeSpan` class. Underlying measure of this class is number of microseconds. To access this value use the `TotalMicroseconds` property of the `MetricTimeSpan`.

You can also convert PCM sample number to microseconds too knowing sample rate of your audio. I think number of microseconds is the most accurate measure in your case.

**Comment by FabioZumbi12** [comment]
Hi,
Thanks and i using this way you suggested but after some time breaking my head i see this metric time only give me a limited time. As example:

`var metricTime = note.TimeAs<MetricTimeSpan>(tempoMap);`

Using `metricTime.Seconds` only get a number 0 - 59, and not minutes and hours represented as seconds, only seconds until one minute, then get back to 0 where the correct should be 60, 61, 62...

Is this intentional?

The same with milliseconds, when we have on second in milliseconds, back to 0.

**Comment by melanchall** [comment]
Hi,

It is done intentionally that `Hours` returns number 0-23, `Minutes` and `Seconds` return number 0-59. Good suggestion to add properties like `TotalSeconds`, `TotalMinutes` and so on. Thank you :)

`note.TimedNoteOnEvent.TimeAs<MetricTimeSpan>(tempo).TotalMicroseconds` is totally equivalent to `note.TimeAs<MetricTimeSpan>(tempo).TotalMicroseconds` and I recommend to use the last one.

**Comment by mherbold** [comment]
Hello - Google search led me here to answer a similar question of mine, but GetNotes is apparently no longer a method of MidiFile.  What is the current way to do this?

**Comment by melanchall** [comment]
Hi,

[`GetNotes`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Interaction.NotesManagingUtilities.html#Melanchall_DryWetMidi_Interaction_NotesManagingUtilities_GetNotes_Melanchall_DryWetMidi_Core_MidiFile_) is an extension method for `MidiFile`. You need to add

```csharp
using Melanchall.DryWetMidi.Interaction;
```

at the top of a class file in order to be able to use the method.

**Comment by mherbold** [comment]
Thanks for the quick reply!  *facepalm*  I should have been able to figure that one out without bugging you - sorry!

I'm now actually using trackChunk.GetNotes() instead, inside my track chunks loop.  Mentioning it here so others can find this as well.  Thank you!

**Comment by melanchall** [comment]
:rocket: Official [DryWetMIDI asset][1] has been released in Unity Asset Store so now you can use standard Unity ways to integrate the library. More info in the [Using in Unity][2] article.


  [1]: https://assetstore.unity.com/packages/tools/audio/drywetmidi-222171
  [2]: https://melanchall.github.io/drywetmidi/articles/dev/Using-in-Unity.html
