### ISSUE TITLE
Compatibility with Mono

### ISSUE THREAD

**Issue by eriveraa** [melanchall/drywetmidi#30]
Hi melanchall,
I would like to know if drywetmidi is compatible with Mono. I need to know this because i want to compile my .net application (which uses drywetmidi) with mono in order to run on macos and linux.
Waiting for your kindly response.
Eduardo.

**Comment by melanchall** [comment]
Hi Eduardo,

The code of the library is compatible with Mono, **BUT** devices API is Windows only at now. If you need only API for working with MIDI files, there will be no any problems to use the library on any platform Mono supports.

Max
