### ISSUE TITLE
Fractional Beats?

### ISSUE THREAD

**Issue by ronnieoverby** [melanchall/drywetmidi#32]
First… amazing library! Thank you, very much.

I want to use `drywetmidi` to playback midi events. It seems that my source event times and lengths are not quite compatible with yours.

For example, my program is generating midi events with the following structure:

```C#
struct Event<T>
{
	public int RelativeBar { get; set; }
	public double Position { get; set; }
	public double Length { get; set; }
	public T Data { get; set; }
}
```

`RelativeBar`: Simply the bar that an event starts.
`Position`: The beat that an event starts. `1` would mean first beat. `2.5` would mean halfway before between 2nd and 3rd beat.
`Length`: The duration of the event in beats. '1.33' would mean roughly 1 + 1/3 beats.

You can see that I'm representing the number of beats as a `double` where the value represents `{Beats}.{Cents}`. I borrowed this system directly from my favorite DAW, Reaper:

![image](https://user-images.githubusercontent.com/101028/63803824-be754a80-c8e3-11e9-9282-84b08eccf37b.png)

It doesn't seem that `BarBeatTimeSpan` offers parity with this representation. It has `Bars/Beats/Ticks`. `Beats` is an whole number and `Ticks` seems to store an additional `MidiTimeSpan` value that doesn't really have anything to do with bars/beats.

I'm sure that I can do the math on my own to convert my fractional beats to your `ITimeSpan` but I wanted to go ahead and ask you if I was missing something in the library that handles this for me.

Thanks for your help!

**Comment by melanchall** [comment]
Hi,

Thanks for using the library!

I took **Bar.Beat.Ticks** notation from Cubase (another DAW like Reaper). Also it allows to set time and length as accurately as possible. `double` can lead to rounding errors on conversion to ticks (which is required since all timestamps stored as integer numbers inside a MIDI file).

Your code is good. I already have plans to expose utilities to get bar/beat length in MIDI ticks so users can easily perform such conversions. It seems I should increase priority of this task :) I'll implement this utilities within this issue so please don't close it.

**Comment by melanchall** [comment]
I've added `BarBeatTimeSpanUtilities` with `GetBarLength` and `GetBeatLength` methods which allow to rewrite your method:

```csharp
long Convert(int bar, double beats, TempoMap tempoMap)
{
    var barPart = TimeConverter.ConvertFrom(new BarBeatTimeSpan(bar), tempoMap);
    var beatsPart = BarBeatTimeSpanUtilities.GetBeatLength(bar, tempoMap) * beats;
    return barPart + (long)Math.Round(beatsPart);
}
```

New API is in develop branch so if you want to try it right now you can build the library from sources.

Also I'm thinking on providing customizable beat division so it can be ticks or cents.

**Comment by melanchall** [comment]
@ronnieoverby I've added new time span class – `BarBeatCentsTimeSpan`. Cents is a `double` number from `0` to `100`. So you can throw away your conversion and work with this new class :)

`BarBeatCentsTimeSpan` is in _develop_ branch so if you want to try it right now you can build the library from sources.

**Comment by melanchall** [comment]
@ronnieoverby Did you try new time span class?

**Comment by ronnieoverby** [comment]
Not yet,  though I'm excited about it. I'll try it today and let you know.
Thanks!

**Comment by melanchall** [comment]
@ronnieoverby Any news? :)

**Comment by ronnieoverby** [comment]
Seems to work, but I did run into a argument range exception with `cents`. 

I would prefer if `BarBeatCentsTimeSpan` didn't have a `Cents` property, but instead had a `double Beats` property, that could represent both the beat and the cents with one value.

**Comment by melanchall** [comment]
OK, I'll think on combining beats and cents together. The problem is how to name the time span class :)

**Comment by ronnieoverby** [comment]
Why should the name change? It still has the same purpose and advantages,
irrespective of its implementation.

**Comment by melanchall** [comment]
Current name implies there is a cents part of the time span. But for double beat there is no this part. It's just bar and fractional beat. Cent is a hundredth part (like percent). But fractional part of a beat is not.

There is a classical programming joke: _There are two hard things in computer science: cache invalidation, **naming things**, and off-by-one errors._ :)

Maybe `BarBeatFractionTimeSpan` is a good name?

**Comment by ronnieoverby** [comment]
You're right. Cents != fractional beat. I guess that name is as good as any.

**Comment by melanchall** [comment]
I've changed `BarBeatCentsTimeSpan` to `BarBeatFractionTimeSpan` with `Bars` and `Beats` properties where `Beats` are `double`.

@ronnieoverby Please check this new API and close the issue if you're happy with it.

**Comment by ronnieoverby** [comment]
That change suits my purposes perfectly. I'm very grateful that you were so considerate of what I was trying to accomplish.
