### ISSUE TITLE
Problem with "Shift Events"

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#37]
If a chunk has - as the first entry - not a channel-event (e.g. trackname), then the Playback funktionality does not use the shifted time.

I think not the first entry should be used for the "Shift Event", Maybe the first channel-event should be shifted.

**Comment by melanchall** [comment]
Yes, I confirm the issue. It's caused by filtering meta events before collecting events for playback. I'll fix it today.

Thanks for pointing out to the bug!

**Comment by melanchall** [comment]
I've fixed the issue in _develop_ branch.

**Comment by FischertBilligheim** [comment]
Thanks a lot, Max.
