### ISSUE TITLE
Convert Format-0 to Format-1

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#38]
How can I convert a Format-0 Chunk to several Chunks - splitted by the midi-channel?

I created this Code, but I assume this can be realized in a much bettre way:

           // Create an array with 16 entries
            var timedEvents = FourBitNumber.Values.Select(channel => new List<ChannelEvent>()).ToArray();
                
                foreach (TrackChunk track in gMidiFile.GetTrackChunks())
                {
                long lTime = 0;

                    foreach (MidiEvent ev in track.Events)
                    {
                    lTime += ev.DeltaTime;

                        if (ev is ChannelEvent)
                        {
                            ev.DeltaTime = lTime;    // Use absolute times to split
                            timedEvents[((ChannelEvent)ev).Channel].Add((ChannelEvent)ev);
                        }
                    }

                track.Events.RemoveAll(ev => ev is ChannelEvent);
            }

            TrackChunk[] tcarray = new TrackChunk[16];

            int index = 0;

            for (int i = 0; i < 16; i++)
            {
                //---------------------------------------------
                //Change the absolute times back to delta-time
                //---------------------------------------------
                ChannelEvent[] cev = (ChannelEvent[]) timedEvents[i].ToArray();

                if (cev.Length == 0)
                    continue;
                //------------------------------------------
                // calculate deltas
                //------------------------------------------
                long[] deltas = new long[cev.Length];
                deltas[0] = cev[0].DeltaTime;

                for (int j = 1; j < cev.Length; j++)
                    deltas[j] = cev[j].DeltaTime - cev[j - 1].DeltaTime;

                //------------------------------------------
                // copy deltas to events
                //------------------------------------------
                for (int k = 0; k < cev.Length; k++)
                      cev[k].DeltaTime = deltas[k];

                // Create a new TrackChunk with the events
                tcarray[index] = new TrackChunk(timedEvents[i]);
                index++;
            }

            gMidiFile.Chunks.AddRange(tcarray);

**Comment by melanchall** [comment]
You can do it with this simple code:

```csharp
var trackChunks = trackChunk.Explode();
```

**Comment by FischertBilligheim** [comment]
Thanks a lot, Max.
