### ISSUE TITLE
Mute Midi-Channels while playback is running

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#39]
How can I mute/unmute midi-channels, while the Playback is running?

**Comment by melanchall** [comment]
If you use release version of the library, there is no way to do this. But you can take develop sources and then you can use `EventCallback` and `NoteCallback` properties of the `Playback` class to set callbacks to filter out those events and notes with muted channels.

```csharp
playback.NoteCallback = (d, rt, rl, t) => mutedChannels.Contains(d.Channel) ? null : d;

playback.EventCallback = (e, rt, t) =>
{
    var channelEvent = e as ChannelEvent;
    if (channelEvent == null)
        return e;

    return mutedChannels.Contains(channelEvent.Channel) ? null : e;
};
```

**Comment by FischertBilligheim** [comment]
Hello melanchall,

Thanks really a lot for your fast response to my 3 issues!!
And thanks really a lot for your great work and the possibility to use „DryWetMidi“!!

With best regards
Thomas

**Comment by melanchall** [comment]
Thomas,

You are welcome! :) Thanks for using the library. Please close issues if they are resolved.

**Comment by FischertBilligheim** [comment]
Thanks a lot, Max.

**Comment by FischertBilligheim** [comment]
I have one additional comment or proposal:
I locally changed the source of "Playback.cs" and added a new property with an Array of bool - for every midi channel ("channelEnabled[16]") to mute or Play.

In "TryPlayNoteEvent " I changed a small part of Code:

            if (midiEvent != null)
            {
                // TF: Realize "Mute"
                if (midiEvent is NoteOnEvent)
                {
                    int channel = ((NoteOnEvent)midiEvent).Channel;

                    if (channelEnabled[channel])
                        SendEvent(midiEvent);
                }
                else
                    SendEvent(midiEvent);

That's simpler and faster than using events.....

**Comment by FischertBilligheim** [comment]
![Mixer](https://user-images.githubusercontent.com/20623089/67127663-19e3fa80-f1fa-11e9-98d9-eec5a2290fd4.PNG)
This is the current status of the mixer with mute and solo-buttons...

**Comment by melanchall** [comment]
Hi Thomas,

Hmm, it seems reasonable to implement this feature. I'll do it :)

Your implementation slightly incomplete since there are other channel events except `NoteOn`. You should check if an event is an instance of `ChannelEvent`.

**Comment by FischertBilligheim** [comment]
Hi Max,
Important is, that the mute/solo can be used while the midi-file is playing.
If you are now muting a channel - and the note-off will not send anymore - you have not the expected behaviour... :-) 
(Another situation: a program change event is not sent, and the channel is switched on again....)

Because of that I think Note_On seems to be ok for muting....

Regards
Thomas

**Comment by FischertBilligheim** [comment]
Hi Max, 
I never worked in a Github-Repository....
Would you generally accept proposals for changes from others than you?
I copied the Developer-Repository to my machine - and did locally changes. 
How can you see my proposal - and accept or reject?

Greetings
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

Recently I've merged PR from @zivillian (#36). So yes, I accept changes from users :)
To create PR you need to fork my repo, push your changes to your fork and create PR from your branch to the _develop_ branch of my repo.

But array of `bool`s is not good. Index should be of type `FourBitNumber` and the check for out of range should exist. I think it would be better to create methods like `MuteChannel`/`UnmuteChannel`/`IsChannelMuted` with all required checks and proper arguments types.

Please do PR and we'll discuss it :)

**Comment by FischertBilligheim** [comment]
PR was created - issue can be closed… :-)

**Comment by melanchall** [comment]
I reopen the issue. Please clarify your requirement according to your last comment on #45.

Do you in fact mute channels on TrackChunk instead of Playback? What does it mean? There is no concept of muting on track chunk level since MIDI spec hasn't such thing.

**Comment by FischertBilligheim** [comment]
As I mentioned in the PR: It‘s fine and sufficient for me to have the mute functionality on the level of midi Channels.
What I‘m currently implementing is a midi- editor inclusive midi-Sequenzer functionality. The base of all sequencers is typically a track - you call it track-chunk. So if the sequencer plays all tracks - and these can be more than 16, even the Midi-Standard supports only 16 Channels(Devices) - it would be a good thing to be able to mute these tracks.... A typical example can be the drum-tracks, for which all drum parts can be splittet - the base-drum on a track, the HiHat on a separate track etc. Nevertheless all tracks are using midi-channel 10... It would be helpful to mute the base-drum, but to mute the drums on channel 10 is currently sufficient for me...

**Comment by melanchall** [comment]
Well, I've investigated efforts needed for this task and it seems new class `Sequencer` should be implemented. But I'm going to create such class in one of new versions of the library in the future. At now I recommend to use approach suggested in my [first reply](https://github.com/melanchall/drywetmidi/issues/39#issuecomment-537921690).

Thanks for using the library and for sharing your experience!

**Comment by FischertBilligheim** [comment]
Ooh - that means my simple solution for the Midi-Channels will not be integrated and also not your method-call solution ?

**Comment by melanchall** [comment]
It's just unncecessary since there is a way to achieve what you want (and it's not so complex as you think). You just need to manage array of bools on your side. Also you can easily replace all array at once and callbacks will use new array automatically.

Also inside callback you can check what track note or event belongs to and mute/unmute it. So you can arrange your data into logical tracks, not by channels.

**Comment by NomarCub** [comment]
Hi!
What do you think the best way to mute channels or the whole playback is, as of now?
I can't really figure out the final solution from your conversation. I've been looking for this functionality on playback, outputdevice, channel, and other interfaces.

**Comment by melanchall** [comment]
Hi @NomarCub,

My first [comment](https://github.com/melanchall/drywetmidi/issues/39#issuecomment-537921690) is what you need. There is nothing tricky there, so I hope you understand the approach. Also please read the library [docs](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html).
