### ISSUE TITLE
[Question/Suggestion]How to/Add playing to check change

### ISSUE THREAD

**Issue by Flithor** [melanchall/drywetmidi#4]
I've found drywebmidi just use to read & write midi file, but must to save the file before checking the music change.
Is it have a way to playing fragment?
If not, I suggest add it.

**Comment by melanchall** [comment]
Hi @Flithor,

Thank you for using the DryWetMIDI. At now there is no way to play a MIDI file with the library. Concept of the library is to provide reading, writing and creating MIDI files. Sound generation is not supposed to be a part of it.

But you are not the one who requesting this feature so I'll think about it again. Thanks for suggestion :)

Max

**Comment by melanchall** [comment]
Hmm, it seems that playing a MIDI file (especially not saved) doesn't fit the DryWetMIDI concept. There are other libraries that provide sound generation for MIDI files so I recommend to use them.
