### ISSUE TITLE
How can I simply transpose all notes of a midi-file, but NOT the Drums?

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#40]

**Comment by melanchall** [comment]
Usually drums are placed on channel 10. So we should transpose notes on channels other than 10. You can do it with this code:

```csharp
// Number of halftones to transpose by
var transposeBy = (SevenBitNumber)20;

var midiFile = MidiFile.Read("file.mid");
midiFile.ProcessNotes(
    n => n.NoteNumber += transposeBy,
    n => n.Channel != (FourBitNumber)9);

midiFile.Write("transposed file.mid");
```

You should use 9 since channel number is 0-based in the DryWetMIDI.

**Comment by FischertBilligheim** [comment]
OMG - it's so easy....   :-)
But:
With that Code, it's not possible to transpose down - I think in that case, I have to differ and use "n => n.NoteNumber -= transposeBy"...
Thanks a lot!
Best regards
Thomas
