### ISSUE TITLE
How can I append one midi-file to another?

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#42]
I would like to append one midi file to another.
I did the following:
I opened the first file (multiple tracks)
I opened the second file (multiple tracks)  - and changed the beginning of all tracks to the end of the first midi file.
I added then all tracks of file2 to file1.

That seems not be sufficiant. Do I have to recalculate all delta-times of file2 with the „ticks-per-count-value“ of file1? 

Thanks for your support!
Regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

Yes, you need to reduce time divisions of both files to common value. You can take either _ticks per quarter note_ of first file or second one. Or you can set new value that will cause minimum rounding error on delta-times processing.

I have plans on MIDI file merge tool, so thanks for your question. I'll increase priority of this task.

Max

**Comment by FischertBilligheim** [comment]
Hi Max,
I realized the functionality this evening in my application- and it works.
Maybe - as you mentioned - you can realize it in the library in the future…..

**Comment by unitybru** [comment]
+1 for the ability to stitch MIDI files more easily.

For those who find this thread, here is how I did it. I had a list of MIDI files that I needed to append one after the other. The trick is to shift things before adding the chunks.

```
var fileNameOut = "myoutput.mid";
var midiFileOut = new MidiFile()
{
	TimeDivision = midiFile.TimeDivision // copied from master file
};

// Add all parts after shifting them
long addedSoFarMicroseconds = 0;
foreach (var midiPart in lsToWrite) // lsToWrite is a list of MidiFile objects
{
	var currentDuration = midiPart.GetDuration<MetricTimeSpan>();
	midiPart.ShiftEvents(new MetricTimeSpan(addedSoFarMicroseconds));
	midiFileOut.Chunks.AddRange(midiPart.Chunks);
	addedSoFarMicroseconds += currentDuration.TotalMicroseconds;
}
midiFileOut.Write(fileNameOut);
```

**Comment by melanchall** [comment]
@unitybru Thanks for the code snippet!

Please note that this code will work only for files with the same time division and tempo. I still have plans on MIDI files merger tool, but currently I'm busy with a big task about supporting macOS in Devices API of the library.

Merging MIDI files requires more work in general case than it can be supposed :)

**Comment by melanchall** [comment]
Starting with the [7.0.0](https://github.com/melanchall/drywetmidi/releases/tag/v7.0.0) version you can use built-in [Merger](https://melanchall.github.io/drywetmidi/articles/tools/Merger.html) tool to [merge MIDI files](https://melanchall.github.io/drywetmidi/articles/tools/MIDI-files-merging.html).
