### ISSUE TITLE
Events-Collection - RemoveAt

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#43]
Should the „removeAt“ or „remove“ of the EventsCollection not update the delta-time of the following event?

Regards
Thomas

**Comment by melanchall** [comment]
Thomas,

All methods of `EventsCollection` don't modify events in any way by design. It's expected behavior. If you want delta-times are automatically corrected on add/remove events, you should use [`TimedEventsManager`](https://github.com/melanchall/drywetmidi/wiki/Events-absolute-time).

**Comment by FischertBilligheim** [comment]
Ok, fine - thanks for the explanation!
Regards
Thomas
