### ISSUE TITLE
How can I adjust the tempo by percentage?

### ISSUE THREAD

**Issue by Yorgg** [melanchall/drywetmidi#44]
I am wondering how I can adjust the tempo for a midi file by a percentage value.

For example - make it 20% faster.   Thanks!

**Comment by melanchall** [comment]
Hi,

First of all, do you need to change speed of playback using `Playback` class of the library or you need to create **new** file that is faster or slower than original one?

**Comment by Yorgg** [comment]
Hi,

Create a new file.  Well, I don't need to create a file - just require an object in memory.

**Comment by melanchall** [comment]
Well, you can use this code:

```csharp
midiFile.GetTrackChunks().First().Events.Insert(0, new SetTempoEvent(SetTempoEvent.DefaultTempo));

foreach (var trackChunk in midiFile.GetTrackChunks())
{
    foreach (var setTempoEvent in trackChunk.Events.OfType<SetTempoEvent>())
    {
        var microsecondsPerQuarterNote = setTempoEvent.MicrosecondsPerQuarterNote;
        setTempoEvent.MicrosecondsPerQuarterNote = (long)Math.Round(microsecondsPerQuarterNote * 0.8);
    }
}
```

This code changes all _Set Tempo_ events so playback will be 20% faster (0.8 means quarter note will be 20% shorter in terms of microseconds). To increase speed use division instead of multiplication.

Please let me know if it works.

**Comment by Yorgg** [comment]
This works, thank you.

**Comment by Yorgg** [comment]
Hi,

This method doesn't seem to work on the midi file below.   It doesn't match the tempo of the audio file produced by Ableton.    The difference I can see is that it has a 6/8 time signature (not sure if that would effect it?). 
[ravel_miroirs_3.zip](https://github.com/melanchall/drywetmidi/files/3795688/ravel_miroirs_3.zip)

**Comment by melanchall** [comment]
Hi,

How did you change tempo with Ableton? Just set 150 instead of 120? And then export to wav? Can you attach audio file produced by Ableton?

**Comment by melanchall** [comment]
I've checked my code with the new file and I don't see any issues. I've created small test:

```csharp
var midiFile = MidiFile.Read("ravel_miroirs_3.mid");
var durationOriginal = midiFile.GetDuration<MetricTimeSpan>().TotalMicroseconds;
Console.WriteLine(durationOriginal);

// ... here the code I've provided above ...

var durationNew = midiFile.GetDuration<MetricTimeSpan>().TotalMicroseconds;
Console.WriteLine(durationNew);
Console.WriteLine("Speed up is " + ((durationOriginal / (double)durationNew - 1) * 100) + "%");
```

And output is:

```
478695833
382956667
Speed up is 24,9999998041554%
```

So we got exactly 25% of speed up. Issue is about changing speed by percentage. We don't talk about BPM here. 25% of speed up is achieved as you can see, new file is 25% shorter than original one :)

**Comment by melanchall** [comment]
Also why you use `0.75`? `120 / 150 = 0.8`. `0.8` should give you the correct result.

**Comment by Yorgg** [comment]
Ah.  The problem was I was dividing in the wrong order.   thanks!
