### ISSUE TITLE
Volume Support

### ISSUE THREAD

**Issue by DrSloth** [melanchall/drywetmidi#46]
Does this library support changing volume of notes you want to add to Trackchunk. If it does: How to implement it? If it doesn't: Are there any workarounds?

Thanks in advance

**Comment by melanchall** [comment]
Hi,

You can set `Velocity` property to the desired value. In most cases smaller velocity means smaller volume. But how velocity will be processed is completely up to synth that will generate sound for your MIDI data so in some cases sound will loud even if velocity set to zero. MIDI standard doesn't provide such concept as volume within MIDI file.

Thanks for using the library and your question!

**Comment by DrSloth** [comment]
Thank you very much for your reply!!
