### ISSUE TITLE
Incoming events - how to get sustain pedal data?

### ISSUE THREAD

**Issue by Yorgg** [melanchall/drywetmidi#47]
I am listening to the `InputDevice` and want to get the _noteName_  and _velocity_ from `NoteOn`,  `NoteOff` events, and also the sustain pedal event (on piano).

I know the `EventType`, but don't know what to do next: 

 ```
        if (e.EventType == DryWetMidi.Smf.MidiEventType.NoteOn)
        {
            // -> NoteName ???
            // -> velocity ???
        }
```

thank you

**Comment by Yorgg** [comment]
I just realized I can do a cast:  (I'm new to c#)

```
 if (e.EventType == Melanchall.DryWetMidi.Smf.MidiEventType.NoteOn)
        {
            var note = e as NoteOnEvent;

            Debug.Log(note.Velocity);
            Debug.Log($"{note.GetNoteName()}{note.GetNoteOctave()}");
        }
```
I have one question remaining:  how to get the sustain pedal data?

**Comment by melanchall** [comment]
Hi,

According to MIDI standard, sustain pedal on/off is a control change event. So you can use this code:

```csharp
var controlChangeEvent = e as ControlChangeEvent;
if (controlChangeEvent != null && ControlUtilities.GetControlName(controlChangeEvent) == ControlName.DamperPedal)
{
    var controlValue = controlChangeEvent.ControlValue;
    var sustainOn = controlValue < 64;
}
```

Values from 0 to 63 correspond to sustain is turned on.

**Comment by Yorgg** [comment]
Great thanks.
