### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Yorgg** [melanchall/drywetmidi#48]
I am having noticeable latency from when a key is pressed on digital piano and when sound is produced.   The latency time is constant (around ~100ms if I had to guess). 

Output device is `MICROSOFT GS WAVETABLE SYNTH`.
The application is running on Unity.   

How can I reduce this latency?

```
  device = Melanchall.DryWetMidi.Devices.InputDevice.GetByName(deviceName);    
  device.EventReceived += OnEventReceived;
  device.StartEventsListening();

 private void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
    {
        if (e.EventType == Melanchall.DryWetMidi.Smf.MidiEventType.NoteOn)
        {
            var note = e as NoteOnEvent;
            Debug.Log(note.Velocity);
            Debug.Log($"{note.GetNoteName()}{note.GetNoteOctave()}");
        }
       
        if (App.Settings.Midi.outputDevice != null)
        {
            App.Settings.Midi.outputDevice.SendEvent(e);
        }
    }
}

```

thanks!

**Comment by melanchall** [comment]
Hi,

It's known problem of the Microsoft GS Wavetable Synth. This software synth adds ~100 ms latency. If you google this problem, you'll find a lot of threads. Examples:

* https://answers.microsoft.com/en-us/windows/forum/windows_7/latency-problem-using-ms-gs-wavetable-synth/1e85704a-803c-438f-b472-fb0cb5211be4
* https://www.pgmusic.com/forums/ubbthreads.php?ubb=showflat&Number=490328
* http://robertinventor.com/smf/interesting-things-off-topic/how-to-play-the-microsoft-gs-wavetable-synth-without-the-110-th-second-latency/

So it's not about DryWetMIDI.

**Comment by Yorgg** [comment]
Ah okay.  I will try another output device then, thank you.
