### ISSUE TITLE
nuget release

### ISSUE THREAD

**Issue by zivillian** [melanchall/drywetmidi#52]
Do you have timeline for the next nuget release? I'm looking for netstandard support.

**Comment by melanchall** [comment]
Hi,

I'm planning to release new version at the start of next week. Or maybe at the end of the current one, but I'm not sure :)

Please don't close the issue. I'll inform you when the package will be pushed to NuGet.

**Comment by melanchall** [comment]
I've released **DryWetMIDI 5.0.0**.

Please read release notes: https://github.com/melanchall/drywetmidi/releases/tag/v5.0.0
Full documentation: https://melanchall.github.io/drywetmidi
