### ISSUE TITLE
Possible to play .aiff samples? 

### ISSUE THREAD

**Issue by Yorgg** [melanchall/drywetmidi#53]
Instead sending midi events to an external 'output device', I would like to play local .aiff files.    Is this possible? 

For example, this Unity project uses NAudio to play aiff samples:  https://github.com/catdevpete/Unity-MIDI-Piano/tree/master/Assets
 
thanks

**Comment by melanchall** [comment]
Hi,

DryWetMIDI is a library for manipulating MIDI data. How MIDI events will be processed or played is completely up to you. Playing audio is not a part of the library.

Thanks
