### ISSUE TITLE
How can I get the "musical" chordname from a chord?

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#58]
It seems possible to get the "Musical"-notes from a "MusicTheory.Chord" object by using "Parse".
But how can I get the "musical-name" of a "SMF.Interaction.Chord" object?
(Musical Name:  e.g: "Cmaj")

Thanks and best regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

Do you want to have method like `ToMusicalName` on `Interaction.Chord` or `Parse` one? At now you cannot get musical name neither for `MusicTheory.Chord` nor for `Interaction.Chord`. But it looks like useful feature. So I'll add it to my backlog. Thank you!

Max

**Comment by FischertBilligheim** [comment]
Hi Max,

Yes, this is the idea: With the chord-manager, I‘m getting all the chords - e.g. from a chunk. But I would like to show the „musical name“ of these chords in my GUI. 
My proposal: Interaction.Chord.ToString() could do that....

Thanks to you, Max!
Regards
Thomas

**Comment by melanchall** [comment]
Thomas,

I'll implement the feature within this issue so please don't close it.

**Comment by FischertBilligheim** [comment]
👍👍

**Comment by melanchall** [comment]
Hi,

I've added method `GetMusicTheoryChord` for `Interaction.Chord` and `GetChordDefinitions` for `MusicTheory.Chord`. Last one is what you need.

`GetChordDefinitions` returns collection of "musical" definitions of a chord as instances of `ChordDefinition` class. Its `ToString` method returns musical name of the chord. Definitions are sorted by complexity so I suppose the first one is what you need.

For example, for chord `A C E` you'll get these definitions:

```
Am
Ab3
Adim#5
Aaugb3b5
```

Determining chord's definitions is pretty tricky. I don't use chords tables, the library tries to infer definitions algorithmically, so I sure there are errors and some chords may not be analyzed correctly (or analyzed at all). Please test the new API and if you'll notice issues, report me.

**Comment by FischertBilligheim** [comment]
Great, thanks a lot!! I will test it and give you response!!
Best regards
Thomas

**Comment by FischertBilligheim** [comment]
Hi Max,

in a first test, I used the following code:

            _IEnumerable<Melanchall.DryWetMidi.Interaction.Chord> chords = gActTrack.GetChords(20);
            foreach (Melanchall.DryWetMidi.Interaction.Chord chord in chords)
            {
                    if (chord.Time + chord.Length > nt && chord.Time < mt)
                    {
                        Melanchall.DryWetMidi.MusicTheory.Chord mChord   = chord.GetMusicTheoryChord();
                        IReadOnlyCollection<ChordDefinition> musicChords = mChord.GetChordDefinitions();

                        if (musicChords.Count > 0)
                            utils.DrawChord(chord.Time, musicChords.First().ToString(), Color.Red);
                    }
            }_

I showed the result in my current implementation of my midi-editor/sequencer (red line on the top)

![Chords](https://user-images.githubusercontent.com/20623089/72562188-1d475a80-38ab-11ea-957f-b8ac34e55a1b.PNG)

You see a chord-track of the song "Angel of Harlem from U2". The first chord has the notes "E,C,G,E,C" - I would expect, that this is the Chord "C-Maj", but not "C7#9#7"....

Another result:
I cannot call these new methods in my draw-routine - the redraw is far too slow now.....

**Comment by FischertBilligheim** [comment]
Hi Max,

additional hint:
If I'm using this code:

            _IEnumerable<Melanchall.DryWetMidi.Interaction.Chord> chords = gActTrack.GetChords(20);

            foreach (Melanchall.DryWetMidi.Interaction.Chord chord in chords)
            {
                    if (chord.Time + chord.Length > nt && chord.Time < mt)
                    {
                    utils.DrawChord(chord.Time, chord.ToString(), Color.Red);_

this is the result:
![image](https://user-images.githubusercontent.com/20623089/72564412-f2abd080-38af-11ea-905b-55ac651a504e.png)

And this works fast enough in the Paint-method......

**Comment by melanchall** [comment]
Hi Thomas,

Thanks for your tests. It seems it would be better to analyze chords by tables :)

But I have a couple of comments:
* First chord is `C E G C E`. `C` chord is `C E G`. With addition of `E` and `C` on top of it still `C` chord?
* `chord.ToString()` just prints notes of a chord so it's not a name of chord.

**Comment by FischertBilligheim** [comment]
Hi Max,

To be honest: I have not much knowledge about music theory. But I assume, that if there are duplicate notes in different octaves ( like in my sample) -  these notes can be ignored.

I think a good reference is here:
http://www.sengpielaudio.com/ChordNameFinder.htm.


To the second comment:
Yes, sure - I’m aware of that. I only mentioned that to give you the info, that this is fast enough to call these functions in the paint/redraw method.

**Comment by melanchall** [comment]
Yes, I'm looking to the same article :)

Well, I'll try to rewrite my methods to use chords tables prior to current algorithm.

**Comment by FischertBilligheim** [comment]
Maybe that can help:

https://github.com/DrA1ex/GuitarHelper/blob/master/PianoKeyEmulator/Chords.cs

**Comment by FischertBilligheim** [comment]
I meanwhile tested the „PianoKeyEmulator“-Approach - it looks pretty good.
I‘m currently adapting the algorithm to the classes of drywetmidi. 
If you are interested, I can - if I finished - send you the implementation, you can adapt it to your coding-style, and integrate it....

**Comment by melanchall** [comment]
Hi Thomas,

I've removed `GetChordDefinitions` method and added `GetNames` one. It returns list of names of the chord using chord table. At now the table is not complete but I'll add more records to it.

Also I asked my friend from [symphony orchestra](https://en.wikipedia.org/wiki/Tchaikovsky_Symphony_Orchestra) about duplicated notes in a chord. You're right, `C E G C E` is indeed `C` chord, it doesn't matter how many duplicated notes are on top of `C E G` triad.

Please test new API. I'm waiting for your feedback.

**Comment by melanchall** [comment]
Added more records to chords names table (CNT).

**Comment by FischertBilligheim** [comment]
Hi Max,

I did a first short test: It looks better, and I don't have Performance issues any more…

But furthermore a lot of chords are not recognized:
e.g: E,G,C:-> C-Maj
       C A,F -> F-Maj
      D#,G#,C -> G#

![image](https://user-images.githubusercontent.com/20623089/72688974-a5786a80-3b0c-11ea-8200-df6930631ca3.png)

The mentioned "PianoKeyEmulator" has an interesting approach:
"Permutations" of the chords are generated and tested - maybe you can have a look to that:

It's the first result from me from today... it's a in-work version:


[MidiChords.zip](https://github.com/melanchall/drywetmidi/files/4083654/MidiChords.zip)

**Comment by melanchall** [comment]
Thanks Thomas. Yes, these permutations are called [chord inversions](https://www.musictheoryacademy.com/understanding-music/chord-inversions/). I'll include them to the CNT lookup. But I think it will degrade performance. I'll test and let you know.

Thanks again.

**Comment by FischertBilligheim** [comment]
Thanks to you, Max!! 👍

**Comment by melanchall** [comment]
Added chords inversions to CNT lookup. @FischertBilligheim Please check out.

**Comment by FischertBilligheim** [comment]
Hi Max,

wow - the current implementation is really great!  
Congratulations - how you realized that new functionality in that short time!!

Best regards
Thomas

**Comment by FischertBilligheim** [comment]
![image](https://user-images.githubusercontent.com/20623089/72841533-dd131e00-3c96-11ea-944c-00ee38a51998.png)

**Comment by aDu** [comment]
Thanks! It's a great feature. It seems when we do `chord.GetNames();` we have to manually filter out the possible chord names based on the bass note? It's a quick one-liner by parsing the string (e.g. if the bass note was `B`, I would only filter results that start or end with a capital `B` string). WDYT about having it integrated into the API, e.g. `chord.GetNames(NoteName bassNote)`?

**Comment by aDu** [comment]
Is there a way to remove duplicated results e.g. `C` vs `CM` vs `Cmaj`?
