### ISSUE TITLE
Default Time Signature (4/4) not working

### ISSUE THREAD

**Issue by rdiazhin** [melanchall/drywetmidi#59]
Creating a new Midi file with default Time Signature (4/4) saves the file with no time signature. Using a non default Time Signature (i.e 3/4) works fine.

**Comment by melanchall** [comment]
Hi,

It's correct behavior. 4/4 time signature is the default signature so no need to store corresponding MIDI event explicitly. The same rule applied to the default tempo (120 BPM).

**Comment by rdiazhin** [comment]
Still not saving default time signature, tempo and key using the compression policy to NoCompresion. 

`            MidiFile newFile = new MidiFile();
            TrackChunk trackChunk1 = new TrackChunk();

            TimedEvent[] timedEvents1 = new TimedEvent[]
            {
                  new TimedEvent(new CopyrightNoticeEvent($"(C) {DateTime.Now.Year} TEST")) { Time = 0},
                  new TimedEvent(new ProgramChangeEvent
                  {
                      ProgramNumber = GeneralMidiProgram.AcousticGrandPiano.AsSevenBitNumber(),
                      Channel = (FourBitNumber)9,
                  }) {Time = 0},
            };

            trackChunk1.AddTimedEvents(timedEvents1);

            Note[] notes1 = new Note[]
            {
                new Note(Melanchall.DryWetMidi.MusicTheory.NoteName.C, 4, 960, 0)
                {
                  Channel = (FourBitNumber)9,
                },
            };

            trackChunk1.AddNotes(notes1);
            newFile.Chunks.Add(trackChunk1);

            newFile.ReplaceTempoMap(TempoMap.Create(new TicksPerQuarterNoteTimeDivision(960), Tempo.FromBeatsPerMinute(120), new TimeSignature(4, 4)));

            newFile.Write(@"E:\Midi\TestNoCompression.mid", true, MidiFileFormat.SingleTrack, new WritingSettings { CompressionPolicy = CompressionPolicy.NoCompression });
`

[TestNoCompression.zip](https://github.com/melanchall/drywetmidi/files/4013227/TestNoCompression.zip)

**Comment by melanchall** [comment]
OK, I got you. You set time signature via `TempoMap`. In this case no `TimeSignatureEvent` added to a MIDI file. So `CompressionPolicy.NoCompression` does nothing. `NoCompression` will work in case MIDI file already contains default time signature event in the start of the file so the event will not be deleted.

Please tell me, do you need to have `TimeSignatureEvent` in your case in a MIDI file, and if yes, why?

Thanks

**Comment by rdiazhin** [comment]
I managed to save the defaults with  `CompressionPolicy.NoCompression` using TimedEvents instead TempoMap.

I'm testing your Midi library to make a Style Maker software for Yamaha arranger keyboards and so far it is perfect for what I need.

Thank you for your help and for this awesome Midi library.
