### ISSUE TITLE
Automatic chords - is it possible?

### ISSUE THREAD

**Issue by tamitam** [melanchall/drywetmidi#6]
Thanks for this amazing library!
Did you write a code to create automatic chords?
I mean, If I want to use your library to make a playback. Do I have to enter code for all the sequences (drums, piano, guitar etc.) Or you have a better way to suggest me?
Thanks again!

**Comment by melanchall** [comment]
Hi,

Thanks for using the library! Please clarify what do you mean "create automatic chords"? At now chords can be obtained via `GetChords` method:

```csharp
using Melanchall.DryWetMidi.Smf;
using Melanchall.DryWetMidi.Smf.Interaction;

var midiFile = MidiFile.Read("mysong.mid");

TrackChunk pianoTrack = midiFile.GetTrackChunks()
                                .FirstOrDefault(c => c.Events
                                                      .OfType<SequenceTrackNameEvent>()
                                                      .Any(e => e.Text == "Piano"));

IEnumerable<Chord> pianoChords = pianoTrack.GetChords();
```

By default notes should start at the same time to be fall into one chord. You can specify tolerance in MIDI ticks to specify area where notes can start to make up a chord:

```csharp
IEnumerable<Chord> pianoChords = pianoTrack.GetChords(100);
```

Is it what you need?

**Comment by melanchall** [comment]
@tamitam Did I answer on your question? :)

**Comment by melanchall** [comment]
I'm closing this issue since no info provided.

@tamitam Please reopen if you have some comments on my answer.
