### ISSUE TITLE
SysExEvent

### ISSUE THREAD

**Issue by barwich** [melanchall/drywetmidi#60]
Hi,

I have some trouble with sending NormalSysExEvents to a mif4 (www.rosendahl-studiotechnik.com). It is a little timecode generator/translator, which I like to setup via MMC commands.

Two Issues came up:
1. If the Midi Device is connected to an USB-C Port an Out of Memory Exception is thrown (this happens with all USB Midi Devices I tried).
- Seems to be a Windows Problem.

2. The SysEx Message does not work:
I used a loopBackPort to control the Output. It seems to be the correct byte-array.
- If I send the same SysEx Message by another MidiTool (like PocketMidi, ...) it works fine with any USB Port.

If I send a ShortMessages like the MidiTimeCodeEvent, the mif4 and other Devices get it.

These SysEx Messages are needed:
F0 7F 7F 06 03 F7 - Start
F0 7F 7F 06 01 F7 - Stop
F0 7F 7F 06 44 06 01 21 02 00 00 00 F7 - Set Time and FPS
F0 7F 7F 06 40 03 46 01 0A F7 - Prepare the mif4 for Timecode generating
As I wrote before, if these Commands are send by another MidiTool they work as they should. Sended by OuputDevice.SendEvent(NormalSysExEvent/EscapeSysExEvent) a Midi Sniffer gets the correct Byte-Array but the Device does not react.

**Comment by melanchall** [comment]
Hi,

**Problem with USB-C**

Unfortunately I cannot reproduce the problem right now since I have no device with this port.

**Problem with SysEx event**

I've created small program to check your issue. I've found no errors, all sysex events you've mentioned are sent/received successfully. Please take a look at my program:

```csharp
var eventsReceived = new List<MidiEvent>();

using (var outputDevice = OutputDevice.GetByName("MIDI A"))
{
    outputDevice.PrepareForEventsSending();

    using (var inputDevice = InputDevice.GetByName("MIDI A"))
    {
        inputDevice.EventReceived += (_, e) => eventsReceived.Add(e.Event);
        inputDevice.StartEventsListening();

        outputDevice.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x06, 0x03, 0xF7 }));
        outputDevice.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x06, 0x01, 0xF7 }));
        outputDevice.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x06, 0x44, 0x06, 0x01, 0x21, 0x02, 0x00, 0x00, 0x00, 0xF7 }));
        outputDevice.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x06, 0x40, 0x03, 0x46, 0x01, 0x0A, 0xF7 }));

        SpinWait.SpinUntil(() => eventsReceived.Count == 4);

        Debug.Assert(((NormalSysExEvent)eventsReceived[0]).Data.SequenceEqual(new byte[] { 0x7F, 0x7F, 0x06, 0x03, 0xF7 }));
        Debug.Assert(((NormalSysExEvent)eventsReceived[1]).Data.SequenceEqual(new byte[] { 0x7F, 0x7F, 0x06, 0x01, 0xF7 }));
        Debug.Assert(((NormalSysExEvent)eventsReceived[2]).Data.SequenceEqual(new byte[] { 0x7F, 0x7F, 0x06, 0x44, 0x06, 0x01, 0x21, 0x02, 0x00, 0x00, 0x00, 0xF7 }));
        Debug.Assert(((NormalSysExEvent)eventsReceived[3]).Data.SequenceEqual(new byte[] { 0x7F, 0x7F, 0x06, 0x40, 0x03, 0x46, 0x01, 0x0A, 0xF7 }));
    }
}
```

I've performed checks on loopback MIDI device. I suppose you specify `0xF0` start byte. But you mustn't specify it. It will sent automatically.

**Comment by melanchall** [comment]
@barwich Any news?

**Comment by barwich** [comment]
Hi,

sorry for the late reply. Yes, the 0xF0 at the beginning was wrong, as you mentioned. The Midi Sniffer cuts off the first 0xF0, so the sended bits where displayed correctly with only one 0xF0, for me. Wireshark USB showed that two 0xF0 where sended.

Regarding the USB-Port Problem: It seems to be a problem with USB-C Hubs and Windows 10. With a direct connection everything works fine, even when only the Midi-Device is connected to the Hub. If there are more devices (like sticks, dongle and so on) connected to the hub, I do get an out of memory exception when trying to send a SysExEvent. It does not happen when I do send a quarter Message.

Axel

**Comment by melanchall** [comment]
Hmm, interesting problem. But unfortunately I can't reproduce it since I have no devices to perform the test :(

Can you please close this issue and open new one regarding USB-C hubs problem only?

**Comment by barwich** [comment]
sure, thanks for the help.
