### ISSUE TITLE
HELP, How can I record midi events in a loop, for instance from bar 1 to 4 looping indefinitely until recording is stopped?

### ISSUE THREAD

**Issue by rdiazhin** [melanchall/drywetmidi#61]
Hello, thanks again for this wonderful library.

I have managed to test successfully the recording functions of the library in the linear mode from bar 1 (time 0) to bar x, but I need to be able to go to the beginning and keep adding events in a loop.

I'm trying to make a Style maker for Yamaha arrangers such as PSR, Tyros, Genos series (yamaha calls Styles to rhythms for auto accompaniments) and the style is composed by 3 intros, 4 Main Variations, 4 Fills, 3 Endings. The user can set the bar length for each section as need from 1 to 32 bars. 

Styles for Yamaha keyboards are midi files with special markers and customs chunks.

The user can define for example, the Main Variation A is 4 bars length.

We start recording events from  bar 1 and when it reaches bar 4, automatically restart to bar 1 and keep adding events from bar 1 to 4 until recording is stopped.

To record the drums channel for instance, we start the recording and begin playing the bass drum until we are satisfied with the result, then add the hi-hat, then snare drum, then toms, ans so on, all this while the recording is in a loop for bar 1 to 4 indefinitely until recording is stopped.

The loop must also be able to play all recorded events.

Here is a video of how to create a style on the Yamaha Arranger itself so you can have a better idea of what I need.

https://youtu.be/qKPaMVjJqqQ

**Comment by melanchall** [comment]
Hi,

Thanks for using the library and for sharing your experience! Right now there is no easy way to do what you want. But I'll definitely implement features that can help with your task.

As a workaround I can suggest the following approach:

1. Create instance of `Recording` class
2. During recording check duration of it and if it's bigger than your desired value (for example 4 bars), stop current recording and start new one (via new instance of `Recording` class)
3. When you've recorded some data, create instance of `Playback` class passing all recorded data to it
4. Start playback along with new recording

Please tell me whether this workaround good for you or not.

Thank you

**Comment by rdiazhin** [comment]
Actually that workaround is what I'm trying to do by now. However, I'm getting weird results with a quick test I did. 

I will keep trying.

Regards.

**Comment by melanchall** [comment]
Hi,

Any news on this issue?

**Comment by rdiazhin** [comment]
I'm still having weird results trying to record midi events in a loop.

For my test, I have created a two bar midi file in memory to serve as metronome. When the recording is started the metronome starts playing to serve as guide; when the metronome reaches `Finished` event I add the recorded events to a list of `TrackChunk` using `recording.ToTrackChunk()`. 

I'm passing the metronome tempoMap to the recording instance 

`recording = new Recording(metronome.GetTempoMap(), inputDevice);`

Immediately a new playback is created and  start playing the events on the list of recorded events.
a new recording is started to capture the events on the next loop, and so on.

I'm recording a very basic Rock pattern like this (Piano roll view in Cakewalk)::
![image](https://user-images.githubusercontent.com/8750636/72472538-bfcfe280-37b2-11ea-8d8e-df0346d8216b.png)

So far, the events recorded are reproduced as expected and I can hear the pattern is fairly close to the desired result.

So far, the events recorded are reproduced as expected and I can hear the pattern is fairly close to the desired result after several loops.

When I stop the recording, I take each trackchunk from the list of `TrackChunk ` captured from the recording and add them to a new MidiFile and then call Write method to save the midi file.

The midi file result is no accurate and it has only 1 bar or less and all notes have half of the time length expected.
This is the result I'm getting (Piano roll view in Cakewalk):
![image](https://user-images.githubusercontent.com/8750636/72473352-8304eb00-37b4-11ea-89c5-fbe4e3469e5e.png)

I have attached a sample project if you can take a look and guide me on what I'm doing wrong.

[MidiLoopRecordingTest.zip](https://github.com/melanchall/drywetmidi/files/4067650/MidiLoopRecordingTest.zip)

Thanks for your help.

**Comment by melanchall** [comment]
> add them to a new MidiFile

Try to set tempo map to this new file:

```csharp
newMidiFile.ReplaceTempoMap(metronome.GetTempoMap());
```

**Comment by rdiazhin** [comment]
I already tried that and still have the same issues. I tried replaceTempoMap as you suggested, tried creating the tempo and time signature as TimedEvents, create a new tempoMap and nothing seems to work.

**Comment by rdiazhin** [comment]
I finally make it work.

The solution was removing the `ActiveSensing` events from the recorded events stored in the trackchunk list.

`foreach (var trkChunk in trackChunks)`
`{`
`trkChunk.RemoveTimedEvents(e1 => e1.Event.EventType == MidiEventType.ActiveSensing);`
`midiFile.Chunks.Add(trkChunk);`
`}`

Thanks for your help again.
I'm closing the issue now.
