### ISSUE TITLE
Cant install SMO for SQL 2017 Nuget package ?or 

### ISSUE THREAD

**Issue by ajnair100** [melanchall/drywetmidi#62]
am still facing the issue am unable to install SMO 14 for sql 2017 for me to run my Avamar backup which needs these Smo14

how can I do this ? any idea is it powershell script or Nuget or what should be done to get these SMo14 for sql 2017??

the command PS fails ..

**Comment by melanchall** [comment]
How the issue is related with DryWetMIDI? :)
