### ISSUE TITLE
Parsing performance

### ISSUE THREAD

**Issue by Yorgg** [melanchall/drywetmidi#64]
I seem to be getting slow results when parsing.

Midi file with 14,000 events:

`GetTempoMap()                      =   140-270ms `
`GetNotes()                               =   200-300ms`
`GetTimedEvents() + TimeAs()  =  180-322ms`

```
foreach (TimedEvent e in midi.GetTimedEvents())
        {                           
              realtime =  e.TimeAs<MetricTimeSpan>(tempoMap).TotalMicroseconds / 1000000f                
        }
```

Running on Unity +  i7 3770.

Any thoughts? 

midi file:
[midi.zip](https://github.com/melanchall/drywetmidi/files/4070374/midi.zip)

**Comment by melanchall** [comment]
Hi,

I suppose it's something related with Unity. On i7 4790 I got following results:

```
GetTempoMap = 28ms
GetNotes = 40ms
GetTimedEvents + TimeAs = 44ms
```

I'll check with Unity as soon as possible.

**Comment by melanchall** [comment]
I confirm greater times with Unity. Thanks for reporting the issue. I'll try to improve preformance.

**Comment by melanchall** [comment]
@Yorgg Let's clarify your case. You just need these methods without MIDI file modification?

**Comment by Yorgg** [comment]
Thanks for looking into this.   I noticed that after compiling the project into a 'Build' the parsing was faster - but there is still a noticeable delay.

Yes,  I just need noteOn,  DamperPedal and noteOff events, and the duration of the notes.

**Comment by melanchall** [comment]
I suppose I can't do much regarding those separate methods, **BUT** I think some things can be calculated along with file reading. So `MidiFile.Read` will be slower, but right after reading you will have tempo map, notes and timed events. So entire process will be faster than separate calls of `MidiFile.Read`, `GetTempoMap`, `GetNotes` and `GetTimedEvents`.

**Comment by Yorgg** [comment]
Sure.  If the data can be gathered during .Read() that would be perfect.   

I'm curious why it runs slower in Unity - compiler related?

**Comment by melanchall** [comment]
It'sbecause of Unity uses Mono as cross-platform .NET runtime which is slower than .NET Core or .NET Framework. It's known "feature" of Mono :)

**Comment by melanchall** [comment]
This task involves more changes than I thought, so please be patient :)

**Comment by Yorgg** [comment]
No worries, thanks for the update.

**Comment by melanchall** [comment]
Hi @Yorgg,

I've added some new classes and refactor existing ones. So now you can use this code:

```csharp
var timedEventsReadingHandler = new TimedEventsReadingHandler(true);
var notesReadingHandler = new NotesReadingHandler(true);
var tempoMapReadingHandler = new TempoMapReadingHandler();

var settings = new ReadingSettings();
settings.ReadingHandlers.Add(timedEventsReadingHandler);
settings.ReadingHandlers.Add(notesReadingHandler);
settings.ReadingHandlers.Add(tempoMapReadingHandler);

var midiFile = MidiFile.Read(@"lszt_hr2.mid", settings);
var tempoMap = tempoMapReadingHandler.TempoMap;
var notes = notesReadingHandler.Notes;

foreach (TimedEvent e in timedEventsReadingHandler.TimedEvents)
{
    var realtime = ((MetricTimeSpan)e.TimeAs(TimeSpanType.Metric, tempoMap)).TotalMicroseconds / 1000000f;
}
```

Also please note that I use non-generic `TimeAs` passing required `TimeSpanType`. Reflection is really slow in Unity/Mono so I suggest to avoid it if possible.

Please test this new API and tell me whether it's faster or not.

**Comment by Yorgg** [comment]
Thanks!  I will try it out today/tomorrow and report back to you.

**Comment by Yorgg** [comment]
This has made it noticeably faster.  After compiling the 'build' I'm getting around ` ~300ms` total. 

For my needs this is good enough at the moment, as the average size midi file is loading `<100ms. `

I got `80ms `using the [https://github.com/naudio/NAudio/tree/master/NAudio/Midi](NAudio midi library) (this is before getting realtimes, or note durations - which I haven't figured out how to do yet, lol).    Perhaps this library could be examined to further improve performance?

**Comment by Yorgg** [comment]
Also, on my system: 

`(MetricTimeSpan)e.TimeAs(TimeSpanType.Metric, tempoMap)).TotalMicroseconds / 1000000f`

is 2x slower than the previous: 

`e.TimeAs<MetricTimeSpan>(tempoMap).TotalMicroseconds /  1000000f`

**Comment by melanchall** [comment]
Hi,

Thanks for your tests!

NAudio reading API contains much less classes and methods which is good for simple files and simple tasks. DryWetMIDI contains much more intermediate steps in reading process. This simplifies maintaning and extending the library, and gives some features like repairing broken files for example. All these steps adds small performance penalties which together give that 20 ms difference.

I'll try to find a way to further improve performance, but I think I can't do much in current architecture of the library (which is good and will not be changed). In my opinion 80 and 100 are quite close values.

As for `TimeAs`, hmm... it's strange. Well, if generic version is faster, use it.

**Comment by Yorgg** [comment]
Indeed it is a very 'bare-bones' library.  The <100ms time I was referring to was for smaller files.  The difference I observed was  [~80ms,  ~300ms], for the midi file I had attached.

**Comment by melanchall** [comment]
I have an idea about what can be changed in channel events reading. I'll try and let you know if it give any performance boost.

**Comment by melanchall** [comment]
I've made small change in `MidiReader`, and my benchmarks show that `MidiFile.Read` works faster after that:

|File format|File size|Events count|Old time (ms)|New time (ms)|
|---|---|---|---|---|
|Multisequence|Large|3949 – 7502|51.839 |26.395 |
|Multisequence|Middle|1571 – 3085|20.235 |10.414 |
|Multisequence|Small|768 – 1401|9.077 |4.625 |
|Multitrack|Large|139325 – 143545|1416.173 |1160.989 |
|Multitrack|Middle|4003 – 5801|128.608 |93.682 |
|Multitrack|Small|0 – 21|0.688 |0.589 |
|Singletrack|Large|14707 – 120084|480.574 |323.901 |
|Singletrack|Middle|8888 – 9630|174.760 |107.235 |
|Singletrack|Small|5 – 33|0.749 |0.640 |

_These times for several files so don't be confused._

Please test and tell me whether `MidiFile.Read` works faster or not.

**Comment by Yorgg** [comment]
Looks like it is faster --> ~250ms from the previous ~300ms.  Thanks!

**Comment by melanchall** [comment]
I find a way to further improve speed of reading. Investigating. I'll let you know about results.

**Comment by melanchall** [comment]
I've added `bool` property `PutDataInMemoryBeforeReading` to `ReadingSettings`. If it set to `true`, entire file will be loaded to memory and then read from it. This significantly speeds up reading process, but consumes larger amount of memory. If your files relatively small (for example, 1 MB and smaller), you can safely use this option.

Please take the latest version and try to set new property to `true`:

```csharp
settings.PutDataInMemoryBeforeReading = true;
```

Please test and let me know new timings.

**Comment by Yorgg** [comment]
Very nice.  This has reduced parsing time by ~150ms.  ^^

When you say _"consumes a large amount of memory"..._  
Is this equivalent to the size of the midi file, or more?

**Comment by melanchall** [comment]
During reading a file there are temporary memory allocations that don't related with whether file loaded to memory or not. Also standard `FileStream` (used for reading MIDI file) always keeps buffer of 4 KB. So the new property changes in fact only that 4 KB. Instead of 4 KB the buffer will be equal to the size of entire file.

**Comment by melanchall** [comment]
Please correct me if I'm wrong: you had initially 500 ms for all methods you described in the first comment and now the same code executes for 140 ms?

**Comment by Yorgg** [comment]
Yes.  After compiling the "build"  it is around 140ms.

**Comment by melanchall** [comment]
Thank you for creating this issue and making the library better!

I have only one thing to try out right now: change reading internals of channel events. I don't think it will give significant speed up, but maybe a couple of milliseconds :)

I'll let you know about results. Thanks again.

**Comment by melanchall** [comment]
I've tested new channel events reading and it didn't give noticeable performance improvement. So if currently achieved speed of reading is OK for you, can you close the issue?

**Comment by melanchall** [comment]
I've made small changes, benchmarks show smaller times. Please take the latest version and test on your files.

**Comment by Yorgg** [comment]
Very nice.  I also confirm smaller times.
