### ISSUE TITLE
GeneralMidi2Percussion

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#65]
Hi Max,

what about the idea to add GeneralMidi2Percussion:

    /// <summary>
    /// General MIDI Level 2 percussion notes.
    /// </summary>
    public enum GeneralMidi2Percussion : byte
    {
        /// <summary>
        /// 'HighQ' General MIDI percussion note.
        /// </summary>
        HighQ = 27,

        /// <summary>
        /// 'Slap' General MIDI percussion note.
        /// </summary>
        Slap = 28,

        /// <summary>
        /// 'ScratchPush' General MIDI percussion note.
        /// </summary>
        ScratchPush = 29,

        /// <summary>
        /// 'ScratchPull' General MIDI percussion note.
        /// </summary>
        ScratchPull = 30,

        /// <summary>
        /// 'Sticks' General MIDI percussion note.
        /// </summary>
        Sticks = 31,

        /// <summary>
        /// 'SquareClick' General MIDI percussion note.
        /// </summary>
        SquareClick = 32,

        /// <summary>
        /// 'MetronomeClick' General MIDI percussion note.
        /// </summary>
        MetronomeClick = 33,

        /// <summary>
        /// 'MetronomeBell' General MIDI percussion note.
        /// </summary>
        MetronomeBell = 34,

        /// <summary>
        /// 'Acoustic Bass Drum' General MIDI percussion note.
        /// </summary>
        AcousticBassDrum = 35,

        /// <summary>
        /// 'Bass Drum 1' General MIDI percussion note.
        /// </summary>
        BassDrum1 = 36,

        /// <summary>
        /// 'Side Stick' General MIDI percussion note.
        /// </summary>
        SideStick = 37,

        /// <summary>
        /// 'Acoustic Snare' General MIDI percussion note.
        /// </summary>
        AcousticSnare = 38,

        /// <summary>
        /// 'Hand Clap' General MIDI percussion note.
        /// </summary>
        HandClap = 39,

        /// <summary>
        /// 'Electric Snare' General MIDI percussion note.
        /// </summary>
        ElectricSnare = 40,

        /// <summary>
        /// 'Low Floor Tom' General MIDI percussion note.
        /// </summary>
        LowFloorTom = 41,

        /// <summary>
        /// 'Closed Hi-Hat' General MIDI percussion note.
        /// </summary>
        ClosedHiHat = 42,

        /// <summary>
        /// 'High Floor Tom' General MIDI percussion note.
        /// </summary>
        HighFloorTom = 43,

        /// <summary>
        /// 'Pedal Hi-Hat' General MIDI percussion note.
        /// </summary>
        PedalHiHat = 44,

        /// <summary>
        /// 'Low Tom' General MIDI percussion note.
        /// </summary>
        LowTom = 45,

        /// <summary>
        /// 'Open Hi-Hat' General MIDI percussion note.
        /// </summary>
        OpenHiHat = 46,

        /// <summary>
        /// 'Low-Mid Tom' General MIDI percussion note.
        /// </summary>
        LowMidTom = 47,

        /// <summary>
        /// 'Hi-Mid Tom' General MIDI percussion note.
        /// </summary>
        HiMidTom = 48,

        /// <summary>
        /// 'Crash Cymbal 1' General MIDI percussion note.
        /// </summary>
        CrashCymbal1 = 49,

        /// <summary>
        /// 'High Tom' General MIDI percussion note.
        /// </summary>
        HighTom = 50,

        /// <summary>
        /// 'Ride Cymbal 1' General MIDI percussion note.
        /// </summary>
        RideCymbal1 = 51,

        /// <summary>
        /// 'Chinese Cymbal' General MIDI percussion note.
        /// </summary>
        ChineseCymbal = 52,

        /// <summary>
        /// 'Ride Bell' General MIDI percussion note.
        /// </summary>
        RideBell = 53,

        /// <summary>
        /// 'Tambourine' General MIDI percussion note.
        /// </summary>
        Tambourine = 54,

        /// <summary>
        /// 'Splash Cymbal' General MIDI percussion note.
        /// </summary>
        SplashCymbal = 55,

        /// <summary>
        /// 'Cowbell' General MIDI percussion note.
        /// </summary>
        Cowbell = 56,

        /// <summary>
        /// 'Crash Cymbal 2' General MIDI percussion note.
        /// </summary>
        CrashCymbal2 = 57,

        /// <summary>
        /// 'Vibraslap' General MIDI percussion note.
        /// </summary>
        Vibraslap = 58,

        /// <summary>
        /// 'Ride Cymbal 2' General MIDI percussion note.
        /// </summary>
        RideCymbal2 = 59,

        /// <summary>
        /// 'Hi Bongo' General MIDI percussion note.
        /// </summary>
        HiBongo = 60,

        /// <summary>
        /// 'Low Bongo' General MIDI percussion note.
        /// </summary>
        LowBongo = 61,

        /// <summary>
        /// 'Mute Hi Conga' General MIDI percussion note.
        /// </summary>
        MuteHiConga = 62,

        /// <summary>
        /// 'Open Hi Conga' General MIDI percussion note.
        /// </summary>
        OpenHiConga = 63,

        /// <summary>
        /// 'Low Conga' General MIDI percussion note.
        /// </summary>
        LowConga = 64,

        /// <summary>
        /// 'High Timbale' General MIDI percussion note.
        /// </summary>
        HighTimbale = 65,

        /// <summary>
        /// 'Low Timbale' General MIDI percussion note.
        /// </summary>
        LowTimbale = 66,

        /// <summary>
        /// 'High Agogo' General MIDI percussion note.
        /// </summary>
        HighAgogo = 67,

        /// <summary>
        /// 'Low Agogo' General MIDI percussion note.
        /// </summary>
        LowAgogo = 68,

        /// <summary>
        /// 'Cabasa' General MIDI percussion note.
        /// </summary>
        Cabasa = 69,

        /// <summary>
        /// 'Maracas' General MIDI percussion note.
        /// </summary>
        Maracas = 70,

        /// <summary>
        /// 'Short Whistle' General MIDI percussion note.
        /// </summary>
        ShortWhistle = 71,

        /// <summary>
        /// 'Long Whistle' General MIDI percussion note.
        /// </summary>
        LongWhistle = 72,

        /// <summary>
        /// 'Short Guiro' General MIDI percussion note.
        /// </summary>
        ShortGuiro = 73,

        /// <summary>
        /// 'Long Guiro' General MIDI percussion note.
        /// </summary>
        LongGuiro = 74,

        /// <summary>
        /// 'Claves' General MIDI percussion note.
        /// </summary>
        Claves = 75,

        /// <summary>
        /// 'Hi Wood Block' General MIDI percussion note.
        /// </summary>
        HiWoodBlock = 76,

        /// <summary>
        /// 'Low Wood Block' General MIDI percussion note.
        /// </summary>
        LowWoodBlock = 77,

        /// <summary>
        /// 'Mute Cuica' General MIDI percussion note.
        /// </summary>
        MuteCuica = 78,

        /// <summary>
        /// 'Open Cuica' General MIDI percussion note.
        /// </summary>
        OpenCuica = 79,

        /// <summary>
        /// 'Mute Triangle' General MIDI percussion note.
        /// </summary>
        MuteTriangle = 80,

        /// <summary>
        /// 'Open Triangle' General MIDI percussion note.
        /// </summary>
        OpenTriangle = 81
    }

**Comment by melanchall** [comment]
Hi Thomas,

Great suggestion! I'll definitely add this enum.

**Comment by FischertBilligheim** [comment]
Ups - I just recognized, that my copy is not complete..... I will update the list in a new comment....

**Comment by FischertBilligheim** [comment]
This is the complete map:


    /// <summary>
    /// General MIDI Level 2 percussion notes.
    /// </summary>
    public enum GeneralMidi2Percussion : byte
    {
        /// <summary>
        /// 'HighQ' General MIDI 2 percussion note.
        /// </summary>
        HighQ = 27,

        /// <summary>
        /// 'Slap' General MIDI 2 percussion note.
        /// </summary>
        Slap = 28,

        /// <summary>
        /// 'ScratchPush' General MIDI 2 percussion note.
        /// </summary>
        ScratchPush = 29,

        /// <summary>
        /// 'ScratchPull' General MIDI 2 percussion note.
        /// </summary>
        ScratchPull = 30,

        /// <summary>
        /// 'Sticks' General MIDI 2 percussion note.
        /// </summary>
        Sticks = 31,

        /// <summary>
        /// 'SquareClick' General MIDI 2 percussion note.
        /// </summary>
        SquareClick = 32,

        /// <summary>
        /// 'MetronomeClick' General MIDI 2 percussion note.
        /// </summary>
        MetronomeClick = 33,

        /// <summary>
        /// 'MetronomeBell' General MIDI 2 percussion note.
        /// </summary>
        MetronomeBell = 34,

        /// <summary>
        /// 'Acoustic Bass Drum' General MIDI 2 percussion note.
        /// </summary>
        AcousticBassDrum = 35,

        /// <summary>
        /// 'Bass Drum 1' General MIDI 2 percussion note.
        /// </summary>
        BassDrum1 = 36,

        /// <summary>
        /// 'Side Stick' General MIDI 2 percussion note.
        /// </summary>
        SideStick = 37,

        /// <summary>
        /// 'Acoustic Snare' General MIDI 2 percussion note.
        /// </summary>
        AcousticSnare = 38,

        /// <summary>
        /// 'Hand Clap' General MIDI 2 percussion note.
        /// </summary>
        HandClap = 39,

        /// <summary>
        /// 'Electric Snare' General MIDI 2 percussion note.
        /// </summary>
        ElectricSnare = 40,

        /// <summary>
        /// 'Low Floor Tom' General MIDI 2 percussion note.
        /// </summary>
        LowFloorTom = 41,

        /// <summary>
        /// 'Closed Hi-Hat' General MIDI 2 percussion note.
        /// </summary>
        ClosedHiHat = 42,

        /// <summary>
        /// 'High Floor Tom' General MIDI 2 percussion note.
        /// </summary>
        HighFloorTom = 43,

        /// <summary>
        /// 'Pedal Hi-Hat' General MIDI 2 percussion note.
        /// </summary>
        PedalHiHat = 44,

        /// <summary>
        /// 'Low Tom' General MIDI 2 percussion note.
        /// </summary>
        LowTom = 45,

        /// <summary>
        /// 'Open Hi-Hat' General MIDI 2 percussion note.
        /// </summary>
        OpenHiHat = 46,

        /// <summary>
        /// 'Low-Mid Tom' General MIDI 2 percussion note.
        /// </summary>
        LowMidTom = 47,

        /// <summary>
        /// 'Hi-Mid Tom' General MIDI 2 percussion note.
        /// </summary>
        HiMidTom = 48,

        /// <summary>
        /// 'Crash Cymbal 1' General MIDI 2 percussion note.
        /// </summary>
        CrashCymbal1 = 49,

        /// <summary>
        /// 'High Tom' General MIDI 2 percussion note.
        /// </summary>
        HighTom = 50,

        /// <summary>
        /// 'Ride Cymbal 1' General MIDI 2 percussion note.
        /// </summary>
        RideCymbal1 = 51,

        /// <summary>
        /// 'Chinese Cymbal' General MIDI 2 percussion note.
        /// </summary>
        ChineseCymbal = 52,

        /// <summary>
        /// 'Ride Bell' General MIDI 2 percussion note.
        /// </summary>
        RideBell = 53,

        /// <summary>
        /// 'Tambourine' General MIDI 2 percussion note.
        /// </summary>
        Tambourine = 54,

        /// <summary>
        /// 'Splash Cymbal' General MIDI 2 percussion note.
        /// </summary>
        SplashCymbal = 55,

        /// <summary>
        /// 'Cowbell' General MIDI 2 percussion note.
        /// </summary>
        Cowbell = 56,

        /// <summary>
        /// 'Crash Cymbal 2' General MIDI 2 percussion note.
        /// </summary>
        CrashCymbal2 = 57,

        /// <summary>
        /// 'Vibraslap' General MIDI 2 percussion note.
        /// </summary>
        Vibraslap = 58,

        /// <summary>
        /// 'Ride Cymbal 2' General MIDI 2 percussion note.
        /// </summary>
        RideCymbal2 = 59,

        /// <summary>
        /// 'Hi Bongo' General MIDI 2 percussion note.
        /// </summary>
        HiBongo = 60,

        /// <summary>
        /// 'Low Bongo' General MIDI 2 percussion note.
        /// </summary>
        LowBongo = 61,

        /// <summary>
        /// 'Mute Hi Conga' General MIDI 2 percussion note.
        /// </summary>
        MuteHiConga = 62,

        /// <summary>
        /// 'Open Hi Conga' General MIDI 2 percussion note.
        /// </summary>
        OpenHiConga = 63,

        /// <summary>
        /// 'Low Conga' General MIDI 2 percussion note.
        /// </summary>
        LowConga = 64,

        /// <summary>
        /// 'High Timbale' General MIDI 2 percussion note.
        /// </summary>
        HighTimbale = 65,

        /// <summary>
        /// 'Low Timbale' General MIDI 2 percussion note.
        /// </summary>
        LowTimbale = 66,

        /// <summary>
        /// 'High Agogo' General MIDI 2 percussion note.
        /// </summary>
        HighAgogo = 67,

        /// <summary>
        /// 'Low Agogo' General MIDI 2 percussion note.
        /// </summary>
        LowAgogo = 68,

        /// <summary>
        /// 'Cabasa' General MIDI 2 percussion note.
        /// </summary>
        Cabasa = 69,

        /// <summary>
        /// 'Maracas' General MIDI 2 percussion note.
        /// </summary>
        Maracas = 70,

        /// <summary>
        /// 'Short Whistle' General MIDI 2 percussion note.
        /// </summary>
        ShortWhistle = 71,

        /// <summary>
        /// 'Long Whistle' General MIDI 2 percussion note.
        /// </summary>
        LongWhistle = 72,

        /// <summary>
        /// 'Short Guiro' General MIDI 2 percussion note.
        /// </summary>
        ShortGuiro = 73,

        /// <summary>
        /// 'Long Guiro' General MIDI 2 percussion note.
        /// </summary>
        LongGuiro = 74,

        /// <summary>
        /// 'Claves' General MIDI 2 percussion note.
        /// </summary>
        Claves = 75,

        /// <summary>
        /// 'Hi Wood Block' General MIDI 2 percussion note.
        /// </summary>
        HiWoodBlock = 76,

        /// <summary>
        /// 'Low Wood Block' General MIDI 2 percussion note.
        /// </summary>
        LowWoodBlock = 77,

        /// <summary>
        /// 'Mute Cuica' General MIDI 2 percussion note.
        /// </summary>
        MuteCuica = 78,

        /// <summary>
        /// 'Open Cuica' General MIDI 2 percussion note.
        /// </summary>
        OpenCuica = 79,

        /// <summary>
        /// 'Mute Triangle' General MIDI 2 percussion note.
        /// </summary>
        MuteTriangle = 80,

        /// <summary>
        /// 'Open Triangle' General MIDI 2 percussion note.
        /// </summary>
        OpenTriangle = 81,

        /// <summary>
        /// 'Open Triangle' General MIDI 2 percussion note.
        /// </summary>
        Shaker = 82,

        /// <summary>
        /// 'Jingle Bell' General MIDI 2 percussion note.
        /// </summary>
        JingleBell = 83,

        /// <summary>
        /// 'Belltree' General MIDI 2 percussion note.
        /// </summary>
        Belltree = 84,

        /// <summary>
        /// 'Castanets' General MIDI 2 percussion note.
        /// </summary>
        Castanets = 85,

        /// <summary>
        /// 'Mute Surdo' General MIDI 2 percussion note.
        /// </summary>
        MuteSurdo = 86,

        /// <summary>
        /// 'Open Surdo' General MIDI 2 percussion note.
        /// </summary>
        OpenSurdo = 87


    }

**Comment by melanchall** [comment]
Thanks a lot, Thomas! I'll work on it right after #58.

**Comment by melanchall** [comment]
Thomas, can you create PR? Some comments for enum fields look duplicated so please fix them. After completing PR you'll be shown as Contributor of the project :)

I really appreciate your help with making the library better!

**Comment by FischertBilligheim** [comment]
Hi Max, yes sure, I can try to do that...

**Comment by FischertBilligheim** [comment]
Hi Max, I need your help: How can I commit/push my changes? What has to be done for that?

![image](https://user-images.githubusercontent.com/20623089/72760448-11280980-3bd9-11ea-85d3-dd1b7d16d842.png)

**Comment by melanchall** [comment]
PR #67 is merged.
