### ISSUE TITLE
Chord-Manager

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#66]
The chords-manager currently seems not to recognize situations like this one in the screenshot:

![image](https://user-images.githubusercontent.com/20623089/72688443-a9ee5480-3b07-11ea-9401-3ae2f88f334c.png)

In Bar-6, the chords-Manager (TrackChunk.GetChords()) returns a chord with 2 notes, not with 3.
Can that be changed?

Regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

At now it's by design. That upper note belongs to first chord. To include it to the second chord we need to split it. I can provide such option for all chords managing API, but we need to discuss this new feature.

First question is where should we split a note? At the point of chord's first note? Or maybe at the point of chord's first note plus some offset? I suppose we should respect all these cases and provide flexible API.

Also note that this splitting will be kind of "ghost" since note will not be actually splitted. But since chord is a collection of notes we need to present this note in the chord.

**Comment by FischertBilligheim** [comment]
Hi Max,
The second chord in my example contains two notes. Wouldn‘t it be possible to verify, if at the beginning of this chord another tone is currently „on“ and add this tone to the chord? Maybe in that way the chord recognition  algorithm must not be changed... And maybe this adding is an option, which can be configured...

**Comment by FischertBilligheim** [comment]
Or is the problem, that a note can not belong to two chords?

**Comment by melanchall** [comment]
In this case the start of a chord will be the start of that long note which I suppose is not what user wants. We should investigate all options and decide how this new API can be implemented in such way that it's configurable and convenient for any user.

**Comment by FischertBilligheim** [comment]
For my specific use-case, I need only the „Musical Chordname“ of the parallel sounding notes. 
So maybe I can - in my mentioned example - get the two-notes chord of the chord-manager, verify if another tone is „on“ at the beginning of the chord, add the tone to the chord and start a chordname recognition. I will try this..

**Comment by melanchall** [comment]
You can try something like this:

```csharp
var chords = midiFile.GetChords();
var chordsNotes = chords.SelectMany(c => c.Notes).ToList();

foreach (var chord in chords)
{
    var notes = chordsNotes.AtTime(chord.Time);
    foreach (var note in notes)
    {
        if (!chord.Notes.Contains(note))
            chord.Notes.Add(note);
    }
}
```

After this code executed `chords` should contain all required notes.

**Comment by FischertBilligheim** [comment]
Thanks a lot, Max! I will test it!!

**Comment by melanchall** [comment]
Thomas, any news?

**Comment by FischertBilligheim** [comment]
Hi Max, yes - this is my current implementation:

           IEnumerable<Melanchall.DryWetMidi.Interaction.Chord> chords = gActTrack.GetChords(noteTolerance);
            IEnumerable<Note> chordsNotes = null;

            foreach (Melanchall.DryWetMidi.Interaction.Chord chord in chords)
            {
                    if ( (chord.Time + chord.Length > nt && chord.Time < mt) )
                    {
                        long chordTime = chord.Time;

                        // -----------------------------------------
                        // Use extended Chord Recognition?
                        //------------------------------------------
                        if (bExtChordRecognition == true)
                        {
                            var notes= notesManager.Notes.AtTime(chord.Time, LengthedObjectPart.Entire);

                            foreach (var note in notes)
                            {
                                if (!chord.Notes.Contains(note, new NoteNumberComparer()))
                                    chord.Notes.Add(note);
                            }
                        }

                        if (chord.Notes.Count() < 3)
                            continue;

                        //------------------------------
                        // Get the musical chord...
                        //------------------------------
                        Melanchall.DryWetMidi.MusicTheory.Chord mChord = chord.GetMusicTheoryChord();
                        IReadOnlyCollection<string> musicChords = mChord.GetNames();

                        if (musicChords.Count == 0)
                            Debug.WriteLine("No chord found:" + chord.ToString());
                        else
                           utils.DrawChord(chordTime, musicChords.First().ToString(), Color.Red);

                    }
            }

I additionally implemented a NoteNumber-Comparer.

    class NoteNumberComparer : IEqualityComparer<Note>
    {
        public bool Equals(Note b1, Note b2)
        {
            if (b2 == null && b1 == null)
                return true;

            else if (b1 == null || b2 == null)
                return false;

            else if (b1.NoteNumber == b2.NoteNumber)
                return true;
            else
                return false;
        }

        public int GetHashCode(Note n)
        {
            return n.GetHashCode();
        }
    }


For my needed scenario, this works well, so I can close the issue. 
I have only one question: Can the comparison be done in a simpler way - without an own comparison-class?

**Comment by melanchall** [comment]
Hi Thomas,

> Can the comparison be done in a simpler way - without an own comparison-class?

Unfortunately no, since you use `Contains` method and custom comparison rule.

**Comment by FischertBilligheim** [comment]
Fine, thanks a lot, Max!
