### ISSUE TITLE
How to get the minimal/maximum/average velocity of all Notes in a chunk..

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#68]
How can I get the minimum/maximum/average velocity of all Notes in a chunk?

I tried:

        public static int GetMinVelocity(TrackChunk track)
        {
            var vel = track.Events
              .OfType<NoteEvent>()
              .Min()
              ?.Velocity;

            if (vel == null)
                return -1;
            else
                return (int)vel;
        }

but this does not work - comparers seem to miss. Sure, I also can run in a loop over all notes - but what would have to be implemented in my example?

**Comment by melanchall** [comment]
Hi Thomas,

`Note` is a complex object so it cannot implement `IComparable` or `IComparabale<Note>` which is required for `Min()` without selector argument. There is no single way to compare notes, so it's completely up to user.

You can either use `Min`/`Max`/`Average(n => n.Velocity)` or loop over all notes and gather all required information. Last way is obviously faster than separate calls of `Min`, `Max` and `Average`.

**Comment by FischertBilligheim** [comment]
Hi Max, thanks a lot for this Info!!
