### ISSUE TITLE
[QUESTION] How to connect a device?

### ISSUE THREAD

**Issue by Amalgamium** [melanchall/drywetmidi#70]
Hi there! I have a small problem with connecting a midi device. I tried to use GetByName and GetByID methods of InputDevice class, but it wasn't work. Where i can see the MIDI device name or it's ID(cause  0 as ID or name that a got from device manager was probably wrong argument for function) or how can i connect it by other way?

**Comment by melanchall** [comment]
Hi,

First of all, you can use `InputDevice.GetAll` to list all input devices currently connected to your computer to ensure your device is correctly recognized. From this list you can see the name of device you want to work with. After that you should be able to call `GetByName` with this name. Or you can take device from this list and continue to work with it.

`GetById` expects a number from `0` to `<devices_count> - 1`. You can get `<devices_count>` with `InputDevice.GetDevicesCount`.

Also please ensure your device is indeed **input** device in terms of the library. Example of an input device is MIDI keyboard.

**Comment by Amalgamium** [comment]
Yeah, it's probably related to my synthesizer(cause other program such FL Studio and Synthesia can't see it too).It seems like only USB adapter is connected, not actual device. But i think I can handle that. Thanks for helping!

**Comment by melanchall** [comment]
Thanks for using the library! Feel free to open new issues :)
