### ISSUE TITLE
Duplicate parts of a midi-file

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#71]
Hi Max,
What is the simplest way to duplicate e.g. all timed events of all chunks of a midi-file e.g from bar 2 and bar 3 to another place - e.g bar. 10?
Before the copy all timed events starting with bar 10 should be delayed 2 bars, so it should not be overwritten.
How would you implement that?

Thanks and best regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

I suppose something like this should work:

```csharp
var tempoMap = file.GetTempoMap();

var startTime = TimeConverter.ConvertFrom(new BarBeatTicksTimeSpan(2), tempoMap);
var endTime = TimeConverter.ConvertFrom(new BarBeatTicksTimeSpan(4), tempoMap);
var targetTime = TimeConverter.ConvertFrom(new BarBeatTicksTimeSpan(10), tempoMap);

foreach (var trackChunk in file.GetTrackChunks())
{
    using (var timedEventsManager = trackChunk.ManageTimedEvents())
    {
        var events = timedEventsManager.Events;

        foreach (var e in events.Where(ee => ee.Time >= targetTime).ToList())
        {
            e.Time += endTime - startTime;
        }

        foreach (var e in events.Where(ee => ee.Time >= startTime && ee.Time < endTime).ToList())
        {
            e.Time += targetTime - startTime;
        }
    }
}
```

**Comment by FischertBilligheim** [comment]
Hi Max,
This issue was definitively not an "issue/problem" with your great library - it was a Question how to use it. Nevertheless you spent your time to support me with that Question. Thanks really a lot for doing that and your perfect support! 
I meanwhile could realize my needed functionality based on your example - so I will close that issue.
(I think the cloning of the Events is missing in you proposal  - but as I mentioned, based on your example I could realize it....)
