### ISSUE TITLE
playback tempo problem

### ISSUE THREAD

**Issue by cvp605** [melanchall/drywetmidi#72]
when i play a midi file ,I use the following code to change the playback tempo but the speed is very slow and not correct.
I try to increase the tempo 10 times (800) it will better but also not the correct tempo.
How can i solve this problem.
Thank You very much.

midiFile.ReplaceTempoMap(TempoMap.Create(Tempo.FromBeatsPerMinute(80)));

**Comment by melanchall** [comment]
Hi,

Do you recreate playback after `ReplaceTempoMap`. For example, in this case speed of playback will not be changed:

```csharp
var playback = MidiFile.GetPlayback();
midiFile.ReplaceTempoMap(TempoMap.Create(Tempo.FromBeatsPerMinute(800)));
```

Once playback created, it's detached from the source. With this code you'll get new speed:

```csharp
var playback = MidiFile.GetPlayback();
midiFile.ReplaceTempoMap(TempoMap.Create(Tempo.FromBeatsPerMinute(800)));
playback = MidiFile.GetPlayback();
```

Also please note that you can just change speed of playback with this code:

```csharp
playback.Speed  =10;
```

It means data will be played back 10 times faster.

**Comment by cvp605** [comment]
OK ,work perfect now.
Thanks your reply.
Thank You Very much.
