### ISSUE TITLE
"Midifile" is sealed.

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#76]
Hi Max,
I wanted to derive from class „MidiFile" to add additional-infos, but that's not possible - the class "MidiFile" is sealed.

Is there a specific reason for that?

Thanks and best regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

Reason for that is MIDI file has strict specification. If you add something to it, this additional info will not be written to file or read from it (unless you use custom chunk or custom meta event).

First of all, please clarify why do you want to unseal `MidiFile`? What do you want to add to it?

**Comment by FischertBilligheim** [comment]
Hi Max,
It‘s really funny, you already mentioned my first use-case!! 😉

In my midi-editor I have an overview of all tracks ( chunks). In this View,  I can create „sections“ with a name, a color, a begin-  and endposition  in the Song. E.g „Intro“, „Refrain“, „Verse1“ etc. This info, I‘m serializing into a custom chunk.
The goal is to handle these sections as a whole in my editor (copy, insert, delete etc)
(An option for the future is to combine these sections from different Midifiles to a new Midifiles..  )

That means logically these sections belong to the Midifile - and this is the reason I wanted to derive from Midifile.

Another idea I have is to write the chords info also as a custom chunk into the Midifile.

**Comment by melanchall** [comment]
Thomas,

So what's the problem to use custom chunks? Unsealing `MidiFile` looks not good right now.

**Comment by FischertBilligheim** [comment]
By the way: This is the current usage of the sections….
![image](https://user-images.githubusercontent.com/20623089/74774150-7aac3e00-5293-11ea-95b6-fbb6d3fc5f89.png)

To answer your question:
It's not a problem, sure.  But in my understanding, such things like the mentioned sections belong to the "MidiFile" object. I'm using instances of a midifile in my Code - and it would make sense to address the sections directly with the midifile-instance. I currently need to handle the sections of a midifile in parallel to the midifile - specially in the case of handling multiple midifiles in parallel, it would be more intuitive to do with the midifile-object.

I surely can also use Aggregation and not Inheritance - because of that I was only asking about the reasons for sealing....   :-)

**Comment by melanchall** [comment]
Thomas,

`MidiFile` is sealed because of strict MIDI file spec as I said. If you add, for example, some custom property to this class, it won't be MIDI file anymore. I suggest to use either aggregation (as you've mentioned) or custom chunk. Using custom chunk, in my opinion, as simple as custom `MidiFile`:

Instead of

```csharp
var sections = midiFile.Sections;
```

you just need to write:

```csharp
var sections = midiFile.Chunks.OfType<SectionsChunk>().First().Sections;
```

Some longer but pretty simple anyway. You wrote:

> it would make sense to address the sections directly with the midifile-instance

Using custom chunk you access sections _"directly with the midifile-instance"_ :)

**Comment by FischertBilligheim** [comment]
Fine, thanks a lot, Max!
I will find a solution!!
Best regards
Thomas

**Comment by FischertBilligheim** [comment]
Topic can be closed.
