### ISSUE TITLE
System.UnauthorizedAccessException while MidiFile.Read in UWP app.

### ISSUE THREAD

**Issue by abhinovpankaj** [melanchall/drywetmidi#80]
I am trying to use this MidiFile.Read method to read a midifile saved in my downloads folder, but it throws System.UnauthorizedAccessException .

**Comment by melanchall** [comment]
Hi,

First of all, this exception is no a bug of the library. In documentation for [Read](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.MidiFile.html#Melanchall_DryWetMidi_Core_MidiFile_Read_System_String_Melanchall_DryWetMidi_Core_ReadingSettings_) method you can see that `UnauthorizedAccessException` can be thrown in following cases:

* This operation is not supported on the current platform
* `filePath` specified a directory
* The caller does not have the required permission

Exception is thrown on reading a file. You'll get this exception with every standard .NET method. For example. try to call [File.ReadAllBytes](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readallbytes).

Also try to read another file in the same directory.

Also it's worth a try to use [StorageFile](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile). Please read related question on Stack Overlow: [c# - UWP - UnauthorizedAccessException on file included in project](https://stackoverflow.com/questions/32530370/c-sharp-uwp-unauthorizedaccessexception-on-file-included-in-project). Using methods from the `StorageFile` you can get stream of file and read MIDI file from that stream.

**Comment by melanchall** [comment]
@abhinovpankaj Did you solve the problem?

**Comment by abhinovpankaj** [comment]
I thin this is related to how files are read in UWP. I can read the files in the same folder using any other project like WPF. I will try StorageFile and I think that should solve the issue.
Thanks

**Comment by melanchall** [comment]
Please try `StorageFile` and let me know if you successfully read a MIDI file :)

**Comment by melanchall** [comment]
Any news?

**Comment by melanchall** [comment]
I'm closing the issue. Please reopen it if you have any questions or noticed a bug.
