### ISSUE TITLE
[Feature] EventPlayed to trigger on timed meta events

### ISSUE THREAD

**Issue by MusicalMiqo** [melanchall/drywetmidi#82]
Is it possible for the EventPlayed event handler from the Playback class be made to trigger on timed meta events i.e. lyric events? It would be of great convenience as I wasn't able to find another method to handle lyrics during playback. Thanks!

**Comment by melanchall** [comment]
Hi,

Nice feature suggestion :) Thanks! I'll implement it.

**Comment by MusicalMiqo** [comment]
Thank you so much!

**Comment by melanchall** [comment]
Now `EventPlayed` event will be fired for meta events too. Please take latest code from _develop_ branch and let me know if it's OK.

**Comment by MusicalMiqo** [comment]
Yes, the EventPlayed event is triggering correctly on lyric events.
