### ISSUE TITLE
Set MIDI Instrument to Tracks

### ISSUE THREAD

**Issue by ragrr4** [melanchall/drywetmidi#9]
Hi!

Is there a way to set the MIDI instrument to the Track?

**Comment by melanchall** [comment]
Hi!

You have several options.

**Program number**

Add `ProgramChangeEvent` at the start of `TrackChunk` with a number of desired program:

```csharp
TrackChunk trackChunk = ...;
trackChunk.Events.Insert(0, new ProgramChangeEvent((SevenBitNumber)45));
```

**General MIDI Level 1 program number**

It is the same option as previous one but you use `GeneralMidiProgram` enum placed in `Melanchall.DryWetMidi.Standards` namespace:

```csharp
using Melanchall.DryWetMidi.Standards;

TrackChunk trackChunk = ...;
trackChunk.Events.Insert(0, GeneralMidiProgram.BrightAcousticPiano.GetProgramEvent());
```

**General MIDI Level 2 program**

For GM2 you should insert several events. Example:

```csharp
using Melanchall.DryWetMidi.Standards;

TrackChunk trackChunk = ...;
trackChunk.Events.InsertRange(0, GeneralMidi2Program.ElectricGuitarDetunedClean.GetProgramEvents());
```

But I'm not sure that all software supports GM2 events sequences in MIDI files so I recommend to use first two approaches.

**Comment by ragrr4** [comment]
Thanks for take the time to answer 👍 

It worked perfectly
