### ISSUE TITLE
Device Connect & StartEventsListening bug

### ISSUE THREAD

**Issue by MuElhusseiny** [melanchall/drywetmidi#90]
im working with c# wpf when i use device connect & StartEventsListening  to routing my midi keyboard to Virtual Output port Working fine but when i press another buttons or radio buttons after 5 times connection was lost how i can fix it !?

My Code
                var inputDevice = Melanchall.DryWetMidi.Devices.InputDevice.GetByName(Keyboard.SelectedItem.ToString());
                var outputDevice = OutputDevice.GetByName("Keyboard");
                var devicesConnector = inputDevice.Connect(outputDevice);
                inputDevice.StartEventsListening();

Thanks

**Comment by melanchall** [comment]
Hi,

Please provide more info.

> when i press another buttons or radio buttons after 5 times connection was lost

What buttons? What's the code inside them?

Also please keep in mind following rules:

* You must save references to input device, outpurt device and devices connector to fields of class, not local variables of some method, because when a program exits a method, all its variables will be marked as ready to be killed by garbage collector.
* You must dispose all devices objects after you're done with them.

Can you please send me your Visual Studio solution so I can point to problem places?

**Comment by MuElhusseiny** [comment]
k thanks for fast replay

What buttons? What's the code inside them?

Buttons, Radiobuttons, Checkboxes
Hide & Show Objects 
and i need to be connected all the time
--------------------------------------------
connection code inside my button
        private void keysave_Click(object sender, RoutedEventArgs e)
        {
           
                var inputDevice = Melanchall.DryWetMidi.Devices.InputDevice.GetByName(Keyboard.SelectedItem.ToString());
                var outputDevice = OutputDevice.GetByName("Keyboard");
                var devicesConnector = inputDevice.Connect(outputDevice);
                inputDevice.StartEventsListening();
}

When I am on the connection page it still works but when I press any button 5 more times the connection is lost.

i need to be connected all the time

sorry for my bad English

**Comment by melanchall** [comment]
Thanks for the info. You have the first problem I've described in my comment:

> You must save references to input device, outpurt device and devices connector to fields of class, not local variables of some method, because when a program exits a method, all its variables will be marked as ready to be killed by garbage collector.

Devices are resources that can be (and will be) released if you don't keep them in long-live references like fields. That's what's going on in your program:

1. The program enters `keysave_Click` method
2. All devices initialized and saved to local variables
3. The program exits `keysave_Click` method
4. Now all your local variables (like `inputDevice`) can be killed from CLR's point of view
5. After some undetermined amount of time CLR will kill your objects via garbage collector

Please try this:

```csharp
private InputDevice _inputDevice;
private OutputDevice _outputDevice;
private DevicesConnector _devicesConnector;

private void keysave_Click(object sender, RoutedEventArgs e)
{
    _inputDevice?.Dispose();
    _inputDevice = Melanchall.DryWetMidi.Devices.InputDevice.GetByName(Keyboard.SelectedItem.ToString());
    
    _outputDevice?.Dispose();
    _outputDevice = OutputDevice.GetByName("Keyboard");

    _devicesConnector = inputDevice.Connect(outputDevice);
    _inputDevice.StartEventsListening();
}
```

**Comment by MuElhusseiny** [comment]
_inputDevice?.Dispose();
got error 
changed to               
_inputDevice.Dispose();

but program crashed

object references not set

**Comment by melanchall** [comment]
OK, instead of `_inputDevice?.Dispose();` write:

```csharp
if (_inputDevice != null)
    _inputDevice.Dispose();
```

I thought you work with at least C# 6 so you have `?.` feature.

**Comment by MuElhusseiny** [comment]
very thanks works fine 

    private Melanchall.DryWetMidi.Devices.InputDevice _inputDevice;
            private OutputDevice _outputDevice;
            private DevicesConnector _devicesConnector;
  if (_inputDevice != null)
                    _inputDevice.Dispose();
              _inputDevice = Melanchall.DryWetMidi.Devices.InputDevice.GetByName(Keyboard.SelectedItem.ToString());
              if (_outputDevice != null)
                  _outputDevice.Dispose();
              _outputDevice = OutputDevice.GetByName("Keyboard");

                _devicesConnector = _inputDevice.Connect(_outputDevice);
                _inputDevice.StartEventsListening();
