### ISSUE TITLE
General Sound Percussion Set ?

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#93]
Hello Max,

what about the idea to add - additionally to GM and GM2-Percussion sets - also a "GeneralSound" Percussion map?
The "General Sound Percussion map" has one additional entry to GM2:
The "CM64/32" percusion set.

If you are interested you can add the following folder to the "Standards" folder of DryWetMidi: 

[GeneralSound.zip](https://github.com/melanchall/drywetmidi/files/5184563/GeneralSound.zip)

Best regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

Yes, adding API to support GS standard looks interesting. Thanks for the code. I'll examine it and add new API as I have free time. Unfortunately right now I have a lot of work on my main job :(

Thanks,
Max

**Comment by melanchall** [comment]
@FischertBilligheim I've added GS percussion API.

**Comment by melanchall** [comment]
@FischertBilligheim Can the issue be closed?
