### ISSUE TITLE
Edit/Delete/Save OTS chunks

### ISSUE THREAD

**Issue by valimaties** [melanchall/drywetmidi#94]
Hi.
After I was able to read custom OTS Chunk, I must Clone - Edit that Chunk and write to another midi file, replacing existing OTS Chunk in new midi file with edited one.
There is also a need to empty one or more MTrk which are TrackChunks inside OTSChunk.
After I will empty/edit one or more tracks, I want to save modified chunks to file opened or to another one.

**Comment by melanchall** [comment]
Hi,

Thanks for the issue.

I need to implement some features in the library to give you ability to write chunks easily. I'll let you know when I'm finished with new API.

**Comment by valimaties** [comment]
Great news!
Thanks 🤗

**Comment by melanchall** [comment]
I've added `WriteHeaderChunk` property to `WritingSettings`. This new API is not released yet so you need either build the library from sources by yourself or take DLL from here: [DryWetMIDI.5.2.0-bin-net45.zip](https://github.com/melanchall/drywetmidi/files/5239394/DryWetMIDI.5.2.0-bin-net45.zip).

First of all, full `OtsChunk` implementation:

```csharp
public sealed class OtsChunk : MidiChunk
{
    public const string Id = "OTSc";

    public OtsChunk()
        : base(Id)
    {
    }

    public IList<TrackChunk> TrackChunks { get; private set; }

    protected override void ReadContent(MidiReader reader, ReadingSettings settings, uint size)
    {
        var data = reader.ReadBytes((int)size);

        using (var memoryStream = new MemoryStream(data))
        {
            var midiFile = MidiFile.Read(memoryStream, new ReadingSettings
            {
                NoHeaderChunkPolicy = NoHeaderChunkPolicy.Ignore
            });

            TrackChunks = midiFile.GetTrackChunks().ToList();
        }
    }

    public override MidiChunk Clone()
    {
        return new OtsChunk
        {
            TrackChunks = TrackChunks.Select(c => (TrackChunk)c.Clone()).ToList()
        };
    }

    protected override uint GetContentSize(WritingSettings settings)
    {
        return (uint)GetData().Length;
    }

    protected override void WriteContent(MidiWriter writer, WritingSettings settings)
    {
        var data = GetData();
        writer.WriteBytes(data);
    }

    private byte[] GetData()
    {
        var midiFile = new MidiFile(TrackChunks);

        using (var memoryStream = new MemoryStream())
        {
            midiFile.Write(memoryStream, settings: new WritingSettings
            {
                WriteHeaderChunk = false
            });

            return memoryStream.ToArray();
        }
    }
}
```

So you read a file like this:

```csharp
var midiFile = MidiFile.Read("LionelRichie Hello_Amkey_TY.sty", new ReadingSettings
{
    CustomChunkTypes = new ChunkTypesCollection
    {
        { typeof(OtsChunk), OtsChunk.Id }
    }
});
```

After that you can take `OtsChunk` from the file:

```csharp
var otsChunk = midiFile.Chunks.OfType<OtsChunk>().FirstOrDefault();
```

Then you can manage `TrackChunks` of `otsChunk`. `TrackChunk` has `Events` property which returns `EventsCollection` that allows you to do what you want with a track chunk's events.

For example, to remove all events from second track chunk

```csharp
otsChunk.TrackChunks[1].Events.Clear();
```

To remove first track chunk:

```csharp
otsChunk.TrackChunks.RemoveAt(0);
```

Or you can add new track chunk:

```csharp
otsChunk.TrackChunks.Add(new TrackChunk(new NormalSysExEvent(new byte[] { 0x45, 0x56 })));
```

So do with track chunks and their events whatever you want :)

And finally to write file back to the original one:

```csharp
midiFile.Write("LionelRichie Hello_Amkey_TY.sty", true);
```

or to a new file:

```csharp
midiFile.Write("new.sty");
```

**Comment by valimaties** [comment]
I have test it and it works like a charm!
Thank you very much!

PS: One suggestion! 
An **Write()** event, without any parameter could be implemented, and this means it will overwrite file loaded!
**Write(string filePath, bool overWrite = false)** it works if you want to give a path for a new file and file already exists! 
But if you only want to rewrite opened file, I don't see the redundant filePath and overwrite bool parameter!

Best regards,
Vali

**Comment by melanchall** [comment]
From my point of view it's dangerous to provide `Write` method without path. User can occasionally rewrite a file. Also `MidiFile` can be created from scratch so what `Write()` should do? In my opinion `Write` without parameters creates questions rather than benefit :)

So can the issue be closed?

**Comment by valimaties** [comment]
Ok. Thanks for details!
Yes, I will close it!

Cheers!

**Comment by valimaties** [comment]
A problem. 
I have tested this only for OTS chunk. But seems Midi data in file will not be read anymore. Where to be the problem, in file header? 
I can find the OTS in new file, but the file itself is not readable by keyboard anymore!

**Comment by valimaties** [comment]
To replace OTS in new file, with one I choose from choosen file, I used:

```cs
otsChunk2.TrackChunks.RemoveAt(j);
otsChunk2.TrackChunks.Insert(j, ((ViewModel)DataContext).OTSes[j].RawDataOTS);

Where RawDataOTS is of type TrackChunk

**Comment by valimaties** [comment]
![Differencies](https://user-images.githubusercontent.com/49796453/95075153-6761bc00-0718-11eb-869f-23d6991b2376.jpg)

There are differences between files, before (left) and after (right) saving!

**Comment by melanchall** [comment]
Can you please describe the problem in more details?

1. What file did you modify?
2. What's wrong with modified file?
3. On your screenshot files are with _prs_ extension. I don't know what a file it is.

**Comment by valimaties** [comment]
Hi Maxim.
As you can see from the picture, the file in the left part is unmodified style file (explain above).  In the right part, there is same file after I changed OTS Chunk's track chunks, using Write function. The thing is OTS Chunk is ok. The rest of file is not ok. Something is changed from the original. [This](http://www.mediafire.com/file/2n01zu63c6i74ef/Ballroom.zip) is a zip folder with style files, with different extensions. From the documentation, all files have the same structure, no matter extension. Extension is a "filter" for different type of keyboards (old or new).

Maybe I don't do what I have to do... My code:

```cs
foreach (SelectableViewModel svm in ((ViewModel)DataContext).Items)
            {
                if (svm.IsSelected == false) continue;
                try
                {
                    var newMidiFile = MidiFile.Read(svm.FilePath, new ReadingSettings
                    {
                        CustomChunkTypes = new ChunkTypesCollection
                        {
                            { typeof(OtsChunk), OtsChunk.Id }
                        }
                    });
                    var otsChunk2 = newMidiFile.Chunks.OfType<OtsChunk>().FirstOrDefault();
                    for (int t = 0; t < 4; t++)
                    {
                        bool sel = false;
                        switch (t)
                        {
                            case 0:
                                sel = ((ViewModel)DataContext).OTS1Selected;
                                break;
                            case 1:
                                sel = ((ViewModel)DataContext).OTS2Selected;
                                break;
                            case 2:
                                sel = ((ViewModel)DataContext).OTS3Selected;
                                break;
                            case 3:
                                sel = ((ViewModel)DataContext).OTS4Selected;
                                break;
                        }
                        if (((ViewModel)DataContext).OTSes[t].RawDataOTS != null && ((ViewModel)DataContext).OTSes[t].RawDataOTS.Events.Count > 0 && sel)
                        {
                            try
                            {
                                otsChunk2.TrackChunks.RemoveAt(t);
                            }
                            catch (Exception) 
                            { 
                                Debug.WriteLine($"Error removing OTS {t + 1}"); 
                                return false;
                            }
                            otsChunk2.TrackChunks.Insert(t, ((ViewModel)DataContext).OTSes[t].RawDataOTS);
                        }
                        else
                        {
                            if (chkEmptyNonSelectedOTSes.IsChecked == true)
                            {
                                otsChunk2.TrackChunks[t].Events.Clear();
                            }
                        }
                    }
                    newMidiFile.Write(svm.FilePath, true);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine($"Error in OTS job \n{ex.Message}");
                }
            }
```

**Comment by melanchall** [comment]
Thanks.

I confirm that the structure of your files is lost on `Write`. I'll examine the issue and let you know about what's going on and how to fix it.

**Comment by melanchall** [comment]
OK, I found what's going on.

In your files you have first chunk of `TrackChunk` type. But when you call `Write` specifying `MultiTrack` file format (by default) DryWetMIDI restructures all track chunks so each one contains events only for single MIDI channel. So your first track chunk explodes into seventeen (16 for each MIDI channel and one for tempo map events) separate track chunks and thus you have 20 chunks in new file instead of 4 in original one.

It's not an error for regular MIDI files. It's just another representation of data.

@valimaties Is it an issue for your files that first track chunk gets exploded into several ones?

**Comment by valimaties** [comment]
Yes. I have to retain the original structure file!

**Comment by melanchall** [comment]
Well, in this case I need to create new setting within `ReadingSettings`. I 'll let you know when new API is implemented.

**Comment by valimaties** [comment]
Ok, thank you very much!
I appreciate that!

**Comment by melanchall** [comment]
Oh, in your case there is a simple solution right now. Just write file with the same format as original one:

```csharp
newMidiFile.Write(svm.FilePath, true, newMidiFile.OriginalFormat);
```

**Comment by valimaties** [comment]
> Oh, in your case there is a simple solution right now. Just write file with the same format as original one:
> 
> ```cs
> newMidiFile.Write(svm.FilePath, true, newMidiFile.OriginalFormat);
> ```

Solved ;)

**Comment by valimaties** [comment]
Hi Maxim.
I reopened this issue, because `OriginalFormat` will not do very good things on every file, as there are some files which will be written as MultiTrack, so when I will write it back, OriginalFormat is MultiTrack, and will explode Track in those 17 tracks...
Maybe there are some other things to do!
Thanks.

**Comment by valimaties** [comment]
It is not ok.
After I save the file, new created file has a bigger size.

For tests, I upload a file. Copy it to a new one. Select OTS chunks 0 and 1 and replace them in the second file. 
First file has 57353 bytes, second, after save it, will have 60788 bytes. 

[Beguine_G.T158.prs.zip](https://github.com/melanchall/drywetmidi/files/5500770/Beguine_G.T158.prs.zip)

**Comment by melanchall** [comment]
Hi,

> Select OTS chunks 0 and 1 and replace them in the second file

Sorry but I don't understand you. Replace with what? What exactly should I do?

In your file I see only one OTS chunk:

![image](https://user-images.githubusercontent.com/26361185/98390545-93999100-2066-11eb-804e-eef3ae9869d4.png)

If I just save original file to the new one with `SingleTrack` format, I'll get a file with greater size. But there is nothing wrong with this. I suppose it's due to DryWetMIDI by defualt writes MIDI files without running status and inserts all entites required by MIDI file specs. If you want, you can turn running status on:

```csharp
midiFile.Write(
    @"Beguine_G.T158_copy.prs",
    true,
    MidiFileFormat.SingleTrack,
    new WritingSettings
    {
        CompressionPolicy = CompressionPolicy.UseRunningStatus
    });
```

With this code the size of the file will be almost the same as original one.

**Comment by valimaties** [comment]
Hi Maxim.
Why CompressionPolicy shows as deprecated? It's ok?

**Comment by melanchall** [comment]
Yes, that's OK. There will be new API in the next release so I marked `CompressionPolicy` as obsolete.

**Comment by valimaties** [comment]
Ok.. Before I close it I must made some tests! :)

**Comment by valimaties** [comment]
Hi Maxim.
As I said, something is not ok...

Take as example the style I give to you.
OTS Chunk contains 4 track chunks.
and let's see some code:

```cs
     // myFile = myStyle.prs; myFile2=myStyleCopy.prs

     var newMidiFile = MidiFile.Read(myFile, new ReadingSettings
                    {
                        CustomChunkTypes = new ChunkTypesCollection
                        {
                            { typeof(OtsChunk), OtsChunk.Id }
                        }
                    });
    var otsChunk = newMidiFile.Chunks.OfType<OtsChunk>().FirstOrDefault();
    var newMidiFile2 = MidiFile.Read(myFile2, new ReadingSettings
                    {
                        CustomChunkTypes = new ChunkTypesCollection
                        {
                            { typeof(OtsChunk), OtsChunk.Id }
                        }
                    });
    var otsChunk2 = newMidiFile2.Chunks.OfType<OtsChunk>().FirstOrDefault();
    
    // remove first and second track chunks from otsChunk2 and insert first and second track chunks from otsChunk
    // practically, I don't change the file at all, I replace a track chunk with the same track chunk, 
    // but from its original file
    otsChunk2.TrackChunks.RemoveAt(0);
    otsChunk2.TrackChunks.RemoveAt(1);
    otsChunk2.TrackChunks.Insert(0, otsChunk.TrackCunks[0]);
    otsChunk2.TrackChunks.Insert(1, otsChunk.TrackCunks[1]);
    newMidiFile2.Write(
                        myFile2, 
                        true, 
                        MidiFileFormat.SingleTrack, 
                        new WritingSettings
                        {
                            CompressionPolicy = CompressionPolicy.UseRunningStatus
                        }
                    );
```
The structure of Truck Chunk from the beginning of the copied file is different than Truck Chunk from the unmodified file! Why?
I opened both files with NotePad++ Compare plugin and these are :

![MidiStructureProblem](https://user-images.githubusercontent.com/49796453/98445004-de2a1480-211d-11eb-9d06-7b8ce2c0540d.png)


So, I think the midi part of this file (first TruckChunk) is modified at `Read` or at `Write`, even if I don't do anything to that part of file!

Some ideas?

**Comment by melanchall** [comment]
First of all, you have an error here

```csharp
otsChunk2.TrackChunks.RemoveAt(0);
otsChunk2.TrackChunks.RemoveAt(1);
```

After first line **the previous second chunk becomes first one**. So in fact you're removing first and **third** chunks and thus change order of chunks after inserting new ones. If you want to remove first and second you need to call `RemoveAt(0)` two times:

```csharp
otsChunk2.TrackChunks.RemoveAt(0);
otsChunk2.TrackChunks.RemoveAt(0);
```

Regarding difference at the start of first MTrk chunk I'll answer later.

**Comment by melanchall** [comment]
@valimaties Despite of different binary content, do you see any issues with new file?

**Comment by valimaties** [comment]
Yes Maxim, indeed, removing consecutively, it is an error, those for lines must be intercalated
```
    otsChunk2.TrackChunks.RemoveAt(0);
    otsChunk2.TrackChunks.Insert(0, otsChunk.TrackCunks[0]);
    otsChunk2.TrackChunks.RemoveAt(1);
    otsChunk2.TrackChunks.Insert(1, otsChunk.TrackCunks[1]);
```

As, if I see issues, I don't know yet. I have to dig much more in midi track as well, using style manual, and to parse that midi track to see if there are differences.

**Comment by melanchall** [comment]
First of all, I've created simple program:

```csharp
var customChunkTypes = new ChunkTypesCollection
{
    { typeof(OtsChunk), OtsChunk.Id }
};

//

var midiFile1 = MidiFile.Read("Beguine_G.T158.prs", new ReadingSettings
{
    InvalidChunkSizePolicy = InvalidChunkSizePolicy.Abort,
    CustomChunkTypes = customChunkTypes
});
var otsChunk1 = midiFile1.Chunks.OfType<OtsChunk>().First();

//

var midiFile2 = MidiFile.Read("Beguine_G.T158_copy.prs", new ReadingSettings
{
    CustomChunkTypes = customChunkTypes
});
var otsChunk2 = midiFile2.Chunks.OfType<OtsChunk>().First();
otsChunk2.TrackChunks.RemoveAt(0);
otsChunk2.TrackChunks.RemoveAt(0);
otsChunk2.TrackChunks.Insert(0, otsChunk1.TrackChunks[0]);
otsChunk2.TrackChunks.Insert(1, otsChunk1.TrackChunks[1]);

midiFile2.Write(
    "Beguine_G.T158_copy_rewritten.prs",
    true,
    MidiFileFormat.SingleTrack,
    new WritingSettings
    {
        CompressionPolicy = CompressionPolicy.UseRunningStatus
    });

//

midiFile2 = MidiFile.Read("Beguine_G.T158_copy_rewritten.prs", new ReadingSettings
{
    InvalidChunkSizePolicy = InvalidChunkSizePolicy.Abort,
    CustomChunkTypes = customChunkTypes
});
otsChunk2 = midiFile2.Chunks.OfType<OtsChunk>().First();
```

So we replace first two track chunks of OTS chunk, write file _Beguine_G.T158.prs_ to _Beguine_G.T158_copy_rewritten.prs_ and read new file.

Now let's compare all track chunks of original file and rewritten one:

```csharp
var firstTrackChunksEqual = MidiChunk.Equals(
    (TrackChunk)midiFile1.Chunks.First(),
    (TrackChunk)midiFile2.Chunks.First());
Console.WriteLine($"First track chunk of original and rewritten files are equal: {firstTrackChunksEqual}");

//

for (var i = 0; i < 4; i++)
{
    var otsTrackChunksEqual = MidiChunk.Equals(otsChunk1.TrackChunks[i], otsChunk2.TrackChunks[i]);
    Console.WriteLine($"Track chunk #{i} of OTS chunk of original and rewritten files are equal: {otsTrackChunksEqual}");
}
```

If we run the program, we'll see following output:

```
First track chunk of original and rewritten files are equal: True
Track chunk #0 of OTS chunk of original and rewritten files are equal: True
Track chunk #1 of OTS chunk of original and rewritten files are equal: True
Track chunk #2 of OTS chunk of original and rewritten files are equal: True
Track chunk #3 of OTS chunk of original and rewritten files are equal: True
```

What does it mean? It means that content of all track chunks in rewritten file is the same as in original one. Both files are semantically identical, they contain the same MIDI events. Thus new file is absolutely correct and will be played and processed by any MIDI player or MIDI program in the same way. So new file is absolutely correct and equals to the original one.

Yes, files have differencies in binary view. But there are a lot of possible reasons. For example, original file may use running status in some places and don't use in others. It's OK and not prohibited by MIDI spec. But DryWetMIDI always writes MIDI data in single valid way. If we tell it to use running status (via `CompressionPolicy`), the running status will be used everywhere in MIDI file where possible.

More than that, we use running status only to write root content of the file. The policy will not be applied to track chunks of OTS chunk. To get bytes of OTS chunk, we used code like that:

```csharp
public static byte[] GetChunksData(IEnumerable<MidiChunk> chunks)
{
    var midiFile = new MidiFile(chunks);

    using (var memoryStream = new MemoryStream())
    {
        midiFile.Write(memoryStream, settings: new WritingSettings
        {
            WriteHeaderChunk = false,
        });

        return memoryStream.ToArray();
    }
}
```

As you can see, we don't specify `CompressionPolicy` here, but we can. If we use it, we'll get another binary representation. But all of those representations are correct and contains the same MIDI data.

In my opinion, analyzing bytes of correct files not worth it. Again, there are a lot of nuances in MIDI that can change binary content of a MIDI file.

**Comment by valimaties** [comment]
OK.
Thanks a lot Maxim! 
Right now I will close this issue and I hope not to open again
👍 🥇
