### ISSUE TITLE
Unresolved P/Invoke method 'winmm.dll!midiOutGetNumDevs' in UWP app

### ISSUE THREAD

**Issue by melanchall** [melanchall/drywetmidi#95]
Copied from [the comment](https://github.com/melanchall/drywetmidi/issues/29#issuecomment-695232923):

> I noticed OutputDevice.GetByName("Microsoft GS Wavetable Synth"); in UWP apps in debug mode works, but release mode fails with "'Unresolved P/Invoke method 'winmm.dll!midiOutGetNumDevs' from this method. Please look for this method in build warnings for more details. '" as UWP has a dedicated abstraction to be used https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi
> 
> A means to use existing cross-platform libraries would be great, or a way to add support for other platforms by app developers.

**Comment by melanchall** [comment]
I've fixed the issue. Changes are not released yet. You can either build the library from sources from _develop_ branch, or take DLL from here: [DryWetMIDI.5.2.0-bin-net45.zip](https://github.com/melanchall/drywetmidi/files/5256751/DryWetMIDI.5.2.0-bin-net45.zip).

I did some testing and results are pretty interesting.

First of all, I have these devices in my system (all are virtual ones):

```
Microsoft GS Wavetable Synth
LoopBe Internal MIDI
Game Controller 1
01. Internal MIDI
02. Internal MIDI
MIDI A
MIDI B
MIDI C
Keyboard
```

If I use DryWetMIDI in .NET framework or .NET Core app, I see all these devices with exact names. But if I use DryWetMIDI in UWP app (after fix) I see:

```
Microsoft GS Wavetable Synth
```

So it looks like all non-standard virtual devices are not listed.

But much more interesting is what UWP native API (from link you've provided) shows:

```
MIDI
MIDI
02. Internal MIDI [1]
Программный синтезатор звуковой таблицы Microsoft
MIDI
01. Internal MIDI [1]
MIDI
MIDI
LoopBe Internal MIDI [1]
```

Hmm, that's not what I expect... `Программный синтезатор звуковой таблицы Microsoft` is `Microsoft GS Wavetable Synth` in Russian. I don't know why Microsoft decided to localize it in UWP API. Also all remaining devices have wrong names. So I definitely won't use UWP API in DryWetMIDI.

Anyway, the problem is fixed now :) Thanks for the issue!

**Comment by andreasbalzer** [comment]
Thank you very much for fixing this issue.
