### ISSUE TITLE
Not sending SMPTE midi when sent

### ISSUE THREAD

**Issue by EsaiasTilly** [melanchall/drywetmidi#96]
Hi! I'm trying to send SMPTE timecode to an OutputDevice, but I cannot get it to work. When I do `device.SendEvent(new NoteOnEvent());` it sends the data which I can see in loopMidi, but when I try to create a SmpteOffsetEvent send send that it does nothing.

```C#
OutputDevice device = OutputDevice.GetById(midiDeviceId);
device.EventSent += Device_EventSent;
SmpteOffsetEvent ev = new SmpteOffsetEvent();
ev.Format = SmpteFormat.Thirty;
ev.Frames = Convert.ToByte(5);
ev.Hours = Convert.ToByte(5);
ev.Minutes = Convert.ToByte(5);
ev.Seconds = Convert.ToByte(5);
device.SendEvent(ev);
device.SendEvent(new NoteOnEvent());
```

I don't event get any call to the EventSent that anything has been sent at all.
Is there something I'm missing?

**Comment by melanchall** [comment]
Hi,

`SmpteOffsetEvent` is a meta event and can't be sent to device. Meta events are for MIDI files only. Can you please say what event do you want to send? Maybe you can provide a link to article about the event?

**Comment by melanchall** [comment]
@EsaiasTilly Any info?

**Comment by EsaiasTilly** [comment]
Oh, sorry. Thank you for the fast reply! What I want to do is send out MTC (MidiTimeCode) with SMPTE format to other programs (in my case Grand MA 2 onPC).

**Comment by melanchall** [comment]
Right now the only way is to send [`MidiTimeCodeEvent`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Core.MidiTimeCodeEvent.html) events where each one will represent part of MTC. But I'll implement helper method to allow just specify hours, minutes and so on and all required events will be sent internally for you. Thanks for the issue! Please don't close it, I'll implement new API within it.

**Comment by EsaiasTilly** [comment]
@melanchall Oh. Thank you! Sounds great!

**Comment by melanchall** [comment]
Hmm, I see there are different MTC events: http://midi.teragonaudio.com/tech/mtc.htm. @EsaiasTilly what one do you want exactly?

**Comment by EsaiasTilly** [comment]
@melanchall I need Full-Frame

**Comment by melanchall** [comment]
From the link I've provided, Full Frame event is just a sysex one:

> F0 7F **cc** 01 01 **hr mn sc fr** F7
> ...
> **cc** is the SysEx channel (0 to 127). It is suggested that a device default to using its Manufacturer's SysEx ID number for this channel, giving the musician the option of changing it. Channel number 0x7F is used to indicate that all devices on the daisy-chain should recognize this Full Frame message.
> ...
> The **hr**, **mn**, **sc**, and **fr** are the hours, minutes, seconds, and frames of the current SMPTE time. The hours byte also contains the SMPTE Type as per the Quarter Frame's Hours High Nibble message.

So to send a Full Frame event in DryWetMIDI:

```csharp
device.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, cc, 0x01, 0x01, hr, mn, sc, fr, 0xF7 }));
```

So just provide desired values for all the variables. Pay attention to **hr**:

> The hours byte also contains the SMPTE Type as per the Quarter Frame's Hours High Nibble message.

**Comment by melanchall** [comment]
@EsaiasTilly Did you solve your task?

**Comment by EsaiasTilly** [comment]
@melanchall I haven't had an opportunity to try it yet. But thank you for helping!

**Comment by EsaiasTilly** [comment]
Here's how I tried to implement it, but it is not recogniced as timecode by either my own program or Grand MA. I'm not sure if I did the right thing with cc and hr, but I think I did.

```C#
// Convert Into Time
int iHr = (int)Math.Floor(timer.ElapsedMilliseconds / 1000d / 60d / 60d);
int iMn = (int)Math.Floor(timer.ElapsedMilliseconds / 1000d / 60d - (iHr * 60d));
int iSc = (int)Math.Floor(timer.ElapsedMilliseconds / 1000d - (iHr * 60d * 60d) - (iMn * 60d));
int iFr = (int)Math.Floor((timer.ElapsedMilliseconds - (iHr * 60d * 60d * 1000d) - (iMn * 60d * 1000d) - (iSc * 1000d)) / 33.3333334d);

// Convert Time Into Bytes
byte hr = Convert.ToByte(iHr);
byte mn = Convert.ToByte(iMn);
byte sc = Convert.ToByte(iSc);
byte fr = Convert.ToByte(iFr);

// Send SysEx Event
device.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x01, 0x01, hr, mn, sc, fr, 0xF7 }));```

**Comment by melanchall** [comment]
@EsaiasTilly What is `timer`? It seems you do a lot of redundant work.

**Comment by EsaiasTilly** [comment]
`timer` is just a simple `System.Diagnostics.Stopwatch` I used to track the time.

**Comment by melanchall** [comment]
[`Stopwatch`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch) has `Elapsed` property which returns [`TimeSpan`](https://docs.microsoft.com/en-us/dotnet/api/system.timespan). `TimeSpan` has `Hours`, `Minutes`, `Seconds`, `Milliseconds` properties:

```csharp
var elapsed = timer.Elapsed;

var hours = (byte)elapsed.Hours;
var minutes = (byte)elapsed.Minutes;
var seconds = (byte)elapsed.Seconds;
```

To calculate frames number we need to know SMPTE format. It can be one the following ones:

```
24 fps
25 fps
30 fps (Drop-Frame)
30 fps
```

What format do you use?

**Comment by EsaiasTilly** [comment]
30 FPS

**Comment by melanchall** [comment]
Please try this code:

```csharp
var elapsed = timer.Elapsed;

var hours = (byte)elapsed.Hours;
var minutes = (byte)elapsed.Minutes;
var seconds = (byte)elapsed.Seconds;
var frames = (byte)(elapsed.Milliseconds * 30 / 1000);

var format = 3;
var formatAndHours = (byte)((format << 5) + hours);

device.SendEvent(new NormalSysExEvent(new byte[] { 0x7F, 0x7F, 0x01, 0x01, formatAndHours, minutes, seconds, frames, 0xF7 }));
```

**Comment by melanchall** [comment]
@EsaiasTilly How it's going?

**Comment by EsaiasTilly** [comment]
@melanchall  I'll try it as soon as I can.

**Comment by EsaiasTilly** [comment]
@melanchall Still no timecode gets recognized by Grand MA 2. I've found another solution though.

**Comment by melanchall** [comment]
I suppose it's a feature of Grand MA 2 that it doesn't recognize those events. What solution did you find?

**Comment by EsaiasTilly** [comment]
@melanchall I'm sending the timecode using another program and reading it from my program instead of sending it. So my program is triggered from MTC instead of sending the MTC.

**Comment by melanchall** [comment]
OK :) So the issue can be closed?

**Comment by EsaiasTilly** [comment]
Sure! Thank you for the help!
