### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in Melanchall.DryWetMidi.dll

### ISSUE THREAD

**Issue by valimaties** [melanchall/drywetmidi#97]
Hi Maxim.

I use some code to play a note when I hit "A" key on my PC Keyboard. This is a test example for what I want to do in the future! 
So, I have this code:

```cs
private static Playback playNote;
private static OutputDevice outputDevice;
private static SevenBitNumber NoteToPlay;
private static FourBitNumber ChannelToPlay;
private static bool isKeyDown = false;

private void MidiDeviceSelection_KeyDown(object sender, KeyEventArgs e)
{
    if (isKeyDown) return;
    isKeyDown = true;
    if (e.KeyCode == Keys.A)
    {
        NoteNames n = new NoteNames();
        NoteToPlay = (SevenBitNumber)Array.IndexOf(n.NotesArray, "A3");
        ChannelToPlay = (FourBitNumber)12;
        PlayNote(true, NoteToPlay, ChannelToPlay);
    }
}

private void MidiDeviceSelection_KeyUp(object sender, KeyEventArgs e)
{
    isKeyDown = false;
    PlayNote(false, NoteToPlay, ChannelToPlay);
    playNote.Dispose();
}

private void PlayNote(bool NoteOn, SevenBitNumber noteToPlay, FourBitNumber channelToPlay)
{
    MidiEvent[] eventToPlay = new MidiEvent[]
        {
            NoteOn ? new NoteOnEvent(noteToPlay, SevenBitNumber.MaxValue) { Channel = channelToPlay} :
            new NoteOffEvent(noteToPlay, SevenBitNumber.MinValue) { Channel = channelToPlay}
        };
    using OutputDevice outputDevice = OutputDevice.GetById((int)cmbMidiOutput.SelectedValue);
    playNote = new Playback(eventToPlay, TempoMap.Default, outputDevice);
    playNote.Start();
    Console.WriteLine($"Note{ (NoteOn ? "On" : "Off") } process started");
}
```

So, when I run this code it gives me this error:
```cs
An unhandled exception of type 'System.AccessViolationException' occurred in Melanchall.DryWetMidi.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

What I am doing wrong?

PS: If I change
```cs
playNote = new Playback(eventToPlay, TempoMap.Default, outputDevice);
```
with
```cs
using var playNote = new Playback(eventToPlay, TempoMap.Default, outputDevice);
```
the error does not shows anymore, but no sound on MidiOutput

**Comment by melanchall** [comment]
Hi,

I suppose it's because of your `using` statements:

```csharp
using OutputDevice outputDevice = OutputDevice.GetById((int)cmbMidiOutput.SelectedValue);
...
using var playNote = new Playback(eventToPlay, TempoMap.Default, outputDevice);
```

So when `PlayNote` method exits device and playback disposed and destroyed. There is [info about it](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html#non-blocking-playback) on the library docs:

> You should be very careful with this approach and `using` block. Example below shows the case where **part of MIDI data will not be played because of playback is disposed before the last MIDI event will be played**:
> 
> ```csharp
> using (var outputDevice = OutputDevice.GetByName("Output MIDI device"))
> using (var playback = MidiFile.Read("Some MIDI file.mid").GetPlayback(outputDevice))
> {
>     playback.Start();
> 
>     // ...
> }
> ```
> 
> **With non-blocking approach you should call `Dispose` manually after you've finished work with playback object.**

So you need to remove `using` keyword on device and playback construction and call `Dispose` on these objects manually when your program exits or when you don't need these objects anymore, or when you change device or construct new playback. While you're working with some device and playback based on this device, you mustn't dispose it (via `using` block or explicitly).

**Comment by valimaties** [comment]
Hi Maxim.
I changed using parts, and now it's working, partially.  When I press repeatedly on A key, after some events I get:
```cs
Exception thrown: 'Melanchall.DryWetMidi.Devices.MidiDeviceException' in Melanchall.DryWetMidi.dll
Error on source : Melanchall.DryWetMidi 
		on line: 0
```

**Comment by melanchall** [comment]
Hi,

Please check these conditions:

* You need to create `OutputDevice` only once and then use it. In your code I see that you create it in each call of `PlayNote`.
* When you want to play new note, call `Stop` on current `Playback` object. So when you press `A` key, call `playNote?.Dispose()` first.

**Comment by valimaties** [comment]
> Hi,
> 
> Please check these conditions:
> 
> * You need to create `OutputDevice` only once and then use it. In your code I see that you create it in each call of `PlayNote`.
> * When you want to play new note, call `Stop` on current `Playback` object. So when you press `A` key, call `playNote?.Dispose()` first.

It is not happening in real music world.... You can play for example F3, A3, D4 with different starting points, but finishing on the same bar... Note off event is practically sent in the same moment, but note on will start differently.

**Comment by melanchall** [comment]
In real world you construct playback from all the notes you want to play. So your example is non-real one, yes? I suppose you should test real scenario.

Can the issue be closed or you have more questions?

**Comment by valimaties** [comment]
Sorry for reopened it!
In real-time, I mean I play notes in real-time.... I don't record some midi events and play them after finishing recording. I play notes by pressing on keys. This was a test replacing my Genos keyboard with PC keyboard, to see how I can send my notes to computer thru this API.

**Comment by melanchall** [comment]
Thanks for using the library!

Feel free to open new issues or reopen this one if you have more questions.

**Comment by melanchall** [comment]
@valimaties One more note. If I understand your task correctly, you want to press a key on PC keyboard and play a MIDI note while PC keyboard's key pressed.

In this case you don't need `Playback` at all:

```csharp
private void MidiDeviceSelection_KeyDown(object sender, KeyEventArgs e)
{
    if (isKeyDown) return;
    isKeyDown = true;
    if (e.KeyCode == Keys.A)
    {
        NoteNames n = new NoteNames();
        NoteToPlay = (SevenBitNumber)Array.IndexOf(n.NotesArray, "A3");
        ChannelToPlay = (FourBitNumber)12;
        outputDevice.SendEvent(new NoteOnEvent(NoteToPlay, SevenBitNumber.MaxValue) { Channel = ChannelToPlay });
    }
}

private void MidiDeviceSelection_KeyUp(object sender, KeyEventArgs e)
{
    isKeyDown = false;
    if (e.KeyCode == Keys.A)
    {
        NoteNames n = new NoteNames();
        NoteToPlay = (SevenBitNumber)Array.IndexOf(n.NotesArray, "A3");
        ChannelToPlay = (FourBitNumber)12;
        outputDevice.SendEvent(new NoteOffEvent(NoteToPlay, SevenBitNumber.MaxValue) { Channel = ChannelToPlay });
    }
}
```

So if key down, just send `NoteOnEvent` with corresponding note's number and channel. If key up, just send corresponding `NoteOffEvent`.

**Comment by valimaties** [comment]
Yes... that it is! 
Thank, you!
