### ISSUE TITLE
Any way to send Channel number in a  SendEvent(New ControlChangeEvent(control,value)?

### ISSUE THREAD

**Issue by 737SimGuy** [melanchall/drywetmidi#98]
Any way to send Channel number in a    outputDevice1.SendEvent(New ControlChangeEvent(control,value)) ?

I tried preceding with a ChannelPrefixEvent but that didn't work.

Thanks,
James

**Comment by melanchall** [comment]
Hi James,

You just need to set `Channel` property of an event:

```csharp
outputDevice1.SendEvent(new ControlChangeEvent(control,value) { Channel = (FourBitNumber)channel });
```

**Comment by 737SimGuy** [comment]
Hi,
Wow ok thank you! I’ll give that a go!

One more (last one I hope!): I have been extracting the ControlChange bytes to check for the incoming channel sent from the port. This working but is there an easier way to get the Channel number in a receive event? A property for that? I’ve poked around a lot and can’t find it. 

James

**Comment by melanchall** [comment]
James,

Just cast received event to `ControlChangeEvent` and check its `Channel` property:

```csharp
private static void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
{
    var controlChangeEvent = e.Event as ControlChangeEvent;
    if (controlChangeEvent ! = null) 
    {
        var channel = controlChangeEvent.Channel;
}
```

**Comment by 737SimGuy** [comment]
Hi,
Wow, that’s way to easy! Sorry I didn’t spot it.
Thank you for taking the time to respond. Great tool you have made.
James

**Comment by melanchall** [comment]
Hi James,

Thank you for using the library and the issue!

Max
