### ISSUE TITLE
How to delete all/any empty/blank bars from a Midifile ?

### ISSUE THREAD

**Issue by amigamod** [melanchall/drywetmidi#99]
Hello,

I want to use drywebmidi to delete/remove any empty/blank bar(s) from midi files (the empty bar(s) can be anywhere inside the midi file and there can be 1x blank measure followed by 3x non blank measures, then 2x blank measures etc... all random)

I've looked at the documentation and I'm really starting coding in C#
I was thinking about doing something like that :
- phase 1 : Enumerating all/every blank measure(s) 
  by checking for each measure of the midi file if it contains a midi event or not

- phase 2 :  Deleting every measure(s) identified at phase1 then save the result into 1x new midi file.

How would you achieve this with drywetmidi ? Any suggestion would be really appreciated.

Kind regards.

**Comment by melanchall** [comment]
Hi,

I suggest following approach:

1. Split MIDI file by grid with step of 1 bar
2. Delete empty files that are result of splitting
3. Merge remaining files into new one

DryWetMIDI has tool for first step – [MidiFileSplitter](https://melanchall.github.io/drywetmidi/articles/tools/MIDI-file-splitter.html). But it seems the tool can be improved to solve your task more easily. I'll implement new feature and will provide you a solution.

Second step is obvious.

Thirs step should be done manually. I'll provide you a solution later.

Right now can you please say me what do you mean 'empty bar"? It's a bar without notes or without MIDI events at all?

Max

**Comment by amigamod** [comment]
Hi, that seems very cool if you implement it in the MidiFileSplitter !

for me an emptybar is a bar which has "no midi event" and no "midi note" inside.

Thanks for your support ! :-)

**Comment by melanchall** [comment]
@amigamod Can you please provide sample files with empty bars?

**Comment by amigamod** [comment]
[mid.mid.zip](https://github.com/melanchall/drywetmidi/files/5293047/mid.mid.zip)

**Comment by amigamod** [comment]
[mid2.mid.zip](https://github.com/melanchall/drywetmidi/files/5293205/mid2.mid.zip)
and here is the second one.

**Comment by melanchall** [comment]
@amigamod  OK, thanks.

I think I've implemented all required things for MIDI file splitting. Changes are in _develop_ branch and not released yet, so you need either build the library by yourself from sources or take DLL from here: [DryWetMIDI.5.2.0-bin-net45.zip](https://github.com/melanchall/drywetmidi/files/5314638/DryWetMIDI.5.2.0-bin-net45.zip) or [DryWetMIDI.5.2.0-bin-netstandard20.zip](https://github.com/melanchall/drywetmidi/files/5314641/DryWetMIDI.5.2.0-bin-netstandard20.zip).

Well, now let's try to solve your task.

First of all, we need to read a MIDI file:

```csharp
var midiFile = MidiFile.Read("path\to\midifile.mid");
```

Then we split the file by grid with step of 1 bar:

```csharp
var grid = new SteppedGrid((MidiTimeSpan)100);
var settings = new SliceMidiFileSettings
{
    SplitNotes = false,
    PreserveTimes = false,
    PreserveTrackChunks = true,
    Markers = new SliceMidiFileMarkers
    {
        PartStartMarkerEventFactory = () => new MarkerEvent("S"),
        PartEndMarkerEventFactory = () => new MarkerEvent("F"),
        EmptyPartMarkerEventFactory = () => new MarkerEvent("E")
    }
};

var newFiles = midiFile.SplitByGrid(grid, settings).ToArray();
```

Now we have _Marker_ events with `"E"` text in each empty part. So let's take non-empty parts by checking that a part doesn't have these marker events:

```csharp
var nonEmptyParts = newFiles.Where(f =>
{
    var newTimedEvents = f.GetTimedEvents().ToArray();
    return newTimedEvents.Any() && !newTimedEvents.Any(e => MidiEvent.Equals(e.Event, new MarkerEvent("E")));
})
.ToArray();
```

Now we need to glue them together:

```csharp
var trackChunksCount = midiFile.GetTrackChunks().Count();
var newTrackChunks = new List<TrackChunk>();

for (var i = 0; i < trackChunksCount; i++)
{
    var trackChunk = new TrackChunk();

    foreach (var part in nonEmptyParts)
    {
        trackChunk.Events.AddRange(part.GetTrackChunks().ElementAt(i).Events);
    }

    newTrackChunks.Add(trackChunk);
}

var resultFile = new MidiFile(newTrackChunks)
{
    TimeDivision = midiFile.TimeDivision
};
```

And finally remove all auxiliary events that were added on MIDI file splitting:

```csharp
var equalityCheckSettings = new MidiEventEqualityCheckSettings
{
    CompareDeltaTimes = false
};

resultFile.RemoveTimedEvents(e =>
    MidiEvent.Equals(e.Event, new MarkerEvent("S"), equalityCheckSettings) ||
    MidiEvent.Equals(e.Event, new MarkerEvent("F"), equalityCheckSettings) ||
    MidiEvent.Equals(e.Event, new MarkerEvent("E"), equalityCheckSettings));
```

Now `resultFile` represents original one without empty bars.

Please let me know if described algorithm works or not.

**Comment by amigamod** [comment]
Perfect, I'll try. Very best regards.

**Comment by melanchall** [comment]
@amigamod Any news?

**Comment by melanchall** [comment]
I'm closing the issue since there are no comments.
